(function(d){function a(g,i,j,l){function n(o){o=d[g][i][o]||[];return typeof o=="string"?o.split(/,?\s+/):o}var m=n("getter");if(l.length==1&&typeof l[0]=="string")m=m.concat(n("getterSetter"));return d.inArray(j,m)!=-1}var b=d.fn.remove,c=d.browser.mozilla&&parseFloat(d.browser.version)<1.9;d.ui={version:"1.6rc5",plugin:{add:function(g,i,j){g=d.ui[g].prototype;for(var l in j){g.plugins[l]=g.plugins[l]||[];g.plugins[l].push([i,j[l]])}},call:function(g,i,j){if(i=g.plugins[i])for(var l=0;l<i.length;l++)g.options[i[l][0]]&&
i[l][1].apply(g.element,j)}},contains:function(g,i){return document.compareDocumentPosition?g.compareDocumentPosition(i)&16:g!==i&&g.contains(i)},cssCache:{},css:function(g){if(d.ui.cssCache[g])return d.ui.cssCache[g];var i=d('<div class="ui-gen"></div>').addClass(g).css({position:"absolute",top:"-5000px",left:"-5000px",display:"block"}).appendTo("body");d.ui.cssCache[g]=!!(!/auto|default/.test(i.css("cursor"))||/^[1-9]/.test(i.css("height"))||/^[1-9]/.test(i.css("width"))||!/none/.test(i.css("backgroundImage"))||
!/transparent|rgba\(0, 0, 0, 0\)/.test(i.css("backgroundColor")));try{d("body").get(0).removeChild(i.get(0))}catch(j){}return d.ui.cssCache[g]},hasScroll:function(g,i){if(d(g).css("overflow")=="hidden")return false;var j=i&&i=="left"?"scrollLeft":"scrollTop",l=false;if(g[j]>0)return true;g[j]=1;l=g[j]>0;g[j]=0;return l},isOverAxis:function(g,i,j){return g>i&&g<i+j},isOver:function(g,i,j,l,n,m){return d.ui.isOverAxis(g,j,n)&&d.ui.isOverAxis(i,l,m)},keyCode:{BACKSPACE:8,CAPS_LOCK:20,COMMA:188,CONTROL:17,
DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38}};if(c){var e=d.attr,f=d.fn.removeAttr,h=/^aria-/,k=/^wairole:/;d.attr=function(g,i,j){var l=j!==undefined;return i=="role"?l?e.call(this,g,i,"wairole:"+j):(e.apply(this,arguments)||"").replace(k,""):h.test(i)?l?g.setAttributeNS("http://www.w3.org/2005/07/aaa",
i.replace(h,"aaa:"),j):e.call(this,g,i.replace(h,"aaa:")):e.apply(this,arguments)};d.fn.removeAttr=function(g){return h.test(g)?this.each(function(){this.removeAttributeNS("http://www.w3.org/2005/07/aaa",g.replace(h,""))}):f.call(this,g)}}d.fn.extend({remove:function(){d("*",this).add(this).each(function(){d(this).triggerHandler("remove")});return b.apply(this,arguments)},enableSelection:function(){return this.attr("unselectable","off").css("MozUserSelect","").unbind("selectstart.ui")},disableSelection:function(){return this.attr("unselectable",
"on").css("MozUserSelect","none").bind("selectstart.ui",function(){return false})},scrollParent:function(){var g;g=d.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(d.curCSS(this,"position",1))&&/(auto|scroll)/.test(d.curCSS(this,"overflow",1)+d.curCSS(this,"overflow-y",1)+d.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(d.curCSS(this,
"overflow",1)+d.curCSS(this,"overflow-y",1)+d.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!g.length?d(document):g}});d.extend(d.expr[":"],{data:function(g,i,j){return!!d.data(g,j[3])},tabbable:function(g){var i=g.nodeName.toLowerCase();return g.tabIndex>=0&&("a"==i&&g.href||/input|select|textarea|button/.test(i)&&"hidden"!=g.type&&!g.disabled)&&!(d(g).is(":hidden")||d(g).parents(":hidden").length)}});d.widget=function(g,i){var j=g.split(".")[0];g=g.split(".")[1];
d.fn[g]=function(l){var n=typeof l=="string",m=Array.prototype.slice.call(arguments,1);if(n&&l.substring(0,1)=="_")return this;if(n&&a(j,g,l,m)){var o=d.data(this[0],g);return o?o[l].apply(o,m):undefined}return this.each(function(){var p=d.data(this,g);!p&&!n&&d.data(this,g,new d[j][g](this,l));p&&n&&d.isFunction(p[l])&&p[l].apply(p,m)})};d[j]=d[j]||{};d[j][g]=function(l,n){var m=this;this.namespace=j;this.widgetName=g;this.widgetEventPrefix=d[j][g].eventPrefix||g;this.widgetBaseClass=j+"-"+g;this.options=
d.extend({},d.widget.defaults,d[j][g].defaults,d.metadata&&d.metadata.get(l)[g],n);this.element=d(l).bind("setData."+g,function(o,p,q){if(o.target==l)return m._setData(p,q)}).bind("getData."+g,function(o,p){if(o.target==l)return m._getData(p)}).bind("remove",function(){return m.destroy()});this._init()};d[j][g].prototype=d.extend({},d.widget.prototype,i);d[j][g].getterSetter="option"};d.widget.prototype={_init:function(){},destroy:function(){this.element.removeData(this.widgetName).removeClass(this.widgetBaseClass+
"-disabled "+this.namespace+"-state-disabled").removeAttr("aria-disabled")},option:function(g,i){var j=g,l=this;if(typeof g=="string"){if(i===undefined)return this._getData(g);j={};j[g]=i}d.each(j,function(n,m){l._setData(n,m)})},_getData:function(g){return this.options[g]},_setData:function(g,i){this.options[g]=i;if(g=="disabled")this.element[i?"addClass":"removeClass"](this.widgetBaseClass+"-disabled "+this.namespace+"-state-disabled").attr("aria-disabled",i)},enable:function(){this._setData("disabled",
false)},disable:function(){this._setData("disabled",true)},_trigger:function(g,i,j){var l=this.options[g];g=g==this.widgetEventPrefix?g:this.widgetEventPrefix+g;i=d.Event(i);i.type=g;this.element.trigger(i,j);return!(d.isFunction(l)&&l.call(this.element[0],i,j)===false||i.isDefaultPrevented())}};d.widget.defaults={disabled:false};d.ui.mouse={_mouseInit:function(){var g=this;this.element.bind("mousedown."+this.widgetName,function(i){return g._mouseDown(i)}).bind("click."+this.widgetName,function(){if(g._preventClickEvent)return g._preventClickEvent=
false});if(d.browser.msie){this._mouseUnselectable=this.element.attr("unselectable");this.element.attr("unselectable","on")}this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName);d.browser.msie&&this.element.attr("unselectable",this._mouseUnselectable)},_mouseDown:function(g){this._mouseStarted&&this._mouseUp(g);this._mouseDownEvent=g;var i=this,j=g.which==1,l=typeof this.options.cancel=="string"?d(g.target).parents().add(g.target).filter(this.options.cancel).length:
false;if(!j||l||!this._mouseCapture(g))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){i.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(g)&&this._mouseDelayMet(g)){this._mouseStarted=this._mouseStart(g)!==false;if(!this._mouseStarted){g.preventDefault();return true}}this._mouseMoveDelegate=function(n){return i._mouseMove(n)};this._mouseUpDelegate=function(n){return i._mouseUp(n)};d(document).bind("mousemove."+
this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);d.browser.safari||g.preventDefault();return true},_mouseMove:function(g){if(d.browser.msie&&!g.button)return this._mouseUp(g);if(this._mouseStarted){this._mouseDrag(g);return g.preventDefault()}if(this._mouseDistanceMet(g)&&this._mouseDelayMet(g))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,g)!==false)?this._mouseDrag(g):this._mouseUp(g);return!this._mouseStarted},_mouseUp:function(g){d(document).unbind("mousemove."+
this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;this._preventClickEvent=true;this._mouseStop(g)}return false},_mouseDistanceMet:function(g){return Math.max(Math.abs(this._mouseDownEvent.pageX-g.pageX),Math.abs(this._mouseDownEvent.pageY-g.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}};
d.ui.mouse.defaults={cancel:null,distance:1,delay:0}})(jQuery);
(function(d){d.widget("ui.draggable",d.extend({},d.ui.mouse,{_init:function(){if(this.options.helper=="original"&&!/^(?:r|a|f)/.test(this.element.css("position")))this.element[0].style.position="relative";this.options.cssNamespace&&this.element.addClass(this.options.cssNamespace+"-draggable");this.options.disabled&&this.element.addClass(this.options.cssNamespace+"-draggable-disabled");this._mouseInit()},destroy:function(){if(this.element.data("draggable")){this.element.removeData("draggable").unbind(".draggable").removeClass(this.options.cssNamespace+"-draggable "+
this.options.cssNamespace+"-draggable-dragging "+this.options.cssNamespace+"-draggable-disabled");this._mouseDestroy()}},_mouseCapture:function(a){var b=this.options;if(this.helper||b.disabled||d(a.target).is("."+this.options.cssNamespace+"-resizable-handle"))return false;this.handle=this._getHandle(a);if(!this.handle)return false;return true},_mouseStart:function(a){var b=this.options;this.helper=this._createHelper(a);this._cacheHelperProportions();if(d.ui.ddmanager)d.ui.ddmanager.current=this;this._cacheMargins();
this.cssPosition=this.helper.css("position");this.scrollParent=this.helper.scrollParent();this.offset=this.element.offset();this.offset={top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};d.extend(this.offset,{click:{left:a.pageX-this.offset.left,top:a.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this._generatePosition(a);this.originalPageX=a.pageX;this.originalPageY=a.pageY;b.cursorAt&&this._adjustOffsetFromHelper(b.cursorAt);
b.containment&&this._setContainment();this._trigger("start",a);this._cacheHelperProportions();d.ui.ddmanager&&!b.dropBehaviour&&d.ui.ddmanager.prepareOffsets(this,a);this.helper.addClass(b.cssNamespace+"-draggable-dragging");this._mouseDrag(a,true);return true},_mouseDrag:function(a,b){this.position=this._generatePosition(a);this.positionAbs=this._convertPositionTo("absolute");if(!b){var c=this._uiHash();this._trigger("drag",a,c);this.position=c.position}if(!this.options.axis||this.options.axis!=
"y")this.helper[0].style.left=this.position.left+"px";if(!this.options.axis||this.options.axis!="x")this.helper[0].style.top=this.position.top+"px";d.ui.ddmanager&&d.ui.ddmanager.drag(this,a);return false},_mouseStop:function(a){var b=false;if(d.ui.ddmanager&&!this.options.dropBehaviour)b=d.ui.ddmanager.drop(this,a);if(this.dropped){b=this.dropped;this.dropped=false}if(this.options.revert=="invalid"&&!b||this.options.revert=="valid"&&b||this.options.revert===true||d.isFunction(this.options.revert)&&
this.options.revert.call(this.element,b)){var c=this;d(this.helper).animate(this.originalPosition,parseInt(this.options.revertDuration,10),function(){c._trigger("stop",a);c._clear()})}else{this._trigger("stop",a);this._clear()}return false},_getHandle:function(a){var b=!this.options.handle||!d(this.options.handle,this.element).length?true:false;d(this.options.handle,this.element).find("*").andSelf().each(function(){if(this==a.target)b=true});return b},_createHelper:function(a){var b=this.options;
a=d.isFunction(b.helper)?d(b.helper.apply(this.element[0],[a])):b.helper=="clone"?this.element.clone():this.element;a.parents("body").length||a.appendTo(b.appendTo=="parent"?this.element[0].parentNode:b.appendTo);a[0]!=this.element[0]&&!/(fixed|absolute)/.test(a.css("position"))&&a.css("position","absolute");return a},_adjustOffsetFromHelper:function(a){if(a.left!=undefined)this.offset.click.left=a.left+this.margins.left;if(a.right!=undefined)this.offset.click.left=this.helperProportions.width-a.right+
this.margins.left;if(a.top!=undefined)this.offset.click.top=a.top+this.margins.top;if(a.bottom!=undefined)this.offset.click.top=this.helperProportions.height-a.bottom+this.margins.top},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var a=this.offsetParent.offset();if(this.cssPosition=="absolute"&&this.scrollParent[0]!=document&&d.ui.contains(this.scrollParent[0],this.offsetParent[0])){a.left+=this.scrollParent.scrollLeft();a.top+=this.scrollParent.scrollTop()}if(this.offsetParent[0]==
document.body&&d.browser.mozilla||this.offsetParent[0].tagName&&this.offsetParent[0].tagName.toLowerCase()=="html"&&d.browser.msie)a={top:0,left:0};return{top:a.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:a.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if(this.cssPosition=="relative"){var a=this.element.position();return{top:a.top-(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:a.left-(parseInt(this.helper.css("left"),
10)||0)+this.scrollParent.scrollLeft()}}else return{top:0,left:0}},_cacheMargins:function(){this.margins={left:parseInt(this.element.css("marginLeft"),10)||0,top:parseInt(this.element.css("marginTop"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var a=this.options;if(a.containment=="parent")a.containment=this.helper[0].parentNode;if(a.containment=="document"||a.containment=="window")this.containment=
[0-this.offset.relative.left-this.offset.parent.left,0-this.offset.relative.top-this.offset.parent.top,d(a.containment=="document"?document:window).width()-this.helperProportions.width-this.margins.left,(d(a.containment=="document"?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(a.containment)){var b=d(a.containment)[0];a=d(a.containment).offset();var c=d(b).css("overflow")!="hidden";this.containment=
[a.left+(parseInt(d(b).css("borderLeftWidth"),10)||0)-this.margins.left,a.top+(parseInt(d(b).css("borderTopWidth"),10)||0)-this.margins.top,a.left+(c?Math.max(b.scrollWidth,b.offsetWidth):b.offsetWidth)-(parseInt(d(b).css("borderLeftWidth"),10)||0)-this.helperProportions.width-this.margins.left,a.top+(c?Math.max(b.scrollHeight,b.offsetHeight):b.offsetHeight)-(parseInt(d(b).css("borderTopWidth"),10)||0)-this.helperProportions.height-this.margins.top]}},_convertPositionTo:function(a,b){if(!b)b=this.position;
var c=a=="absolute"?1:-1,e=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&d.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,f=/(html|body)/i.test(e[0].tagName);return{top:b.top+this.offset.relative.top*c+this.offset.parent.top*c-(this.cssPosition=="fixed"?-this.scrollParent.scrollTop():f?0:e.scrollTop())*c,left:b.left+this.offset.relative.left*c+this.offset.parent.left*c-(this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():f?0:e.scrollLeft())*
c}},_generatePosition:function(a){var b=this.options,c=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&d.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,e=/(html|body)/i.test(c[0].tagName);if(this.cssPosition=="relative"&&!(this.scrollParent[0]!=document&&this.scrollParent[0]!=this.offsetParent[0]))this.offset.relative=this._getRelativeOffset();var f=a.pageX,h=a.pageY;if(this.originalPosition){if(this.containment){if(a.pageX-this.offset.click.left<
this.containment[0])f=this.containment[0]+this.offset.click.left;if(a.pageY-this.offset.click.top<this.containment[1])h=this.containment[1]+this.offset.click.top;if(a.pageX-this.offset.click.left>this.containment[2])f=this.containment[2]+this.offset.click.left;if(a.pageY-this.offset.click.top>this.containment[3])h=this.containment[3]+this.offset.click.top}if(b.grid){h=this.originalPageY+Math.round((h-this.originalPageY)/b.grid[1])*b.grid[1];h=this.containment?!(h-this.offset.click.top<this.containment[1]||
h-this.offset.click.top>this.containment[3])?h:!(h-this.offset.click.top<this.containment[1])?h-b.grid[1]:h+b.grid[1]:h;f=this.originalPageX+Math.round((f-this.originalPageX)/b.grid[0])*b.grid[0];f=this.containment?!(f-this.offset.click.left<this.containment[0]||f-this.offset.click.left>this.containment[2])?f:!(f-this.offset.click.left<this.containment[0])?f-b.grid[0]:f+b.grid[0]:f}}return{top:h-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+(this.cssPosition=="fixed"?-this.scrollParent.scrollTop():
e?0:c.scrollTop()),left:f-this.offset.click.left-this.offset.relative.left-this.offset.parent.left+(this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():e?0:c.scrollLeft())}},_clear:function(){this.helper.removeClass(this.options.cssNamespace+"-draggable-dragging");this.helper[0]!=this.element[0]&&!this.cancelHelperRemoval&&this.helper.remove();this.helper=null;this.cancelHelperRemoval=false},_trigger:function(a,b,c){c=c||this._uiHash();d.ui.plugin.call(this,a,[b,c]);if(a=="drag")this.positionAbs=
this._convertPositionTo("absolute");return d.widget.prototype._trigger.call(this,a,b,c)},plugins:{},_uiHash:function(){return{helper:this.helper,position:this.position,absolutePosition:this.positionAbs,options:this.options}}}));d.extend(d.ui.draggable,{version:"1.6rc5",eventPrefix:"drag",defaults:{appendTo:"parent",axis:false,cancel:":input,option",connectToSortable:false,containment:false,cssNamespace:"ui",cursor:"default",cursorAt:null,delay:0,distance:1,grid:false,handle:false,helper:"original",
iframeFix:false,opacity:null,refreshPositions:false,revert:false,revertDuration:500,scope:"default",scroll:true,scrollSensitivity:20,scrollSpeed:20,snap:false,snapMode:"both",snapTolerance:20,stack:false,zIndex:null}});d.ui.plugin.add("draggable","connectToSortable",{start:function(a,b){var c=d(this).data("draggable");c.sortables=[];d(b.options.connectToSortable).each(function(){d(this+"").each(function(){if(d.data(this,"sortable")){var e=d.data(this,"sortable");c.sortables.push({instance:e,shouldRevert:e.options.revert});
e._refreshItems();e._trigger("activate",a,c)}})})},stop:function(a){var b=d(this).data("draggable");d.each(b.sortables,function(){if(this.instance.isOver){this.instance.isOver=0;b.cancelHelperRemoval=true;this.instance.cancelHelperRemoval=false;if(this.shouldRevert)this.instance.options.revert=true;this.instance._mouseStop(a);this.instance.element.triggerHandler("sortreceive",[a,d.extend(this.instance._uiHash(),{sender:b.element})],this.instance.options.receive);this.instance.options.helper=this.instance.options._helper;
b.options.helper=="original"&&this.instance.currentItem.css({top:"auto",left:"auto"})}else{this.instance.cancelHelperRemoval=false;this.instance._trigger("deactivate",a,b)}})},drag:function(a,b){var c=d(this).data("draggable"),e=this,f=function(h){return d.ui.isOver(this.positionAbs.top+this.offset.click.top,this.positionAbs.left+this.offset.click.left,h.top,h.left,h.height,h.width)};d.each(c.sortables,function(){if(f.call(c,this.instance.containerCache)){if(!this.instance.isOver){this.instance.isOver=
1;this.instance.currentItem=d(e).clone().appendTo(this.instance.element).data("sortable-item",true);this.instance.options._helper=this.instance.options.helper;this.instance.options.helper=function(){return b.helper[0]};a.target=this.instance.currentItem[0];this.instance._mouseCapture(a,true);this.instance._mouseStart(a,true,true);this.instance.offset.click.top=c.offset.click.top;this.instance.offset.click.left=c.offset.click.left;this.instance.offset.parent.left-=c.offset.parent.left-this.instance.offset.parent.left;
this.instance.offset.parent.top-=c.offset.parent.top-this.instance.offset.parent.top;c._trigger("toSortable",a);c.dropped=this.instance.element;this.instance.fromOutside=true}this.instance.currentItem&&this.instance._mouseDrag(a)}else if(this.instance.isOver){this.instance.isOver=0;this.instance.cancelHelperRemoval=true;this.instance.options.revert=false;this.instance._mouseStop(a,true);this.instance.options.helper=this.instance.options._helper;this.instance.currentItem.remove();this.instance.placeholder&&
this.instance.placeholder.remove();c._trigger("fromSortable",a);c.dropped=false}})}});d.ui.plugin.add("draggable","cursor",{start:function(a,b){var c=d("body");if(c.css("cursor"))b.options._cursor=c.css("cursor");c.css("cursor",b.options.cursor)},stop:function(a,b){b.options._cursor&&d("body").css("cursor",b.options._cursor)}});d.ui.plugin.add("draggable","iframeFix",{start:function(a,b){d(b.options.iframeFix===true?"iframe":b.options.iframeFix).each(function(){d('<div class="ui-draggable-iframeFix" style="background: #fff;"></div>').css({width:this.offsetWidth+
"px",height:this.offsetHeight+"px",position:"absolute",opacity:"0.001",zIndex:1E3}).css(d(this).offset()).appendTo("body")})},stop:function(){d("div.ui-draggable-iframeFix").each(function(){this.parentNode.removeChild(this)})}});d.ui.plugin.add("draggable","opacity",{start:function(a,b){var c=d(b.helper);if(c.css("opacity"))b.options._opacity=c.css("opacity");c.css("opacity",b.options.opacity)},stop:function(a,b){b.options._opacity&&d(b.helper).css("opacity",b.options._opacity)}});d.ui.plugin.add("draggable",
"scroll",{start:function(){var a=d(this).data("draggable");if(a.scrollParent[0]!=document&&a.scrollParent[0].tagName!="HTML")a.overflowOffset=a.scrollParent.offset()},drag:function(a,b){var c=b.options,e=false,f=d(this).data("draggable");if(f.scrollParent[0]!=document&&f.scrollParent[0].tagName!="HTML"){if(f.overflowOffset.top+f.scrollParent[0].offsetHeight-a.pageY<c.scrollSensitivity)f.scrollParent[0].scrollTop=e=f.scrollParent[0].scrollTop+c.scrollSpeed;else if(a.pageY-f.overflowOffset.top<c.scrollSensitivity)f.scrollParent[0].scrollTop=
e=f.scrollParent[0].scrollTop-c.scrollSpeed;if(f.overflowOffset.left+f.scrollParent[0].offsetWidth-a.pageX<c.scrollSensitivity)f.scrollParent[0].scrollLeft=e=f.scrollParent[0].scrollLeft+c.scrollSpeed;else if(a.pageX-f.overflowOffset.left<c.scrollSensitivity)f.scrollParent[0].scrollLeft=e=f.scrollParent[0].scrollLeft-c.scrollSpeed}else{if(a.pageY-d(document).scrollTop()<c.scrollSensitivity)e=d(document).scrollTop(d(document).scrollTop()-c.scrollSpeed);else if(d(window).height()-(a.pageY-d(document).scrollTop())<
c.scrollSensitivity)e=d(document).scrollTop(d(document).scrollTop()+c.scrollSpeed);if(a.pageX-d(document).scrollLeft()<c.scrollSensitivity)e=d(document).scrollLeft(d(document).scrollLeft()-c.scrollSpeed);else if(d(window).width()-(a.pageX-d(document).scrollLeft())<c.scrollSensitivity)e=d(document).scrollLeft(d(document).scrollLeft()+c.scrollSpeed)}e!==false&&d.ui.ddmanager&&!c.dropBehaviour&&d.ui.ddmanager.prepareOffsets(f,a)}});d.ui.plugin.add("draggable","snap",{start:function(a,b){var c=d(this).data("draggable");
c.snapElements=[];d(b.options.snap.constructor!=String?b.options.snap.items||":data(draggable)":b.options.snap).each(function(){var e=d(this),f=e.offset();this!=c.element[0]&&c.snapElements.push({item:this,width:e.outerWidth(),height:e.outerHeight(),top:f.top,left:f.left})})},drag:function(a,b){for(var c=d(this).data("draggable"),e=b.options.snapTolerance,f=b.absolutePosition.left,h=f+c.helperProportions.width,k=b.absolutePosition.top,g=k+c.helperProportions.height,i=c.snapElements.length-1;i>=0;i--){var j=
c.snapElements[i].left,l=j+c.snapElements[i].width,n=c.snapElements[i].top,m=n+c.snapElements[i].height;if(j-e<f&&f<l+e&&n-e<k&&k<m+e||j-e<f&&f<l+e&&n-e<g&&g<m+e||j-e<h&&h<l+e&&n-e<k&&k<m+e||j-e<h&&h<l+e&&n-e<g&&g<m+e){if(b.options.snapMode!="inner"){var o=Math.abs(n-g)<=e,p=Math.abs(m-k)<=e,q=Math.abs(j-h)<=e,r=Math.abs(l-f)<=e;if(o)b.position.top=c._convertPositionTo("relative",{top:n-c.helperProportions.height,left:0}).top;if(p)b.position.top=c._convertPositionTo("relative",{top:m,left:0}).top;
if(q)b.position.left=c._convertPositionTo("relative",{top:0,left:j-c.helperProportions.width}).left;if(r)b.position.left=c._convertPositionTo("relative",{top:0,left:l}).left}var s=o||p||q||r;if(b.options.snapMode!="outer"){o=Math.abs(n-k)<=e;p=Math.abs(m-g)<=e;q=Math.abs(j-f)<=e;r=Math.abs(l-h)<=e;if(o)b.position.top=c._convertPositionTo("relative",{top:n,left:0}).top;if(p)b.position.top=c._convertPositionTo("relative",{top:m-c.helperProportions.height,left:0}).top;if(q)b.position.left=c._convertPositionTo("relative",
{top:0,left:j}).left;if(r)b.position.left=c._convertPositionTo("relative",{top:0,left:l-c.helperProportions.width}).left}if(!c.snapElements[i].snapping&&(o||p||q||r||s))c.options.snap.snap&&c.options.snap.snap.call(c.element,a,d.extend(c._uiHash(),{snapItem:c.snapElements[i].item}));c.snapElements[i].snapping=o||p||q||r||s}else{c.snapElements[i].snapping&&c.options.snap.release&&c.options.snap.release.call(c.element,a,d.extend(c._uiHash(),{snapItem:c.snapElements[i].item}));c.snapElements[i].snapping=
false}}}});d.ui.plugin.add("draggable","stack",{start:function(a,b){var c=d.makeArray(d(b.options.stack.group)).sort(function(e,f){return(parseInt(d(e).css("zIndex"),10)||b.options.stack.min)-(parseInt(d(f).css("zIndex"),10)||b.options.stack.min)});d(c).each(function(e){this.style.zIndex=b.options.stack.min+e});this[0].style.zIndex=b.options.stack.min+c.length}});d.ui.plugin.add("draggable","zIndex",{start:function(a,b){var c=d(b.helper);if(c.css("zIndex"))b.options._zIndex=c.css("zIndex");c.css("zIndex",
b.options.zIndex)},stop:function(a,b){b.options._zIndex&&d(b.helper).css("zIndex",b.options._zIndex)}})})(jQuery);
(function(d){d.widget("ui.droppable",{_init:function(){var a=this.options.accept;this.isover=0;this.isout=1;this.options.accept=this.options.accept&&d.isFunction(this.options.accept)?this.options.accept:function(b){return b.is(a)};this.proportions={width:this.element[0].offsetWidth,height:this.element[0].offsetHeight};d.ui.ddmanager.droppables[this.options.scope]=d.ui.ddmanager.droppables[this.options.scope]||[];d.ui.ddmanager.droppables[this.options.scope].push(this);this.options.cssNamespace&&this.element.addClass(this.options.cssNamespace+
"-droppable")},destroy:function(){for(var a=d.ui.ddmanager.droppables[this.options.scope],b=0;b<a.length;b++)a[b]==this&&a.splice(b,1);this.element.removeClass(this.options.cssNamespace+"-droppable "+this.options.cssNamespace+"-droppable-disabled").removeData("droppable").unbind(".droppable")},_setData:function(a,b){if(a=="accept")this.options.accept=b&&d.isFunction(b)?b:function(c){return c.is(accept)};else d.widget.prototype._setData.apply(this,arguments)},_activate:function(a){var b=d.ui.ddmanager.current;
d.ui.plugin.call(this,"activate",[a,this.ui(b)]);b&&this._trigger("activate",a,this.ui(b))},_deactivate:function(a){var b=d.ui.ddmanager.current;d.ui.plugin.call(this,"deactivate",[a,this.ui(b)]);b&&this._trigger("deactivate",a,this.ui(b))},_over:function(a){var b=d.ui.ddmanager.current;if(!(!b||(b.currentItem||b.element)[0]==this.element[0]))if(this.options.accept.call(this.element,b.currentItem||b.element)){d.ui.plugin.call(this,"over",[a,this.ui(b)]);this._trigger("over",a,this.ui(b))}},_out:function(a){var b=
d.ui.ddmanager.current;if(!(!b||(b.currentItem||b.element)[0]==this.element[0]))if(this.options.accept.call(this.element,b.currentItem||b.element)){d.ui.plugin.call(this,"out",[a,this.ui(b)]);this._trigger("out",a,this.ui(b))}},_drop:function(a,b){var c=b||d.ui.ddmanager.current;if(!c||(c.currentItem||c.element)[0]==this.element[0])return false;var e=false;this.element.find(":data(droppable)").not("."+c.options.cssNamespace+"-draggable-dragging").each(function(){var f=d.data(this,"droppable");if(f.options.greedy&&
d.ui.intersect(c,d.extend(f,{offset:f.element.offset()}),f.options.tolerance)){e=true;return false}});if(e)return false;if(this.options.accept.call(this.element,c.currentItem||c.element)){d.ui.plugin.call(this,"drop",[a,this.ui(c)]);this._trigger("drop",a,this.ui(c));return this.element}return false},plugins:{},ui:function(a){return{draggable:a.currentItem||a.element,helper:a.helper,position:a.position,absolutePosition:a.positionAbs,options:this.options,element:this.element}}});d.extend(d.ui.droppable,
{version:"1.6rc5",eventPrefix:"drop",defaults:{accept:"*",activeClass:null,cssNamespace:"ui",greedy:false,hoverClass:null,scope:"default",tolerance:"intersect"}});d.ui.intersect=function(a,b,c){if(!b.offset)return false;var e=(a.positionAbs||a.position.absolute).left,f=e+a.helperProportions.width,h=(a.positionAbs||a.position.absolute).top,k=h+a.helperProportions.height,g=b.offset.left,i=g+b.proportions.width,j=b.offset.top,l=j+b.proportions.height;switch(c){case "fit":return g<e&&f<i&&j<h&&k<l;case "intersect":return g<
e+a.helperProportions.width/2&&f-a.helperProportions.width/2<i&&j<h+a.helperProportions.height/2&&k-a.helperProportions.height/2<l;case "pointer":return d.ui.isOver((a.positionAbs||a.position.absolute).top+(a.clickOffset||a.offset.click).top,(a.positionAbs||a.position.absolute).left+(a.clickOffset||a.offset.click).left,j,g,b.proportions.height,b.proportions.width);case "touch":return(h>=j&&h<=l||k>=j&&k<=l||h<j&&k>l)&&(e>=g&&e<=i||f>=g&&f<=i||e<g&&f>i);default:return false}};d.ui.ddmanager={current:null,
droppables:{"default":[]},prepareOffsets:function(a,b){var c=d.ui.ddmanager.droppables[a.options.scope],e=b?b.type:null,f=(a.currentItem||a.element).find(":data(droppable)").andSelf(),h=0;a:for(;h<c.length;h++)if(!(c[h].options.disabled||a&&!c[h].options.accept.call(c[h].element,a.currentItem||a.element))){for(var k=0;k<f.length;k++)if(f[k]==c[h].element[0]){c[h].proportions.height=0;continue a}c[h].visible=c[h].element.css("display")!="none";if(c[h].visible){c[h].offset=c[h].element.offset();c[h].proportions=
{width:c[h].element[0].offsetWidth,height:c[h].element[0].offsetHeight};if(e=="dragstart"||e=="sortactivate")c[h]._activate.call(c[h],b)}}},drop:function(a,b){var c=false;d.each(d.ui.ddmanager.droppables[a.options.scope],function(){if(this.options){if(!this.options.disabled&&this.visible&&d.ui.intersect(a,this,this.options.tolerance))c=this._drop.call(this,b);if(!this.options.disabled&&this.visible&&this.options.accept.call(this.element,a.currentItem||a.element)){this.isout=1;this.isover=0;this._deactivate.call(this,
b)}}});return c},drag:function(a,b){a.options.refreshPositions&&d.ui.ddmanager.prepareOffsets(a,b);d.each(d.ui.ddmanager.droppables[a.options.scope],function(){if(!(this.options.disabled||this.greedyChild||!this.visible)){var c=d.ui.intersect(a,this,this.options.tolerance);if(c=!c&&this.isover==1?"isout":c&&this.isover==0?"isover":null){var e;if(this.options.greedy){var f=this.element.parents(":data(droppable):eq(0)");if(f.length){e=d.data(f[0],"droppable");e.greedyChild=c=="isover"?1:0}}if(e&&c==
"isover"){e.isover=0;e.isout=1;e._out.call(e,b)}this[c]=1;this[c=="isout"?"isover":"isout"]=0;this[c=="isover"?"_over":"_out"].call(this,b);if(e&&c=="isout"){e.isout=0;e.isover=1;e._over.call(e,b)}}}})}};d.ui.plugin.add("droppable","activeClass",{activate:function(a,b){d(this).addClass(b.options.activeClass)},deactivate:function(a,b){d(this).removeClass(b.options.activeClass)},drop:function(a,b){d(this).removeClass(b.options.activeClass)}});d.ui.plugin.add("droppable","hoverClass",{over:function(a,
b){d(this).addClass(b.options.hoverClass)},out:function(a,b){d(this).removeClass(b.options.hoverClass)},drop:function(a,b){d(this).removeClass(b.options.hoverClass)}})})(jQuery);
(function(d){d.widget("ui.resizable",d.extend({},d.ui.mouse,{_init:function(){var a=this,b=this.options,c=this.element.css("position");this.originalElement=this.element;this.element.addClass("ui-resizable").css({position:/static/.test(c)?"relative":c});d.extend(b,{_aspectRatio:!!b.aspectRatio,helper:b.helper||b.ghost||b.animate?b.helper||"ui-resizable-helper":null,knobHandles:b.knobHandles===true?"ui-resizable-knob-handle":b.knobHandles});b.defaultTheme={"ui-resizable":{display:"block"},"ui-resizable-handle":{position:"absolute",
background:"#F2F2F2",fontSize:"0.1px"},"ui-resizable-n":{cursor:"n-resize",height:"4px",left:"0px",right:"0px",borderTop:"1px solid #DEDEDE"},"ui-resizable-s":{cursor:"s-resize",height:"4px",left:"0px",right:"0px",borderBottom:"1px solid #DEDEDE"},"ui-resizable-e":{cursor:"e-resize",width:"4px",top:"0px",bottom:"0px",borderRight:"1px solid #DEDEDE"},"ui-resizable-w":{cursor:"w-resize",width:"4px",top:"0px",bottom:"0px",borderLeft:"1px solid #DEDEDE"},"ui-resizable-se":{cursor:"se-resize",width:"4px",
height:"4px",borderRight:"1px solid #DEDEDE",borderBottom:"1px solid #DEDEDE"},"ui-resizable-sw":{cursor:"sw-resize",width:"4px",height:"4px",borderBottom:"1px solid #DEDEDE",borderLeft:"1px solid #DEDEDE"},"ui-resizable-ne":{cursor:"ne-resize",width:"4px",height:"4px",borderRight:"1px solid #DEDEDE",borderTop:"1px solid #DEDEDE"},"ui-resizable-nw":{cursor:"nw-resize",width:"4px",height:"4px",borderLeft:"1px solid #DEDEDE",borderTop:"1px solid #DEDEDE"}};b.knobTheme={"ui-resizable-handle":{background:"#F2F2F2",
border:"1px solid #808080",height:"8px",width:"8px"},"ui-resizable-n":{cursor:"n-resize",top:"0px",left:"45%"},"ui-resizable-s":{cursor:"s-resize",bottom:"0px",left:"45%"},"ui-resizable-e":{cursor:"e-resize",right:"0px",top:"45%"},"ui-resizable-w":{cursor:"w-resize",left:"0px",top:"45%"},"ui-resizable-se":{cursor:"se-resize",right:"0px",bottom:"0px"},"ui-resizable-sw":{cursor:"sw-resize",left:"0px",bottom:"0px"},"ui-resizable-nw":{cursor:"nw-resize",left:"0px",top:"0px"},"ui-resizable-ne":{cursor:"ne-resize",
right:"0px",top:"0px"}};b._nodeName=this.element[0].nodeName;if(b._nodeName.match(/canvas|textarea|input|select|button|img/i)){c=this.element;/relative/.test(c.css("position"))&&d.browser.opera&&c.css({position:"relative",top:"auto",left:"auto"});c.wrap(d('<div class="ui-wrapper"\tstyle="overflow: hidden;"></div>').css({position:c.css("position"),width:c.outerWidth(),height:c.outerHeight(),top:c.css("top"),left:c.css("left")}));c=this.element;this.element=this.element.parent();this.element.data("resizable",
this);this.element.css({marginLeft:c.css("marginLeft"),marginTop:c.css("marginTop"),marginRight:c.css("marginRight"),marginBottom:c.css("marginBottom")});c.css({marginLeft:0,marginTop:0,marginRight:0,marginBottom:0});d.browser.safari&&b.preventDefault&&c.css("resize","none");b.proportionallyResize=c.css({position:"static",zoom:1,display:"block"});this.element.css({margin:c.css("margin")});this._proportionallyResize()}if(!b.handles)b.handles=!d(".ui-resizable-handle",this.element).length?"e,s,se":
{n:".ui-resizable-n",e:".ui-resizable-e",s:".ui-resizable-s",w:".ui-resizable-w",se:".ui-resizable-se",sw:".ui-resizable-sw",ne:".ui-resizable-ne",nw:".ui-resizable-nw"};if(b.handles.constructor==String){b.zIndex=b.zIndex||1E3;if(b.handles=="all")b.handles="n,e,s,w,se,sw,ne,nw";c=b.handles.split(",");b.handles={};for(var e={handle:"position: absolute; display: none; overflow:hidden;",n:"top: 0pt; width:100%;",e:"right: 0pt; height:100%;",s:"bottom: 0pt; width:100%;",w:"left: 0pt; height:100%;",se:"bottom: 0pt; right: 0px;",
sw:"bottom: 0pt; left: 0px;",ne:"top: 0pt; right: 0px;",nw:"top: 0pt; left: 0px;"},f=0;f<c.length;f++){var h=d.trim(c[f]),k=b.defaultTheme,g="ui-resizable-"+h,i=!d.ui.css(g)&&!b.knobHandles,j=d.ui.css("ui-resizable-knob-handle");k=d.extend(k[g],k["ui-resizable-handle"]);j=d.extend(b.knobTheme[g],!j?b.knobTheme["ui-resizable-handle"]:{});var l=/sw|se|ne|nw/.test(h)?{zIndex:++b.zIndex}:{};g=d(['<div class="ui-resizable-handle ',g,'" style="',i?e[h]:"",e.handle,'"></div>'].join("")).css(l);"se"==h&&
g.addClass("ui-icon ui-icon-gripsmall-diagonal-se");b.handles[h]=".ui-resizable-"+h;this.element.append(g.css(i?k:{}).css(b.knobHandles?j:{}).addClass(b.knobHandles?"ui-resizable-knob-handle":"").addClass(b.knobHandles))}if(b.knobHandles)this.element.addClass("ui-resizable-knob").css(!d.ui.css("ui-resizable-knob")?{}:{})}this._renderAxis=function(n){n=n||this.element;for(var m in b.handles){if(b.handles[m].constructor==String)b.handles[m]=d(b.handles[m],this.element).show();b.transparent&&b.handles[m].css({opacity:0});
if(this.element.is(".ui-wrapper")&&b._nodeName.match(/textarea|input|select|button/i)){var o=d(b.handles[m],this.element),p=0;p=/sw|ne|nw|se|n|s/.test(m)?o.outerHeight():o.outerWidth();o=["padding",/ne|nw|n/.test(m)?"Top":/se|sw|s/.test(m)?"Bottom":/^e$/.test(m)?"Right":"Left"].join("");b.transparent||n.css(o,p);this._proportionallyResize()}d(b.handles[m])}};this._renderAxis(this.element);b._handles=d(".ui-resizable-handle",a.element);b.disableSelection&&b._handles.disableSelection();b._handles.mouseover(function(){if(!b.resizing){if(this.className)var n=
this.className.match(/ui-resizable-(se|sw|ne|nw|n|e|s|w)/i);a.axis=b.axis=n&&n[1]?n[1]:"se"}});if(b.autoHide){b._handles.hide();d(a.element).addClass("ui-resizable-autohide").hover(function(){d(this).removeClass("ui-resizable-autohide");b._handles.show()},function(){if(!b.resizing){d(this).addClass("ui-resizable-autohide");b._handles.hide()}})}this._mouseInit()},destroy:function(){var a=this.element,b=a.children(".ui-resizable").get(0);this._mouseDestroy();var c=function(e){d(e).removeClass("ui-resizable ui-resizable-disabled").removeData("resizable").unbind(".resizable").find(".ui-resizable-handle").remove()};
c(a);if(a.is(".ui-wrapper")&&b){a.parent().append(d(b).css({position:a.css("position"),width:a.outerWidth(),height:a.outerHeight(),top:a.css("top"),left:a.css("left")})).end().remove();c(b)}},_mouseCapture:function(a){if(this.options.disabled)return false;var b=false;for(var c in this.options.handles)if(d(this.options.handles[c])[0]==a.target)b=true;if(!b)return false;return true},_mouseStart:function(a){var b=this.options,c=this.element.position(),e=this.element,f=function(g){return parseInt(g,10)||
0},h=d.browser.msie&&d.browser.version<7;b.resizing=true;b.documentScroll={top:d(document).scrollTop(),left:d(document).scrollLeft()};if(e.is(".ui-draggable")||/absolute/.test(e.css("position"))){var k=d.browser.msie&&!b.containment&&/absolute/.test(e.css("position"))&&!/relative/.test(e.parent().css("position"));e.css({position:"absolute",top:c.top+(k?b.documentScroll.top:0),left:c.left+(k?b.documentScroll.left:0)})}d.browser.opera&&/relative/.test(e.css("position"))&&e.css({position:"relative",
top:"auto",left:"auto"});this._renderProxy();c=f(this.helper.css("left"));f=f(this.helper.css("top"));if(b.containment){c+=d(b.containment).scrollLeft()||0;f+=d(b.containment).scrollTop()||0}this.offset=this.helper.offset();this.position={left:c,top:f};this.size=b.helper||h?{width:e.outerWidth(),height:e.outerHeight()}:{width:e.width(),height:e.height()};this.originalSize=b.helper||h?{width:e.outerWidth(),height:e.outerHeight()}:{width:e.width(),height:e.height()};this.originalPosition={left:c,top:f};
this.sizeDiff={width:e.outerWidth()-e.width(),height:e.outerHeight()-e.height()};this.originalMousePosition={left:a.pageX,top:a.pageY};b.aspectRatio=typeof b.aspectRatio=="number"?b.aspectRatio:this.originalSize.width/this.originalSize.height||1;if(b.preserveCursor){b=d(".ui-resizable-"+this.axis).css("cursor");d("body").css("cursor",b=="auto"?this.axis+"-resize":b)}this._propagate("start",a);return true},_mouseDrag:function(a){var b=this.helper,c=this.options,e=this.originalMousePosition,f=this._change[this.axis];
if(!f)return false;e=f.apply(this,[a,a.pageX-e.left||0,a.pageY-e.top||0]);if(c._aspectRatio||a.shiftKey)e=this._updateRatio(e,a);e=this._respectSize(e,a);this._propagate("resize",a);b.css({top:this.position.top+"px",left:this.position.left+"px",width:this.size.width+"px",height:this.size.height+"px"});!c.helper&&c.proportionallyResize&&this._proportionallyResize();this._updateCache(e);this._trigger("resize",a,this.ui());return false},_mouseStop:function(a){this.options.resizing=false;var b=this.options;
if(b.helper){var c=b.proportionallyResize,e=c&&/textarea/i.test(c.get(0).nodeName);c=e&&d.ui.hasScroll(c.get(0),"left")?0:this.sizeDiff.height;e={width:this.size.width-(e?0:this.sizeDiff.width),height:this.size.height-c};c=parseInt(this.element.css("left"),10)+(this.position.left-this.originalPosition.left)||null;var f=parseInt(this.element.css("top"),10)+(this.position.top-this.originalPosition.top)||null;b.animate||this.element.css(d.extend(e,{top:f,left:c}));b.helper&&!b.animate&&this._proportionallyResize()}b.preserveCursor&&
d("body").css("cursor","auto");this._propagate("stop",a);b.helper&&this.helper.remove();return false},_updateCache:function(a){this.offset=this.helper.offset();if(a.left)this.position.left=a.left;if(a.top)this.position.top=a.top;if(a.height)this.size.height=a.height;if(a.width)this.size.width=a.width},_updateRatio:function(a){var b=this.options,c=this.position,e=this.size,f=this.axis;if(a.height)a.width=e.height*b.aspectRatio;else if(a.width)a.height=e.width/b.aspectRatio;if(f=="sw"){a.left=c.left+
(e.width-a.width);a.top=null}if(f=="nw"){a.top=c.top+(e.height-a.height);a.left=c.left+(e.width-a.width)}return a},_respectSize:function(a){var b=this.options,c=this.axis,e=a.width&&b.maxWidth&&b.maxWidth<a.width,f=a.height&&b.maxHeight&&b.maxHeight<a.height,h=a.width&&b.minWidth&&b.minWidth>a.width,k=a.height&&b.minHeight&&b.minHeight>a.height;if(h)a.width=b.minWidth;if(k)a.height=b.minHeight;if(e)a.width=b.maxWidth;if(f)a.height=b.maxHeight;var g=this.originalPosition.left+this.originalSize.width,
i=this.position.top+this.size.height,j=/sw|nw|w/.test(c);c=/nw|ne|n/.test(c);if(h&&j)a.left=g-b.minWidth;if(e&&j)a.left=g-b.maxWidth;if(k&&c)a.top=i-b.minHeight;if(f&&c)a.top=i-b.maxHeight;if((b=!a.width&&!a.height)&&!a.left&&a.top)a.top=null;else if(b&&!a.top&&a.left)a.left=null;return a},_proportionallyResize:function(){var a=this.options;if(a.proportionallyResize){var b=a.proportionallyResize,c=this.helper||this.element;if(!a.borderDif){var e=[b.css("borderTopWidth"),b.css("borderRightWidth"),
b.css("borderBottomWidth"),b.css("borderLeftWidth")],f=[b.css("paddingTop"),b.css("paddingRight"),b.css("paddingBottom"),b.css("paddingLeft")];a.borderDif=d.map(e,function(h,k){var g=parseInt(h,10)||0,i=parseInt(f[k],10)||0;return g+i})}d.browser.msie&&(d(c).is(":hidden")||d(c).parents(":hidden").length)||b.css({height:c.height()-a.borderDif[0]-a.borderDif[2]||0,width:c.width()-a.borderDif[1]-a.borderDif[3]||0})}},_renderProxy:function(){var a=this.element,b=this.options;this.elementOffset=a.offset();
if(b.helper){this.helper=this.helper||d('<div style="overflow:hidden;"></div>');var c=d.browser.msie&&d.browser.version<7,e=c?1:0;c=c?2:-1;this.helper.addClass(b.helper).css({width:a.outerWidth()+c,height:a.outerHeight()+c,position:"absolute",left:this.elementOffset.left-e+"px",top:this.elementOffset.top-e+"px",zIndex:++b.zIndex});this.helper.appendTo("body");b.disableSelection&&this.helper.disableSelection()}else this.helper=a},_change:{e:function(a,b){return{width:this.originalSize.width+b}},w:function(a,
b){return{left:this.originalPosition.left+b,width:this.originalSize.width-b}},n:function(a,b,c){return{top:this.originalPosition.top+c,height:this.originalSize.height-c}},s:function(a,b,c){return{height:this.originalSize.height+c}},se:function(a,b,c){return d.extend(this._change.s.apply(this,arguments),this._change.e.apply(this,[a,b,c]))},sw:function(a,b,c){return d.extend(this._change.s.apply(this,arguments),this._change.w.apply(this,[a,b,c]))},ne:function(a,b,c){return d.extend(this._change.n.apply(this,
arguments),this._change.e.apply(this,[a,b,c]))},nw:function(a,b,c){return d.extend(this._change.n.apply(this,arguments),this._change.w.apply(this,[a,b,c]))}},_propagate:function(a,b){d.ui.plugin.call(this,a,[b,this.ui()]);a!="resize"&&this._trigger(a,b,this.ui())},plugins:{},ui:function(){return{originalElement:this.originalElement,element:this.element,helper:this.helper,position:this.position,size:this.size,options:this.options,originalSize:this.originalSize,originalPosition:this.originalPosition}}}));
d.extend(d.ui.resizable,{version:"1.6rc5",eventPrefix:"resize",defaults:{alsoResize:false,animate:false,animateDuration:"slow",animateEasing:"swing",aspectRatio:false,autoHide:false,cancel:":input,option",containment:false,delay:0,disableSelection:true,distance:1,ghost:false,grid:false,knobHandles:false,maxHeight:null,maxWidth:null,minHeight:10,minWidth:10,preserveCursor:true,preventDefault:true,proportionallyResize:false,transparent:false}});d.ui.plugin.add("resizable","alsoResize",{start:function(a,
b){var c=b.options;d(this).data("resizable");var e=function(f){d(f).each(function(){d(this).data("resizable-alsoresize",{width:parseInt(d(this).width(),10),height:parseInt(d(this).height(),10),left:parseInt(d(this).css("left"),10),top:parseInt(d(this).css("top"),10)})})};if(typeof c.alsoResize=="object"&&!c.alsoResize.parentNode)if(c.alsoResize.length){c.alsoResize=c.alsoResize[0];e(c.alsoResize)}else d.each(c.alsoResize,function(f){e(f)});else e(c.alsoResize)},resize:function(a,b){var c=b.options,
e=d(this).data("resizable"),f=e.originalSize,h=e.originalPosition,k={height:e.size.height-f.height||0,width:e.size.width-f.width||0,top:e.position.top-h.top||0,left:e.position.left-h.left||0},g=function(i,j){d(i).each(function(){var l=d(this),n=d(this).data("resizable-alsoresize"),m={};d.each((j&&j.length?j:["width","height","top","left"])||["width","height","top","left"],function(o,p){var q=(n[p]||0)+(k[p]||0);if(q&&q>=0)m[p]=q||null});if(/relative/.test(l.css("position"))&&d.browser.opera){e._revertToRelativePosition=
true;l.css({position:"absolute",top:"auto",left:"auto"})}l.css(m)})};typeof c.alsoResize=="object"&&!c.alsoResize.nodeType?d.each(c.alsoResize,function(i,j){g(i,j)}):g(c.alsoResize)},stop:function(){var a=d(this).data("resizable");if(a._revertToRelativePosition&&d.browser.opera){a._revertToRelativePosition=false;el.css({position:"relative"})}d(this).removeData("resizable-alsoresize-start")}});d.ui.plugin.add("resizable","animate",{stop:function(a,b){var c=b.options,e=d(this).data("resizable"),f=c.proportionallyResize,
h=f&&/textarea/i.test(f.get(0).nodeName),k=h&&d.ui.hasScroll(f.get(0),"left")?0:e.sizeDiff.height;h={width:e.size.width-(h?0:e.sizeDiff.width),height:e.size.height-k};k=parseInt(e.element.css("left"),10)+(e.position.left-e.originalPosition.left)||null;var g=parseInt(e.element.css("top"),10)+(e.position.top-e.originalPosition.top)||null;e.element.animate(d.extend(h,g&&k?{top:g,left:k}:{}),{duration:c.animateDuration,easing:c.animateEasing,step:function(){var i={width:parseInt(e.element.css("width"),
10),height:parseInt(e.element.css("height"),10),top:parseInt(e.element.css("top"),10),left:parseInt(e.element.css("left"),10)};f&&f.css({width:i.width,height:i.height});e._updateCache(i);e._propagate("resize",a)}})}});d.ui.plugin.add("resizable","containment",{start:function(a,b){var c=b.options,e=d(this).data("resizable"),f=e.element;c=c.containment;if(f=c instanceof d?c.get(0):/parent/.test(c)?f.parent().get(0):c){e.containerElement=d(f);if(/document/.test(c)||c==document){e.containerOffset={left:0,
top:0};e.containerPosition={left:0,top:0};e.parentData={element:d(document),left:0,top:0,width:d(document).width(),height:d(document).height()||document.body.parentNode.scrollHeight}}else{e.containerOffset=d(f).offset();e.containerPosition=d(f).position();e.containerSize={height:d(f).innerHeight(),width:d(f).innerWidth()};c=e.containerOffset;var h=e.containerSize.height,k=e.containerSize.width;k=d.ui.hasScroll(f,"left")?f.scrollWidth:k;h=d.ui.hasScroll(f)?f.scrollHeight:h;e.parentData={element:f,
left:c.left,top:c.top,width:k,height:h}}}},resize:function(a,b){var c=b.options,e=d(this).data("resizable"),f=e.containerOffset,h=e.position,k=c._aspectRatio||a.shiftKey,g={top:0,left:0},i=e.containerElement;if(i[0]!=document&&/static/.test(i.css("position")))g=e.containerPosition;if(h.left<(c.helper?f.left:0)){e.size.width+=c.helper?e.position.left-f.left:e.position.left-g.left;if(k)e.size.height=e.size.width/c.aspectRatio;e.position.left=c.helper?f.left:0}if(h.top<(c.helper?f.top:0)){e.size.height+=
c.helper?e.position.top-f.top:e.position.top;if(k)e.size.width=e.size.height*c.aspectRatio;e.position.top=c.helper?f.top:0}h=Math.abs((c.helper?e.offset.left-g.left:e.offset.left-g.left)+e.sizeDiff.width);f=Math.abs((c.helper?e.offset.top-g.top:e.offset.top-f.top)+e.sizeDiff.height);if(h+e.size.width>=e.parentData.width){e.size.width=e.parentData.width-h;if(k)e.size.height=e.size.width/c.aspectRatio}if(f+e.size.height>=e.parentData.height){e.size.height=e.parentData.height-f;if(k)e.size.width=e.size.height*
c.aspectRatio}},stop:function(a,b){var c=b.options,e=d(this).data("resizable"),f=e.containerOffset,h=e.containerPosition,k=e.containerElement,g=d(e.helper),i=g.offset(),j=g.outerWidth()-e.sizeDiff.width;e=g.outerHeight()-e.sizeDiff.height;c.helper&&!c.animate&&/relative/.test(k.css("position"))&&d(this).css({left:i.left-h.left-f.left,width:j,height:e});c.helper&&!c.animate&&/static/.test(k.css("position"))&&d(this).css({left:i.left-h.left-f.left,width:j,height:e})}});d.ui.plugin.add("resizable","ghost",
{start:function(a,b){var c=b.options,e=d(this).data("resizable"),f=c.proportionallyResize,h=e.size;e.ghost=f?f.clone():e.element.clone();e.ghost.css({opacity:0.25,display:"block",position:"relative",height:h.height,width:h.width,margin:0,left:0,top:0}).addClass("ui-resizable-ghost").addClass(typeof c.ghost=="string"?c.ghost:"");e.ghost.appendTo(e.helper)},resize:function(){var a=d(this).data("resizable");a.ghost&&a.ghost.css({position:"relative",height:a.size.height,width:a.size.width})},stop:function(){var a=
d(this).data("resizable");a.ghost&&a.helper&&a.helper.get(0).removeChild(a.ghost.get(0))}});d.ui.plugin.add("resizable","grid",{resize:function(a,b){var c=b.options,e=d(this).data("resizable"),f=e.size,h=e.originalSize,k=e.originalPosition,g=e.axis;c.grid=typeof c.grid=="number"?[c.grid,c.grid]:c.grid;var i=Math.round((f.width-h.width)/(c.grid[0]||1))*(c.grid[0]||1);c=Math.round((f.height-h.height)/(c.grid[1]||1))*(c.grid[1]||1);if(/^(se|s|e)$/.test(g)){e.size.width=h.width+i;e.size.height=h.height+
c}else if(/^(ne)$/.test(g)){e.size.width=h.width+i;e.size.height=h.height+c;e.position.top=k.top-c}else{if(/^(sw)$/.test(g)){e.size.width=h.width+i;e.size.height=h.height+c}else{e.size.width=h.width+i;e.size.height=h.height+c;e.position.top=k.top-c}e.position.left=k.left-i}}})})(jQuery);
(function(d){d.widget("ui.selectable",d.extend({},d.ui.mouse,{_init:function(){var a=this;this.element.addClass("ui-selectable");this.dragged=false;var b;this.refresh=function(){b=d(a.options.filter,a.element[0]);b.each(function(){var c=d(this),e=c.offset();d.data(this,"selectable-item",{element:this,$element:c,left:e.left,top:e.top,right:e.left+c.outerWidth(),bottom:e.top+c.outerHeight(),startselected:false,selected:c.hasClass("ui-selected"),selecting:c.hasClass("ui-selecting"),unselecting:c.hasClass("ui-unselecting")})})};
this.refresh();this.selectees=b.addClass("ui-selectee");this._mouseInit();this.helper=d(document.createElement("div")).css({border:"1px dotted black"}).addClass("ui-selectable-helper")},destroy:function(){this.element.removeClass("ui-selectable ui-selectable-disabled").removeData("selectable").unbind(".selectable");this._mouseDestroy()},_mouseStart:function(a){var b=this;this.opos=[a.pageX,a.pageY];if(!this.options.disabled){var c=this.options;this.selectees=d(c.filter,this.element[0]);this._trigger("start",
a);d("body").append(this.helper);this.helper.css({"z-index":100,position:"absolute",left:a.clientX,top:a.clientY,width:0,height:0});c.autoRefresh&&this.refresh();this.selectees.filter(".ui-selected").each(function(){var e=d.data(this,"selectable-item");e.startselected=true;if(!a.metaKey){e.$element.removeClass("ui-selected");e.selected=false;e.$element.addClass("ui-unselecting");e.unselecting=true;b._trigger("unselecting",a,{unselecting:e.element})}});d(a.target).parents().andSelf().each(function(){var e=
d.data(this,"selectable-item");if(e){e.$element.removeClass("ui-unselecting").addClass("ui-selecting");e.unselecting=false;e.selecting=true;e.selected=true;b._trigger("selecting",a,{selecting:e.element});return false}})}},_mouseDrag:function(a){var b=this;this.dragged=true;if(!this.options.disabled){var c=this.options,e=this.opos[0],f=this.opos[1],h=a.pageX,k=a.pageY;if(e>h){var g=h;h=e;e=g}if(f>k){g=k;k=f;f=g}this.helper.css({left:e,top:f,width:h-e,height:k-f});this.selectees.each(function(){var i=
d.data(this,"selectable-item");if(!(!i||i.element==b.element[0])){var j=false;if(c.tolerance=="touch")j=!(i.left>h||i.right<e||i.top>k||i.bottom<f);else if(c.tolerance=="fit")j=i.left>e&&i.right<h&&i.top>f&&i.bottom<k;if(j){if(i.selected){i.$element.removeClass("ui-selected");i.selected=false}if(i.unselecting){i.$element.removeClass("ui-unselecting");i.unselecting=false}if(!i.selecting){i.$element.addClass("ui-selecting");i.selecting=true;b._trigger("selecting",a,{selecting:i.element})}}else{if(i.selecting)if(a.metaKey&&
i.startselected){i.$element.removeClass("ui-selecting");i.selecting=false;i.$element.addClass("ui-selected");i.selected=true}else{i.$element.removeClass("ui-selecting");i.selecting=false;if(i.startselected){i.$element.addClass("ui-unselecting");i.unselecting=true}b._trigger("unselecting",a,{unselecting:i.element})}if(i.selected)if(!a.metaKey&&!i.startselected){i.$element.removeClass("ui-selected");i.selected=false;i.$element.addClass("ui-unselecting");i.unselecting=true;b._trigger("unselecting",a,
{unselecting:i.element})}}}});return false}},_mouseStop:function(a){var b=this;this.dragged=false;d(".ui-unselecting",this.element[0]).each(function(){var c=d.data(this,"selectable-item");c.$element.removeClass("ui-unselecting");c.unselecting=false;c.startselected=false;b._trigger("unselected",a,{unselected:c.element})});d(".ui-selecting",this.element[0]).each(function(){var c=d.data(this,"selectable-item");c.$element.removeClass("ui-selecting").addClass("ui-selected");c.selecting=false;c.selected=
true;c.startselected=true;b._trigger("selected",a,{selected:c.element})});this._trigger("stop",a);this.helper.remove();return false}}));d.extend(d.ui.selectable,{version:"1.6rc5",defaults:{appendTo:"body",autoRefresh:true,cancel:":input,option",delay:0,distance:0,filter:"*",tolerance:"touch"}})})(jQuery);
(function(d){d.widget("ui.sortable",d.extend({},d.ui.mouse,{_init:function(){this.containerCache={};this.options.cssNamespace&&this.element.addClass(this.options.cssNamespace+"-sortable");this.refresh();this.floating=this.items.length?/left|right/.test(this.items[0].item.css("float")):false;this.offset=this.element.offset();this._mouseInit()},destroy:function(){this.element.removeClass(this.options.cssNamespace+"-sortable "+this.options.cssNamespace+"-sortable-disabled").removeData("sortable").unbind(".sortable");
this._mouseDestroy();for(var a=this.items.length-1;a>=0;a--)this.items[a].item.removeData("sortable-item")},_mouseCapture:function(a,b){if(this.reverting)return false;if(this.options.disabled||this.options.type=="static")return false;this._refreshItems(a);var c=null,e=this;d(a.target).parents().each(function(){if(d.data(this,"sortable-item")==e){c=d(this);return false}});if(d.data(a.target,"sortable-item")==e)c=d(a.target);if(!c)return false;if(this.options.handle&&!b){var f=false;d(this.options.handle,
c).find("*").andSelf().each(function(){if(this==a.target)f=true});if(!f)return false}this.currentItem=c;this._removeCurrentsFromItems();return true},_mouseStart:function(a,b,c){b=this.options;this.currentContainer=this;this.refreshPositions();this.helper=this._createHelper(a);this._cacheHelperProportions();this._cacheMargins();this.scrollParent=this.helper.scrollParent();this.offset=this.currentItem.offset();this.offset={top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};
this.helper.css("position","absolute");this.cssPosition=this.helper.css("position");d.extend(this.offset,{click:{left:a.pageX-this.offset.left,top:a.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this._generatePosition(a);this.originalPageX=a.pageX;this.originalPageY=a.pageY;b.cursorAt&&this._adjustOffsetFromHelper(b.cursorAt);this.domPosition={prev:this.currentItem.prev()[0],parent:this.currentItem.parent()[0]};this.helper[0]!=this.currentItem[0]&&
this.currentItem.hide();this._createPlaceholder();b.containment&&this._setContainment();this._trigger("start",a);this._preserveHelperProportions||this._cacheHelperProportions();if(!c)for(c=this.containers.length-1;c>=0;c--)this.containers[c]._trigger("activate",a,this);if(d.ui.ddmanager)d.ui.ddmanager.current=this;d.ui.ddmanager&&!b.dropBehaviour&&d.ui.ddmanager.prepareOffsets(this,a);this.dragging=true;this.helper.addClass(b.cssNamespace+"-sortable-helper");this._mouseDrag(a);return true},_mouseDrag:function(a){this.position=
this._generatePosition(a);this.positionAbs=this._convertPositionTo("absolute");if(!this.lastPositionAbs)this.lastPositionAbs=this.positionAbs;d.ui.plugin.call(this,"sort",[a,this._uiHash()]);this.positionAbs=this._convertPositionTo("absolute");if(!this.options.axis||this.options.axis!="y")this.helper[0].style.left=this.position.left+"px";if(!this.options.axis||this.options.axis!="x")this.helper[0].style.top=this.position.top+"px";for(var b=this.items.length-1;b>=0;b--){var c=this.items[b],e=c.item[0],
f=this._intersectsWithPointer(c);if(f)if(e!=this.currentItem[0]&&this.placeholder[f==1?"next":"prev"]()[0]!=e&&!d.ui.contains(this.placeholder[0],e)&&(this.options.type=="semi-dynamic"?!d.ui.contains(this.element[0],e):true)){this.direction=f==1?"down":"up";if(this.options.tolerance=="pointer"||this._intersectsWithSides(c))this.options.sortIndicator.call(this,a,c);else break;this._trigger("change",a);break}}this._contactContainers(a);d.ui.ddmanager&&d.ui.ddmanager.drag(this,a);this._trigger("sort",
a);this.lastPositionAbs=this.positionAbs;return false},_mouseStop:function(a,b){if(a){d.ui.ddmanager&&!this.options.dropBehaviour&&d.ui.ddmanager.drop(this,a);if(this.options.revert){var c=this,e=c.placeholder.offset();c.reverting=true;d(this.helper).animate({left:e.left-this.offset.parent.left-c.margins.left+(this.offsetParent[0]==document.body?0:this.offsetParent[0].scrollLeft),top:e.top-this.offset.parent.top-c.margins.top+(this.offsetParent[0]==document.body?0:this.offsetParent[0].scrollTop)},
parseInt(this.options.revert,10)||500,function(){c._clear(a)})}else this._clear(a,b);return false}},cancel:function(){if(this.dragging){this._mouseUp();this.options.helper=="original"?this.currentItem.css(this._storedCSS).removeClass(this.options.cssNamespace+"-sortable-helper"):this.currentItem.show();for(var a=this.containers.length-1;a>=0;a--){this.containers[a]._trigger("deactivate",null,this);if(this.containers[a].containerCache.over){this.containers[a]._trigger("out",null,this);this.containers[a].containerCache.over=
0}}}this.placeholder[0].parentNode&&this.placeholder[0].parentNode.removeChild(this.placeholder[0]);this.options.helper!="original"&&this.helper&&this.helper[0].parentNode&&this.helper.remove();d.extend(this,{helper:null,dragging:false,reverting:false,_noFinalSort:null});this.domPosition.prev?d(this.domPosition.prev).after(this.currentItem):d(this.domPosition.parent).prepend(this.currentItem);return true},serialize:function(a){var b=this._getItemsAsjQuery(a&&a.connected),c=[];a=a||{};d(b).each(function(){var e=
(d(a.item||this).attr(a.attribute||"id")||"").match(a.expression||/(.+)[-=_](.+)/);if(e)c.push((a.key||e[1]+"[]")+"="+(a.key&&a.expression?e[1]:e[2]))});return c.join("&")},toArray:function(a){var b=this._getItemsAsjQuery(a&&a.connected),c=[];a=a||{};b.each(function(){c.push(d(a.item||this).attr(a.attribute||"id")||"")});return c},_intersectsWith:function(a){var b=this.positionAbs.left,c=b+this.helperProportions.width,e=this.positionAbs.top,f=e+this.helperProportions.height,h=a.left,k=h+a.width,g=
a.top,i=g+a.height,j=this.offset.click.top,l=this.offset.click.left;return this.options.tolerance=="pointer"||this.options.forcePointerForContainers||this.options.tolerance!="pointer"&&this.helperProportions[this.floating?"width":"height"]>a[this.floating?"width":"height"]?e+j>g&&e+j<i&&b+l>h&&b+l<k:h<b+this.helperProportions.width/2&&c-this.helperProportions.width/2<k&&g<e+this.helperProportions.height/2&&f-this.helperProportions.height/2<i},_intersectsWithPointer:function(a){var b=d.ui.isOverAxis(this.positionAbs.top+
this.offset.click.top,a.top,a.height);a=d.ui.isOverAxis(this.positionAbs.left+this.offset.click.left,a.left,a.width);b=b&&a;a=this._getDragVerticalDirection();var c=this._getDragHorizontalDirection();if(!b)return false;return this.floating?c&&c=="right"||a=="down"?2:1:a&&(a=="down"?2:1)},_intersectsWithSides:function(a){var b=d.ui.isOverAxis(this.positionAbs.top+this.offset.click.top,a.top+a.height/2,a.height);a=d.ui.isOverAxis(this.positionAbs.left+this.offset.click.left,a.left+a.width/2,a.width);
var c=this._getDragVerticalDirection(),e=this._getDragHorizontalDirection();return this.floating&&e?e=="right"&&a||e=="left"&&!a:c&&(c=="down"&&b||c=="up"&&!b)},_getDragVerticalDirection:function(){var a=this.positionAbs.top-this.lastPositionAbs.top;return a!=0&&(a>0?"down":"up")},_getDragHorizontalDirection:function(){var a=this.positionAbs.left-this.lastPositionAbs.left;return a!=0&&(a>0?"right":"left")},refresh:function(a){this._refreshItems(a);this.refreshPositions()},_getItemsAsjQuery:function(a){var b=
[],c=[];if(this.options.connectWith&&a)for(a=this.options.connectWith.length-1;a>=0;a--)for(var e=d(this.options.connectWith[a]),f=e.length-1;f>=0;f--){var h=d.data(e[f],"sortable");if(h&&h!=this&&!h.options.disabled)c.push([d.isFunction(h.options.items)?h.options.items.call(h.element):d(h.options.items,h.element).not("."+h.options.cssNamespace+"-sortable-helper"),h])}c.push([d.isFunction(this.options.items)?this.options.items.call(this.element,null,{options:this.options,item:this.currentItem}):d(this.options.items,
this.element).not("."+this.options.cssNamespace+"-sortable-helper"),this]);for(a=c.length-1;a>=0;a--)c[a][0].each(function(){b.push(this)});return d(b)},_removeCurrentsFromItems:function(){for(var a=this.currentItem.find(":data(sortable-item)"),b=0;b<this.items.length;b++)for(var c=0;c<a.length;c++)a[c]==this.items[b].item[0]&&this.items.splice(b,1)},_refreshItems:function(a){this.items=[];this.containers=[this];var b=this.items,c=[[d.isFunction(this.options.items)?this.options.items.call(this.element[0],
a,{item:this.currentItem}):d(this.options.items,this.element),this]];if(this.options.connectWith)for(var e=this.options.connectWith.length-1;e>=0;e--)for(var f=d(this.options.connectWith[e]),h=f.length-1;h>=0;h--){var k=d.data(f[h],"sortable");if(k&&k!=this&&!k.options.disabled){c.push([d.isFunction(k.options.items)?k.options.items.call(k.element[0],a,{item:this.currentItem}):d(k.options.items,k.element),k]);this.containers.push(k)}}for(e=c.length-1;e>=0;e--){a=c[e][1];f=c[e][0];h=0;for(k=f.length;h<
k;h++){var g=d(f[h]);g.data("sortable-item",a);b.push({item:g,instance:a,width:0,height:0,left:0,top:0})}}},refreshPositions:function(a){if(this.offsetParent&&this.helper)this.offset.parent=this._getParentOffset();for(var b=this.items.length-1;b>=0;b--){var c=this.items[b];if(!(c.instance!=this.currentContainer&&this.currentContainer&&c.item[0]!=this.currentItem[0])){var e=this.options.toleranceElement?d(this.options.toleranceElement,c.item):c.item;if(!a)if(this.options.accurateIntersection){c.width=
e.outerWidth();c.height=e.outerHeight()}else{c.width=e[0].offsetWidth;c.height=e[0].offsetHeight}e=e.offset();c.left=e.left;c.top=e.top}}if(this.options.custom&&this.options.custom.refreshContainers)this.options.custom.refreshContainers.call(this);else for(b=this.containers.length-1;b>=0;b--){e=this.containers[b].element.offset();this.containers[b].containerCache.left=e.left;this.containers[b].containerCache.top=e.top;this.containers[b].containerCache.width=this.containers[b].element.outerWidth();
this.containers[b].containerCache.height=this.containers[b].element.outerHeight()}},_createPlaceholder:function(a){var b=a||this,c=b.options;if(!c.placeholder||c.placeholder.constructor==String){var e=c.placeholder;c.placeholder={element:function(){var f=d(document.createElement(b.currentItem[0].nodeName)).addClass(e||b.currentItem[0].className+" "+b.options.cssNamespace+"-sortable-placeholder").removeClass(b.options.cssNamespace+"-sortable-helper")[0];if(!e)f.style.visibility="hidden";return f},
update:function(f,h){if(!(e&&!c.forcePlaceholderSize)){h.height()||h.height(b.currentItem.innerHeight()-parseInt(b.currentItem.css("paddingTop")||0,10)-parseInt(b.currentItem.css("paddingBottom")||0,10));h.width()||h.width(b.currentItem.innerWidth()-parseInt(b.currentItem.css("paddingLeft")||0,10)-parseInt(b.currentItem.css("paddingRight")||0,10))}}}}b.placeholder=d(c.placeholder.element.call(b.element,b.currentItem));b.currentItem.after(b.placeholder);c.placeholder.update(b,b.placeholder)},_contactContainers:function(a){for(var b=
this.containers.length-1;b>=0;b--)if(this._intersectsWith(this.containers[b].containerCache)){if(!this.containers[b].containerCache.over){if(this.currentContainer!=this.containers[b]){for(var c=1E4,e=null,f=this.positionAbs[this.containers[b].floating?"left":"top"],h=this.items.length-1;h>=0;h--)if(d.ui.contains(this.containers[b].element[0],this.items[h].item[0])){var k=this.items[h][this.containers[b].floating?"left":"top"];if(Math.abs(k-f)<c){c=Math.abs(k-f);e=this.items[h]}}if(!e&&!this.options.dropOnEmpty)continue;
this.currentContainer=this.containers[b];e?this.options.sortIndicator.call(this,a,e,null,true):this.options.sortIndicator.call(this,a,null,this.containers[b].element,true);this._trigger("change",a);this.containers[b]._trigger("change",a,this);this.options.placeholder.update(this.currentContainer,this.placeholder)}this.containers[b]._trigger("over",a,this);this.containers[b].containerCache.over=1}}else if(this.containers[b].containerCache.over){this.containers[b]._trigger("out",a,this);this.containers[b].containerCache.over=
0}},_createHelper:function(a){var b=this.options;a=d.isFunction(b.helper)?d(b.helper.apply(this.element[0],[a,this.currentItem])):b.helper=="clone"?this.currentItem.clone():this.currentItem;a.parents("body").length||d(b.appendTo!="parent"?b.appendTo:this.currentItem[0].parentNode)[0].appendChild(a[0]);if(a[0]==this.currentItem[0])this._storedCSS={width:this.currentItem[0].style.width,height:this.currentItem[0].style.height,position:this.currentItem.css("position"),top:this.currentItem.css("top"),
left:this.currentItem.css("left")};if(a[0].style.width==""||b.forceHelperSize)a.width(this.currentItem.width());if(a[0].style.height==""||b.forceHelperSize)a.height(this.currentItem.height());return a},_adjustOffsetFromHelper:function(a){if(a.left!=undefined)this.offset.click.left=a.left+this.margins.left;if(a.right!=undefined)this.offset.click.left=this.helperProportions.width-a.right+this.margins.left;if(a.top!=undefined)this.offset.click.top=a.top+this.margins.top;if(a.bottom!=undefined)this.offset.click.top=
this.helperProportions.height-a.bottom+this.margins.top},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var a=this.offsetParent.offset();if(this.cssPosition=="absolute"&&this.scrollParent[0]!=document&&d.ui.contains(this.scrollParent[0],this.offsetParent[0])){a.left+=this.scrollParent.scrollLeft();a.top+=this.scrollParent.scrollTop()}if(this.offsetParent[0]==document.body&&d.browser.mozilla||this.offsetParent[0].tagName&&this.offsetParent[0].tagName.toLowerCase()=="html"&&
d.browser.msie)a={top:0,left:0};return{top:a.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:a.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if(this.cssPosition=="relative"){var a=this.currentItem.position();return{top:a.top-(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:a.left-(parseInt(this.helper.css("left"),10)||0)+this.scrollParent.scrollLeft()}}else return{top:0,left:0}},_cacheMargins:function(){this.margins=
{left:parseInt(this.currentItem.css("marginLeft"),10)||0,top:parseInt(this.currentItem.css("marginTop"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var a=this.options;if(a.containment=="parent")a.containment=this.helper[0].parentNode;if(a.containment=="document"||a.containment=="window")this.containment=[0-this.offset.relative.left-this.offset.parent.left,0-this.offset.relative.top-
this.offset.parent.top,d(a.containment=="document"?document:window).width()-this.helperProportions.width-this.margins.left,(d(a.containment=="document"?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(a.containment)){var b=d(a.containment)[0];a=d(a.containment).offset();var c=d(b).css("overflow")!="hidden";this.containment=[a.left+(parseInt(d(b).css("borderLeftWidth"),10)||0)-this.margins.left,a.top+
(parseInt(d(b).css("borderTopWidth"),10)||0)-this.margins.top,a.left+(c?Math.max(b.scrollWidth,b.offsetWidth):b.offsetWidth)-(parseInt(d(b).css("borderLeftWidth"),10)||0)-this.helperProportions.width-this.margins.left,a.top+(c?Math.max(b.scrollHeight,b.offsetHeight):b.offsetHeight)-(parseInt(d(b).css("borderTopWidth"),10)||0)-this.helperProportions.height-this.margins.top]}},_convertPositionTo:function(a,b){if(!b)b=this.position;var c=a=="absolute"?1:-1,e=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=
document&&d.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,f=/(html|body)/i.test(e[0].tagName);return{top:b.top+this.offset.relative.top*c+this.offset.parent.top*c-(this.cssPosition=="fixed"?-this.scrollParent.scrollTop():f?0:e.scrollTop())*c,left:b.left+this.offset.relative.left*c+this.offset.parent.left*c-(this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():f?0:e.scrollLeft())*c}},_generatePosition:function(a){var b=this.options,c=this.cssPosition==
"absolute"&&!(this.scrollParent[0]!=document&&d.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,e=/(html|body)/i.test(c[0].tagName);if(this.cssPosition=="relative"&&!(this.scrollParent[0]!=document&&this.scrollParent[0]!=this.offsetParent[0]))this.offset.relative=this._getRelativeOffset();var f=a.pageX,h=a.pageY;if(this.originalPosition){if(this.containment){if(a.pageX-this.offset.click.left<this.containment[0])f=this.containment[0]+this.offset.click.left;
if(a.pageY-this.offset.click.top<this.containment[1])h=this.containment[1]+this.offset.click.top;if(a.pageX-this.offset.click.left>this.containment[2])f=this.containment[2]+this.offset.click.left;if(a.pageY-this.offset.click.top>this.containment[3])h=this.containment[3]+this.offset.click.top}if(b.grid){h=this.originalPageY+Math.round((h-this.originalPageY)/b.grid[1])*b.grid[1];h=this.containment?!(h-this.offset.click.top<this.containment[1]||h-this.offset.click.top>this.containment[3])?h:!(h-this.offset.click.top<
this.containment[1])?h-b.grid[1]:h+b.grid[1]:h;f=this.originalPageX+Math.round((f-this.originalPageX)/b.grid[0])*b.grid[0];f=this.containment?!(f-this.offset.click.left<this.containment[0]||f-this.offset.click.left>this.containment[2])?f:!(f-this.offset.click.left<this.containment[0])?f-b.grid[0]:f+b.grid[0]:f}}return{top:h-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+(this.cssPosition=="fixed"?-this.scrollParent.scrollTop():e?0:c.scrollTop()),left:f-this.offset.click.left-
this.offset.relative.left-this.offset.parent.left+(this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():e?0:c.scrollLeft())}},_rearrange:function(a,b,c,e){c?c[0].appendChild(this.placeholder[0]):b.item[0].parentNode.insertBefore(this.placeholder[0],this.direction=="down"?b.item[0]:b.item[0].nextSibling);this.counter=this.counter?++this.counter:1;var f=this,h=this.counter;window.setTimeout(function(){h==f.counter&&f.refreshPositions(!e)},0)},_clear:function(a,b){this.reverting=false;this._noFinalSort||
this.placeholder.before(this.currentItem);this._noFinalSort=null;if(this.helper[0]==this.currentItem[0]){for(var c in this._storedCSS)if(this._storedCSS[c]=="auto"||this._storedCSS[c]=="static")this._storedCSS[c]="";this.currentItem.css(this._storedCSS).removeClass(this.options.cssNamespace+"-sortable-helper")}else this.currentItem.show();this.fromOutside&&this._trigger("receive",a,this,b);if(this.fromOutside||this.domPosition.prev!=this.currentItem.prev().not("."+this.options.cssNamespace+"-sortable-helper")[0]||
this.domPosition.parent!=this.currentItem.parent()[0])this._trigger("update",a,null,b);if(!d.ui.contains(this.element[0],this.currentItem[0])){this._trigger("remove",a,null,b);for(c=this.containers.length-1;c>=0;c--)if(d.ui.contains(this.containers[c].element[0],this.currentItem[0])){this.containers[c]._trigger("receive",a,this,b);this.containers[c]._trigger("update",a,this,b)}}for(c=this.containers.length-1;c>=0;c--){this.containers[c]._trigger("deactivate",a,this,b);if(this.containers[c].containerCache.over){this.containers[c]._trigger("out",
a,this);this.containers[c].containerCache.over=0}}this.dragging=false;if(this.cancelHelperRemoval){this._trigger("beforeStop",a,null,b);this._trigger("stop",a,null,b);return false}this._trigger("beforeStop",a,null,b);this.placeholder[0].parentNode.removeChild(this.placeholder[0]);this.helper[0]!=this.currentItem[0]&&this.helper.remove();this.helper=null;this._trigger("stop",a,null,b);this.fromOutside=false;return true},_trigger:function(a,b,c,e){d.ui.plugin.call(this,a,[b,this._uiHash(c)]);e||d.widget.prototype._trigger.call(this,
a,b,this._uiHash(c))===false&&this.cancel()},plugins:{},_uiHash:function(a){var b=a||this;return{helper:b.helper,placeholder:b.placeholder||d([]),position:b.position,absolutePosition:b.positionAbs,item:b.currentItem,sender:a?a.element:null}}}));d.extend(d.ui.sortable,{getter:"serialize toArray",version:"1.6rc5",defaults:{accurateIntersection:true,appendTo:"parent",cancel:":input,option",cssNamespace:"ui",delay:0,distance:1,dropOnEmpty:true,forcePlaceholderSize:false,forceHelperSize:false,helper:"original",
items:"> *",scope:"default",scroll:true,scrollSensitivity:20,scrollSpeed:20,sortIndicator:d.ui.sortable.prototype._rearrange,tolerance:"default",zIndex:1E3}});d.ui.plugin.add("sortable","cursor",{start:function(){var a=d("body"),b=d(this).data("sortable");if(a.css("cursor"))b.options._cursor=a.css("cursor");a.css("cursor",b.options.cursor)},beforeStop:function(){var a=d(this).data("sortable");a.options._cursor&&d("body").css("cursor",a.options._cursor)}});d.ui.plugin.add("sortable","opacity",{start:function(a,
b){var c=b.helper,e=d(this).data("sortable");if(c.css("opacity"))e.options._opacity=c.css("opacity");c.css("opacity",e.options.opacity)},beforeStop:function(a,b){var c=d(this).data("sortable");c.options._opacity&&d(b.helper).css("opacity",c.options._opacity)}});d.ui.plugin.add("sortable","scroll",{start:function(){var a=d(this).data("sortable");if(a.scrollParent[0]!=document&&a.scrollParent[0].tagName!="HTML")a.overflowOffset=a.scrollParent.offset()},sort:function(a){var b=d(this).data("sortable"),
c=b.options,e=false;if(b.scrollParent[0]!=document&&b.scrollParent[0].tagName!="HTML"){if(b.overflowOffset.top+b.scrollParent[0].offsetHeight-a.pageY<c.scrollSensitivity)b.scrollParent[0].scrollTop=e=b.scrollParent[0].scrollTop+c.scrollSpeed;else if(a.pageY-b.overflowOffset.top<c.scrollSensitivity)b.scrollParent[0].scrollTop=e=b.scrollParent[0].scrollTop-c.scrollSpeed;if(b.overflowOffset.left+b.scrollParent[0].offsetWidth-a.pageX<c.scrollSensitivity)b.scrollParent[0].scrollLeft=e=b.scrollParent[0].scrollLeft+
c.scrollSpeed;else if(a.pageX-b.overflowOffset.left<c.scrollSensitivity)b.scrollParent[0].scrollLeft=e=b.scrollParent[0].scrollLeft-c.scrollSpeed}else{if(a.pageY-d(document).scrollTop()<c.scrollSensitivity)e=d(document).scrollTop(d(document).scrollTop()-c.scrollSpeed);else if(d(window).height()-(a.pageY-d(document).scrollTop())<c.scrollSensitivity)e=d(document).scrollTop(d(document).scrollTop()+c.scrollSpeed);if(a.pageX-d(document).scrollLeft()<c.scrollSensitivity)e=d(document).scrollLeft(d(document).scrollLeft()-
c.scrollSpeed);else if(d(window).width()-(a.pageX-d(document).scrollLeft())<c.scrollSensitivity)e=d(document).scrollLeft(d(document).scrollLeft()+c.scrollSpeed)}e!==false&&d.ui.ddmanager&&!c.dropBehaviour&&d.ui.ddmanager.prepareOffsets(b,a)}});d.ui.plugin.add("sortable","zIndex",{start:function(a,b){var c=b.helper,e=d(this).data("sortable");if(c.css("zIndex"))e.options._zIndex=c.css("zIndex");c.css("zIndex",e.options.zIndex)},beforeStop:function(a,b){var c=d(this).data("sortable");if(c.options._zIndex)d(b.helper).css("zIndex",
c.options._zIndex=="auto"?"":c.options._zIndex)}})})(jQuery);
