dojo.provide("dojo.dnd.HtmlDragManager");dojo.require("dojo.dnd.DragAndDrop");dojo.require("dojo.event.*");dojo.require("dojo.lang.array");dojo.require("dojo.html.common");dojo.require("dojo.html.layout");
dojo.declare("dojo.dnd.HtmlDragManager",dojo.dnd.DragManager,{disabled:false,nestedTargets:false,mouseDownTimer:null,dsCounter:0,dsPrefix:"dojoDragSource",dropTargetDimensions:[],currentDropTarget:null,previousDropTarget:null,_dragTriggered:false,selectedSources:[],dragObjects:[],dragSources:[],dropTargets:[],currentX:null,currentY:null,lastX:null,lastY:null,mouseDownX:null,mouseDownY:null,threshold:7,dropAcceptable:false,cancelEvent:function(a){a.stopPropagation();a.preventDefault()},registerDragSource:function(a){if(a.domNode){var b=
this.dsPrefix,c=b+"Idx_"+this.dsCounter++;a.dragSourceId=c;this.dragSources[c]=a;a.domNode.setAttribute(b,c);dojo.render.html.ie&&dojo.event.browser.addListener(a.domNode,"ondragstart",this.cancelEvent)}},unregisterDragSource:function(a){if(a.domNode){var b=this.dsPrefix,c=a.dragSourceId;delete a.dragSourceId;delete this.dragSources[c];a.domNode.setAttribute(b,null);dojo.render.html.ie&&dojo.event.browser.removeListener(a.domNode,"ondragstart",this.cancelEvent)}},registerDropTarget:function(a){this.dropTargets.push(a)},
unregisterDropTarget:function(a){a=dojo.lang.find(this.dropTargets,a,true);a>=0&&this.dropTargets.splice(a,1)},getDragSource:function(a){a=a.target;if(a!==dojo.body()){for(var b=dojo.html.getAttribute(a,this.dsPrefix);!b&&a;){a=a.parentNode;if(!a||a===dojo.body())return;b=dojo.html.getAttribute(a,this.dsPrefix)}return this.dragSources[b]}},onKeyDown:function(){},onMouseDown:function(a){if(!this.disabled){if(dojo.render.html.ie){if(a.button!=1)return}else if(a.which!=1)return;if(!dojo.html.isTag(a.target.nodeType==
dojo.html.TEXT_NODE?a.target.parentNode:a.target,"button","textarea","input","select","option")){var b=this.getDragSource(a);if(b){if(!dojo.lang.inArray(this.selectedSources,b)){this.selectedSources.push(b);b.onSelected()}this.mouseDownX=a.pageX;this.mouseDownY=a.pageY;a.preventDefault();dojo.event.connect(document,"onmousemove",this,"onMouseMove")}}}},onMouseUp:function(a){if(this.selectedSources.length!=0){this.mouseDownY=this.mouseDownX=null;this._dragTriggered=false;a.dragSource=this.dragSource;
if(!a.shiftKey&&!a.ctrlKey){this.currentDropTarget&&this.currentDropTarget.onDropStart();dojo.lang.forEach(this.dragObjects,function(b){var c=null;if(b){if(this.currentDropTarget){a.dragObject=b;var d=this.currentDropTarget.domNode.childNodes;if(d.length>0)for(a.dropTarget=d[0];a.dropTarget==b.domNode;)a.dropTarget=a.dropTarget.nextSibling;else a.dropTarget=this.currentDropTarget.domNode;if(this.dropAcceptable)c=this.currentDropTarget.onDrop(a);else this.currentDropTarget.onDragOut(a)}a.dragStatus=
this.dropAcceptable&&c?"dropSuccess":"dropFailure";dojo.lang.delayThese([function(){try{b.dragSource.onDragEnd(a)}catch(f){var e={};for(var g in a)if(g=="type")e.type="mouseup";else e[g]=a[g];b.dragSource.onDragEnd(e)}},function(){b.onDragEnd(a)}])}},this);this.selectedSources=[];this.dragObjects=[];this.dragSource=null;this.currentDropTarget&&this.currentDropTarget.onDropEnd()}dojo.event.disconnect(document,"onmousemove",this,"onMouseMove");this.currentDropTarget=null}},onScroll:function(){for(var a=
0;a<this.dragObjects.length;a++)this.dragObjects[a].updateDragOffset&&this.dragObjects[a].updateDragOffset();this.dragObjects.length&&this.cacheTargetLocations()},_dragStartDistance:function(a,b){if(this.mouseDownX&&this.mouseDownX){var c=Math.abs(a-this.mouseDownX),d=Math.abs(b-this.mouseDownY);return parseInt(Math.sqrt(c*c+d*d),10)}},cacheTargetLocations:function(){dojo.profile.start("cacheTargetLocations");this.dropTargetDimensions=[];dojo.lang.forEach(this.dropTargets,function(a){var b=a.domNode;
if(b&&a.accepts([this.dragSource])){var c=dojo.html.getAbsolutePosition(b,true);b=dojo.html.getBorderBox(b);this.dropTargetDimensions.push([[c.x,c.y],[c.x+b.width,c.y+b.height],a])}},this);dojo.profile.end("cacheTargetLocations")},onMouseMove:function(a){if(dojo.render.html.ie&&a.button!=1){this.currentDropTarget=null;this.onMouseUp(a,true)}else{if(this.selectedSources.length&&!this.dragObjects.length){var b,c;if(!this._dragTriggered){this._dragTriggered=this._dragStartDistance(a.pageX,a.pageY)>this.threshold;
if(!this._dragTriggered)return;b=a.pageX-this.mouseDownX;c=a.pageY-this.mouseDownY}this.dragSource=this.selectedSources[0];dojo.lang.forEach(this.selectedSources,function(f){if(f){var e=f.onDragStart(a);if(e){e.onDragStart(a);e.dragOffset.y+=c;e.dragOffset.x+=b;e.dragSource=f;this.dragObjects.push(e)}}},this);this.previousDropTarget=null;this.cacheTargetLocations()}dojo.lang.forEach(this.dragObjects,function(f){f&&f.onDragMove(a)});if(this.currentDropTarget){var d=dojo.html.toCoordinateObject(this.currentDropTarget.domNode,
true);d=[[d.x,d.y],[d.x+d.width,d.y+d.height]]}if(!this.nestedTargets&&d&&this.isInsideBox(a,d))this.dropAcceptable&&this.currentDropTarget.onDragMove(a,this.dragObjects);else{d=this.findBestTarget(a);if(d.target===null){if(this.currentDropTarget){this.currentDropTarget.onDragOut(a);this.previousDropTarget=this.currentDropTarget;this.currentDropTarget=null}this.dropAcceptable=false}else if(this.currentDropTarget!==d.target){if(this.currentDropTarget){this.previousDropTarget=this.currentDropTarget;
this.currentDropTarget.onDragOut(a)}this.currentDropTarget=d.target;a.dragObjects=this.dragObjects;this.dropAcceptable=this.currentDropTarget.onDragOver(a)}else this.dropAcceptable&&this.currentDropTarget.onDragMove(a,this.dragObjects)}}},findBestTarget:function(a){var b=this,c={};c.target=null;c.points=null;dojo.lang.every(this.dropTargetDimensions,function(d){if(!b.isInsideBox(a,d))return true;c.target=d[2];c.points=d;return Boolean(b.nestedTargets)});return c},isInsideBox:function(a,b){if(a.pageX>
b[0][0]&&a.pageX<b[1][0]&&a.pageY>b[0][1]&&a.pageY<b[1][1])return true;return false},onMouseOver:function(){},onMouseOut:function(){}});dojo.dnd.dragManager=new dojo.dnd.HtmlDragManager;
(function(){var a=document,b=dojo.dnd.dragManager;dojo.event.connect(a,"onkeydown",b,"onKeyDown");dojo.event.connect(a,"onmouseover",b,"onMouseOver");dojo.event.connect(a,"onmouseout",b,"onMouseOut");dojo.event.connect(a,"onmousedown",b,"onMouseDown");dojo.event.connect(a,"onmouseup",b,"onMouseUp");dojo.event.connect(window,"onscroll",b,"onScroll")})();
