dojo.provide("dojo.dnd.HtmlDragAndDrop");dojo.require("dojo.dnd.HtmlDragManager");dojo.require("dojo.dnd.DragAndDrop");dojo.require("dojo.html.*");dojo.require("dojo.html.display");dojo.require("dojo.html.util");dojo.require("dojo.html.selection");dojo.require("dojo.html.iframe");dojo.require("dojo.lang.extras");dojo.require("dojo.lfx.*");dojo.require("dojo.event.*");
dojo.declare("dojo.dnd.HtmlDragSource",dojo.dnd.DragSource,{dragClass:"",onDragStart:function(){var a=new dojo.dnd.HtmlDragObject(this.dragObject,this.type);if(this.dragClass)a.dragClass=this.dragClass;if(this.constrainToContainer)a.constrainTo(this.constrainingContainer||this.domNode.parentNode);return a},setDragHandle:function(a){a=dojo.byId(a);dojo.dnd.dragManager.unregisterDragSource(this);this.domNode=a;dojo.dnd.dragManager.registerDragSource(this)},setDragTarget:function(a){this.dragObject=
a},constrainTo:function(a){this.constrainToContainer=true;if(a)this.constrainingContainer=a},onSelected:function(){for(var a=0;a<this.dragObjects.length;a++)dojo.dnd.dragManager.selectedSources.push(new dojo.dnd.HtmlDragSource(this.dragObjects[a]))},addDragObjects:function(){for(var a=0;a<arguments.length;a++)this.dragObjects.push(dojo.byId(arguments[a]))}},function(a,b){a=dojo.byId(a);this.dragObjects=[];this.constrainToContainer=false;if(a){this.dragObject=this.domNode=a;this.type=b||this.domNode.nodeName.toLowerCase();
dojo.dnd.DragSource.prototype.reregister.call(this)}});
dojo.declare("dojo.dnd.HtmlDragObject",dojo.dnd.DragObject,{dragClass:"",opacity:0.5,createIframe:true,disableX:false,disableY:false,createDragNode:function(){var a=this.domNode.cloneNode(true);this.dragClass&&dojo.html.addClass(a,this.dragClass);this.opacity<1&&dojo.html.setOpacity(a,this.opacity);var b=a.tagName.toLowerCase(),c=b=="tr";if(c||b=="tbody"){var d=this.domNode.ownerDocument;b=d.createElement("table");if(c){d=d.createElement("tbody");b.appendChild(d);d.appendChild(a)}else b.appendChild(a);
d=(c?this.domNode:this.domNode.firstChild).childNodes;a=(c?a:a.firstChild).childNodes;for(c=0;c<d.length;c++)if(a[c]&&a[c].style)a[c].style.width=dojo.html.getContentBox(d[c]).width+"px";a=b}if((dojo.render.html.ie55||dojo.render.html.ie60)&&this.createIframe){with(a.style)left=top="0px";b=document.createElement("div");b.appendChild(a);this.bgIframe=new dojo.html.BackgroundIframe(b);b.appendChild(this.bgIframe.iframe);a=b}a.style.zIndex=999;return a},onDragStart:function(a){dojo.html.clearSelection();
this.scrollOffset=dojo.html.getScroll().offset;this.dragStartPosition=dojo.html.getAbsolutePosition(this.domNode,true);this.dragOffset={y:this.dragStartPosition.y-a.pageY,x:this.dragStartPosition.x-a.pageX};this.dragClone=this.createDragNode();this.containingBlockPosition=this.domNode.offsetParent?dojo.html.getAbsolutePosition(this.domNode.offsetParent,true):{x:0,y:0};if(this.constrainToContainer)this.constraints=this.getConstraints();with(this.dragClone.style){position="absolute";top=this.dragOffset.y+
a.pageY+"px";left=this.dragOffset.x+a.pageX+"px"}dojo.body().appendChild(this.dragClone);dojo.event.topic.publish("dragStart",{source:this})},getConstraints:function(){if(this.constrainingContainer.nodeName.toLowerCase()=="body"){var a=dojo.html.getViewport(),b=a.width;a=a.height;var c=dojo.html.getScroll().offset,d=c.x;c=c.y}else{a=dojo.html.getContentBox(this.constrainingContainer);b=a.width;a=a.height;d=this.containingBlockPosition.x+dojo.html.getPixelValue(this.constrainingContainer,"padding-left",
true)+dojo.html.getBorderExtent(this.constrainingContainer,"left");c=this.containingBlockPosition.y+dojo.html.getPixelValue(this.constrainingContainer,"padding-top",true)+dojo.html.getBorderExtent(this.constrainingContainer,"top")}var e=dojo.html.getMarginBox(this.domNode);return{minX:d,minY:c,maxX:d+b-e.width,maxY:c+a-e.height}},updateDragOffset:function(){var a=dojo.html.getScroll().offset;if(a.y!=this.scrollOffset.y){var b=a.y-this.scrollOffset.y;this.dragOffset.y+=b;this.scrollOffset.y=a.y}if(a.x!=
this.scrollOffset.x){b=a.x-this.scrollOffset.x;this.dragOffset.x+=b;this.scrollOffset.x=a.x}},onDragMove:function(a){this.updateDragOffset();var b=this.dragOffset.x+a.pageX;a=this.dragOffset.y+a.pageY;if(this.constrainToContainer){if(b<this.constraints.minX)b=this.constraints.minX;if(a<this.constraints.minY)a=this.constraints.minY;if(b>this.constraints.maxX)b=this.constraints.maxX;if(a>this.constraints.maxY)a=this.constraints.maxY}this.setAbsolutePosition(b,a);dojo.event.topic.publish("dragMove",
{source:this})},setAbsolutePosition:function(a,b){if(!this.disableY)this.dragClone.style.top=b+"px";if(!this.disableX)this.dragClone.style.left=a+"px"},onDragEnd:function(a){switch(a.dragStatus){case "dropSuccess":dojo.html.removeNode(this.dragClone);this.dragClone=null;break;case "dropFailure":dojo.html.getAbsolutePosition(this.dragClone,true);a=dojo.lfx.slideTo(this.dragClone,{left:this.dragStartPosition.x+1,top:this.dragStartPosition.y+1},300);var b=this;dojo.event.connect(a,"onEnd",function(){dojo.html.removeNode(b.dragClone);
b.dragClone=null});a.play();break}dojo.event.topic.publish("dragEnd",{source:this})},constrainTo:function(a){this.constrainToContainer=true;this.constrainingContainer=a?a:this.domNode.parentNode}},function(a,b){this.domNode=dojo.byId(a);this.type=b;this.constrainToContainer=false;this.dragSource=null;dojo.dnd.DragObject.prototype.register.call(this)});
dojo.declare("dojo.dnd.HtmlDropTarget",dojo.dnd.DropTarget,{vertical:false,onDragOver:function(a){if(!this.accepts(a.dragObjects))return false;this.childBoxes=[];a=0;for(var b;a<this.domNode.childNodes.length;a++){b=this.domNode.childNodes[a];if(b.nodeType==dojo.html.ELEMENT_NODE){var c=dojo.html.getAbsolutePosition(b,true),d=dojo.html.getBorderBox(b);this.childBoxes.push({top:c.y,bottom:c.y+d.height,left:c.x,right:c.x+d.width,height:d.height,width:d.width,node:b})}}return true},_getNodeUnderMouse:function(a){for(var b=
0;b<this.childBoxes.length;b++)with(this.childBoxes[b])if(a.pageX>=left&&a.pageX<=right&&a.pageY>=top&&a.pageY<=bottom)return b;return-1},createDropIndicator:function(){this.dropIndicator=document.createElement("div");with(this.dropIndicator.style){position="absolute";zIndex=999;if(this.vertical){borderLeftWidth="1px";borderLeftColor="black";borderLeftStyle="solid";height=dojo.html.getBorderBox(this.domNode).height+"px";top=dojo.html.getAbsolutePosition(this.domNode,true).y+"px"}else{borderTopWidth=
"1px";borderTopColor="black";borderTopStyle="solid";width=dojo.html.getBorderBox(this.domNode).width+"px";left=dojo.html.getAbsolutePosition(this.domNode,true).x+"px"}}},onDragMove:function(a,b){var c=this._getNodeUnderMouse(a);this.dropIndicator||this.createDropIndicator();var d=this.vertical?dojo.html.gravity.WEST:dojo.html.gravity.NORTH,e=false;if(c<0)if(this.childBoxes.length){if(d=dojo.html.gravity(this.childBoxes[0].node,a)&d)e=true}else d=true;else{var f=this.childBoxes[c];d=dojo.html.gravity(f.node,
a)&d;if(f.node===b[0].dragSource.domNode)e=true;else if((d?c>0?this.childBoxes[c-1]:f:c<this.childBoxes.length-1?this.childBoxes[c+1]:f).node===b[0].dragSource.domNode)e=true}if(e)this.dropIndicator.style.display="none";else{this.dropIndicator.style.display="";this.placeIndicator(a,b,c,d);dojo.html.hasParent(this.dropIndicator)||dojo.body().appendChild(this.dropIndicator)}},placeIndicator:function(a,b,c,d){a=this.vertical?"left":"top";var e;if(c<0)if(this.childBoxes.length)e=d?this.childBoxes[0]:
this.childBoxes[this.childBoxes.length-1];else this.dropIndicator.style[a]=dojo.html.getAbsolutePosition(this.domNode,true)[this.vertical?"x":"y"]+"px";else e=this.childBoxes[c];if(e){this.dropIndicator.style[a]=(d?e[a]:e[this.vertical?"right":"bottom"])+"px";if(this.vertical){this.dropIndicator.style.height=e.height+"px";this.dropIndicator.style.top=e.top+"px"}else{this.dropIndicator.style.width=e.width+"px";this.dropIndicator.style.left=e.left+"px"}}},onDragOut:function(){if(this.dropIndicator){dojo.html.removeNode(this.dropIndicator);
delete this.dropIndicator}},onDrop:function(a){this.onDragOut(a);var b=this._getNodeUnderMouse(a),c=this.vertical?dojo.html.gravity.WEST:dojo.html.gravity.NORTH;if(b<0){if(this.childBoxes.length)return dojo.html.gravity(this.childBoxes[0].node,a)&c?this.insert(a,this.childBoxes[0].node,"before"):this.insert(a,this.childBoxes[this.childBoxes.length-1].node,"after");return this.insert(a,this.domNode,"append")}b=this.childBoxes[b];return dojo.html.gravity(b.node,a)&c?this.insert(a,b.node,"before"):this.insert(a,
b.node,"after")},insert:function(a,b,c){a=a.dragObject.domNode;if(c=="before")return dojo.html.insertBefore(a,b);else if(c=="after")return dojo.html.insertAfter(a,b);else if(c=="append"){b.appendChild(a);return true}return false}},function(a,b){if(arguments.length!=0){this.domNode=dojo.byId(a);dojo.dnd.DropTarget.call(this);if(b&&dojo.lang.isString(b))b=[b];this.acceptedTypes=b||[];dojo.dnd.dragManager.registerDropTarget(this)}});
