var sUserAgent=navigator.userAgent,fAppVersion=parseFloat(navigator.appVersion);function compareVersions(a,c){var b=a.split("."),d=c.split(".");if(b.length>d.length)for(var e=0;e<b.length-d.length;e++)d.push("0");else if(b.length<d.length)for(e=0;e<d.length-b.length;e++)b.push("0");for(e=0;e<b.length;e++)if(b[e]<d[e])return-1;else if(b[e]>d[e])return 1;return 0}var isOpera=sUserAgent.indexOf("Opera")>-1,isMinOpera4=isMinOpera5=isMinOpera6=isMinOpera7=isMinOpera7_5=false;
if(isOpera){var fOperaVersion;if(navigator.appName=="Opera")fOperaVersion=fAppVersion;else{var reOperaVersion=/Opera (\d+\.\d+)/;reOperaVersion.test(sUserAgent);fOperaVersion=parseFloat(RegExp.$1)}isMinOpera4=fOperaVersion>=4;isMinOpera5=fOperaVersion>=5;isMinOpera6=fOperaVersion>=6;isMinOpera7=fOperaVersion>=7;isMinOpera7_5=fOperaVersion>=7.5}
var isKHTML=sUserAgent.indexOf("KHTML")>-1||sUserAgent.indexOf("Konqueror")>-1||sUserAgent.indexOf("AppleWebKit")>-1,isMinSafari1=isMinSafari1_2=false,isMinKonq2_2=isMinKonq3=isMinKonq3_1=isMinKonq3_2=false,isSafari=false;
if(isKHTML){isSafari=sUserAgent.indexOf("AppleWebKit")>-1;isKonq=sUserAgent.indexOf("Konqueror")>-1;if(isSafari){var reAppleWebKit=/AppleWebKit\/(\d+(?:\.\d*)?)/;reAppleWebKit.test(sUserAgent);var fAppleWebKitVersion=parseFloat(RegExp.$1);isMinSafari1=fAppleWebKitVersion>=85;isMinSafari1_2=fAppleWebKitVersion>=124;isMinSafari3=fAppleWebKitVersion>=510}else if(isKonq){var reKonq=/Konqueror\/(\d+(?:\.\d+(?:\.\d)?)?)/;reKonq.test(sUserAgent);isMinKonq2_2=compareVersions(RegExp.$1,"2.2")>=0;isMinKonq3=
compareVersions(RegExp.$1,"3.0")>=0;isMinKonq3_1=compareVersions(RegExp.$1,"3.1")>=0;isMinKonq3_2=compareVersions(RegExp.$1,"3.2")>=0}}var isIE=sUserAgent.indexOf("compatible")>-1&&sUserAgent.indexOf("MSIE")>-1&&!isOpera,isMinIE4=isMinIE5=isMinIE5_5=isMinIE6=false;if(isIE){var reIE=/MSIE (\d+\.\d+);/;reIE.test(sUserAgent);var fIEVersion=parseFloat(RegExp.$1);isMinIE4=fIEVersion>=4;isMinIE5=fIEVersion>=5;isMinIE5_5=fIEVersion>=5.5;isMinIE6=fIEVersion>=6}
var isMoz=sUserAgent.indexOf("Gecko")>-1&&!isKHTML,isMinMoz1=sMinMoz1_4=isMinMoz1_5=false;if(isMoz){var reMoz=/rv:(\d+\.\d+(?:\.\d+)?)/;reMoz.test(sUserAgent);isMinMoz1=compareVersions(RegExp.$1,"1.0")>=0;isMinMoz1_4=compareVersions(RegExp.$1,"1.4")>=0;isMinMoz1_5=compareVersions(RegExp.$1,"1.5")>=0}var isNS4=!isIE&&!isOpera&&!isMoz&&!isKHTML&&sUserAgent.indexOf("Mozilla")==0&&navigator.appName=="Netscape"&&fAppVersion>=4&&fAppVersion<5,isMinNS4=isMinNS4_5=isMinNS4_7=isMinNS4_8=false;
if(isNS4){isMinNS4=true;isMinNS4_5=fAppVersion>=4.5;isMinNS4_7=fAppVersion>=4.7;isMinNS4_8=fAppVersion>=4.8}var isWin=navigator.platform=="Win32"||navigator.platform=="Windows",isMac=navigator.platform=="Mac68K"||navigator.platform=="MacPPC"||navigator.platform=="Macintosh",isUnix=navigator.platform=="X11"&&!isWin&&!isMac,isWin95=isWin98=isWinNT4=isWin2K=isWinME=isWinXP=false,isMac68K=isMacPPC=false,isSunOS=isMinSunOS4=isMinSunOS5=isMinSunOS5_5=false;
if(isWin){isWin95=sUserAgent.indexOf("Win95")>-1||sUserAgent.indexOf("Windows 95")>-1;isWin98=sUserAgent.indexOf("Win98")>-1||sUserAgent.indexOf("Windows 98")>-1;isWinME=sUserAgent.indexOf("Win 9x 4.90")>-1||sUserAgent.indexOf("Windows ME")>-1;isWin2K=sUserAgent.indexOf("Windows NT 5.0")>-1||sUserAgent.indexOf("Windows 2000")>-1;isWinXP=sUserAgent.indexOf("Windows NT 5.1")>-1||sUserAgent.indexOf("Windows XP")>-1;isWinNT4=sUserAgent.indexOf("WinNT")>-1||sUserAgent.indexOf("Windows NT")>-1||sUserAgent.indexOf("WinNT4.0")>
-1||sUserAgent.indexOf("Windows NT 4.0")>-1&&!isWinME&&!isWin2K&&!isWinXP}if(isMac){isMac68K=sUserAgent.indexOf("Mac_68000")>-1||sUserAgent.indexOf("68K")>-1;isMacPPC=sUserAgent.indexOf("Mac_PowerPC")>-1||sUserAgent.indexOf("PPC")>-1}if(isUnix)if(isSunOS=sUserAgent.indexOf("SunOS")>-1){var reSunOS=/SunOS (\d+\.\d+(?:\.\d+)?)/;reSunOS.test(sUserAgent);isMinSunOS4=compareVersions(RegExp.$1,"4.0")>=0;isMinSunOS5=compareVersions(RegExp.$1,"5.0")>=0;isMinSunOS5_5=compareVersions(RegExp.$1,"5.5")>=0}
function analysis(a,c){try{if(c==undefined){var b="";for(var d in a)b+=d+"\t\t:"+a[d]+"\n"}else{b='<table  cellspacing="0">';for(d in a){b+="<tr>";b+="<td>"+d+"</td><td>";b+=a[d];b+="</td>";b+="</tr>"}b+="</table>"}return b}catch(e){}}function trace(a,c){result=analysis(a,c);c==undefined?alert(result):window.open("","traceWin").document.write(result)}function openLinkInNewWindow(a){if(a)if(a=a.getAttribute("href")){window.open(a);return false}return true}
function toggleLayer(a){try{var c=document.getElementById(a);c.style.display=c.style.display=="none"?"block":"none"}catch(b){}return true}function showLayer(a){document.getElementById(a).style.display="block";return true}function hideLayer(a){document.getElementById(a).style.display="none";return true}function findFormObject(a){for(a=a;a;a=a.parentNode)if(a.nodeName=="FORM")return a;return null}
function trim(a){for(var c=0,b=a.length,d=0;d<a.length;d++)if(a.charAt(d)!=" "){c=d;break}for(d=a.length-1;d>=0;d--)if(a.charAt(d)!=" "){b=d+1;break}return a.substring(c,b)}function checkValue(a,c){try{if(a.value.length==0){alert(c);a.focus();return false}return true}catch(b){return false}}function trimAll(a){try{for(var c=0;c<a.elements.length;c++)a.elements[c].tagName.toLowerCase();return true}catch(b){alert(b.message)}}
function openKeyword(a){window.open(a,"keyword","width=570,height=650,location=0,menubar=0,resizable=1,scrollbars=1,status=0,toolbar=0")}var oProgress=null;function beginProgress(){endProgress();oProgress=document.createElement("span");oProgress.style.position="absolute";oProgress.style.left="0px";oProgress.style.top="0px";oProgress.style.backgroundColor="#FFFF99";oProgress.innerText="???..";document.body.appendChild(oProgress)}
function endProgress(){if(oProgress){document.body.removeChild(oProgress);oProgress=null}}
if(isMoz){XMLDocument.prototype.selectNodes=function(a){a=(new XPathEvaluator).evaluate(a,this,null,XPathResult.ORDERER_NODE_ITERATOR_TYPE,null);for(var c=[],b=a.iterateNext();b;){c[b.nodeName]=b.firstChild.nodeValue;b=a.iterateNext()}return c};XMLDocument.prototype.selectSingleNode=function(a){return(new XPathEvaluator).evaluate(a,this,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue};Node.prototype.__defineGetter__("xml",function(){return(new XMLSerializer).serializeToString(this,
"text/xml")})}function createHttp(){try{return new XMLHttpRequest}catch(a){for(var c=["MSXML2.XMLHTTP.5.0","MSXML2.XMLHTTP.4.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<c.length;b++)try{return new ActiveXObject(c[b])}catch(d){}return null}}var loading=false;
function getResponse(a,c){try{loading=true;var b=createHttp();aux=a.indexOf("?")==-1?"?":"&";b.open("POST",a+aux+"time="+(new Date).getTime(),false);if(c==undefined)c="";else b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");b.send(c);result=[];if(isSafari||isOpera){resultNodes=b.responseXML.firstChild.childNodes;for(var d=0;d<resultNodes.length;d++)if(resultNodes.item(d).firstChild!=null)result[resultNodes.item(d).nodeName]=resultNodes.item(d).firstChild.nodeValue;loading=false;
delete b;return result}else if(isIE){resultNodes=b.responseXML.documentElement.childNodes;result=[];for(d=0;d<resultNodes.length;d++)result[resultNodes[d].nodeName]=resultNodes[d].text;loading=false;delete b;return result}else{loading=false;var e=b.responseXML.selectNodes("/response/descendant::*");delete b;return e}}catch(f){alert("exception");loading=false;document.getElementsByName("body");b=document.createElement("div");document.body.appendChild(b);b.innerHTML='<iframe src="'+a+'"style="display:none" onload="location.href=location.href"></iframe>';
return false}}function requestHttp(a){try{var c=createHttp();c.open("GET",a+"&time="+(new Date).getTime(),false);c.send("");var b=isSafari||isOpera?c.responseXML.firstChild.firstChild.nextSibling.firstChild.nodeValue:c.responseXML.selectSingleNode("/response/error").text;delete c;return b}catch(d){window.status=d.messge}}function requestHttpText(a){var c=createHttp();c.open("GET",a+"&time="+(new Date).getTime(),false);c.send("");a=c.responseText;delete c;return a}
function requestHttpXml(a){var c=createHttp();c.open("GET",a+"&time="+(new Date).getTime(),false);c.send("");a=c.responseXML;delete c;return a}function requestPost(a,c){var b=createHttp();b.open("POST",a+"&time="+(new Date).getTime(),false);b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");b.send(c+"&time="+(new Date).getTime());var d=b.responseXML.selectSingleNode("/response/error").text;delete b;return d}
function requestPostText(a,c){var b=createHttp();b.open("POST",a+"&time="+(new Date).getTime(),false);b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");b.send(c);var d=b.responseText;delete b;return d}function setRequestBody(a,c,b){var d="";d+="--"+b+"\r\n";d+='Content-Disposition: form-data; name="'+a+'"\r\n\r\n';d+=c+"\r\n";return d}function isNull(a,c){if(a.value.length==0){alert(c+"\t");a.focus();return true}return false}
function open_img(a){img_view=window.open("","TatterImagePopup","width=0, height=0, left=0, top=0, scrollbars=yes, resizable=yes");img_view.document.write('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">\n\t<head>\n\t\t<title> :: View :: </title>\n\t\t<meta http-equiv="content-type" content="text/html; charset=utf-8" />\n\t\t<script type="text/javascript">\n\t\t//<![CDATA\n\t\t\tfunction getWindowCleintHeight() {\n\t\t\t\treturn (window.innerHeight != null) ? window.innerHeight : document.documentElement.clientHeight;\n\t\t\t}\n\t\t\tfunction getWindowCleintWidth() {\n\t\t\t\treturn (window.innerWidth != null) ? window.innerWidth : document.documentElement.clientWidth;\n\t\t\t}\n\t\t\tfunction resize(img) {\n\t\t\t\tvar imageWidth = img.width+5;\n\t\t\t\tvar imageHeight = img.height+5;\n\t\t\t\tvar screenWidth = screen.availWidth;\n\t\t\t\tvar screenHeight = screen.availHeight;\n\t\t\t\tvar windowWidth = imageWidth;\n\t\t\t\tvar windowHeight = imageHeight;\n\t\t\t\tvar positionX = (screenWidth - imageWidth) / 2;\n\t\t\t\tvar positionY = (screenHeight - imageHeight) / 2;\n\t\t\t\tif(imageWidth > screenWidth * 0.8) {\n\t\t\t\t\twindowWidth = screenWidth * 0.8;\n\t\t\t\t\tdocument.body.scroll ="yes";\n\t\t\t\t\tpositionX = 0;\n\t\t\t\t}\n\t\t\t\tif(imageHeight > screenHeight * 0.8 ) {\n\t\t\t\t\twindowHeight = screenHeight * 0.8;\n\t\t\t\t\tdocument.body.scroll ="yes";\n\t\t\t\t\tpositionY = 0;\n\t\t\t\t}\n               iWidth = windowWidth - getWindowCleintWidth();\n               iHeight = windowHeight - getWindowCleintHeight();\n               window.resizeBy(iWidth, iHeight);\n\t\t\t\twindow.moveTo(positionX, positionY);\n\t\t\t}\n\t\t//]]\>\n\t\t<\/script>\n\t</head>\n\t<body style="margin: 0px; padding: 0;">\n\t\t<a href="javascript:window.close()"><img src="'+
a+'" style="border: 0px; padding: 0; margin:0;" onload="resize(this)" /></a>\n\t</body>\n</html>');try{img_view.document.close()}catch(c){}try{img_view.document.focus()}catch(b){}}function openFullScreen(a,c){img_view=window.open(a,"img_popup","width="+screen.width+",height="+screen.height+",left=0,top=0,scrollbars=no,resizable=yes");img_view.status=c;try{img_view.document.focus()}catch(b){}}
function scroller(a,c){try{a=document.getElementById(a);var b=document.body.scrollTop;status=a.scrollTop+"  "+document.body.scrollTop+"  "+c+" = "+(a.offsetTop-document.body.scrollTop)/c;b+=(a.offsetTop-document.body.scrollTop)/c;document.body.scrollTop==b&&clearInterval(scrollerId);window.scroll(0,b)}catch(d){clearInterval(scrollerId);alert(d.message)}}function eleganceScroll(a,c){if(c==undefined)c=8;scrollerId=window.setInterval("scroller('"+a+"',"+c+")",1E3/30)}
function showJukeboxList(a,c){target=document.getElementById("jukeBoxContainer"+a);divTarget=document.getElementById("jukeBox"+a+"Div");flashTarget=document.getElementById("jukeBox"+a+"Flash");target.style.height=flashTarget.style.height=divTarget.style.height=c+"px"}function setUserSetting(a,c){(new HTTPRequest("POST",blogURL+"/owner/setting/userSetting/set/")).send("name="+encodeURIComponent(a)+"&value="+encodeURIComponent(c))}
function getWindowCleintHeight(){return window.innerHeight!=null?window.innerHeight:document.documentElement.clientHeight}function getWindowCleintWidth(){return window.innerWidth!=null?window.innerWidth:document.documentElement.clientWidth}function getOffsetTop(a){return a?a.offsetTop+getOffsetTop(a.offsetParent):0}function getOffsetLeft(a){return a?a.offsetLeft+getOffsetLeft(a.offsetParent):0}
function updateFeed(){var a=createHttp();if(a){a.open("GET",blogURL+"/feeder?"+(new Date).getTime(),true);a.send("")}}function searchChildNodes(a,c){var b=[];if(a.hasChildNodes())for(var d=0;d<a.childNodes.length;d++){var e=a.childNodes[d];if(e.nodeType==1){if(e.tagName.toUpperCase()==c.toUpperCase())b[b.length]=e;e=searchChildNodes(e,c);for(var f=0;f<e.length;f++)b[b.length]=e[f]}}return b}
function getEmbedCode(a,c,b,d,e,f,g,h,j,k,l,m){try{if(a==undefined||c==undefined||b==undefined)return false;if(f==undefined)var n="",o="";else{n='<param name="FlashVars" value="'+f+'" />';o=' FlashVars="'+f+'" '}if(g==undefined)var p="",q="";else{p='<param name="menu" value="'+g+'" />';q=' menu="'+g+'" '}if(h==undefined)var r="",t="";else{r='<param name="wmode" value="'+h+'" />';t=' wmode="'+h+'" '}if(j==undefined)var u="",v="";else{u='<param name="quality" value="'+j+'" />';v=' quality="'+j+'" '}if(k==
undefined)var w="",x="";else{w='<param name="bgcolor" value="'+k+'" />';x=' bgcolor="'+k+'" '}if(l==undefined)var y="",z="";else{y='<param name="allowScriptAccess" value="'+l+'" />';z=' allowScriptAccess="'+l+'" '}d=d==undefined?"":'id="'+d+'"';if(m==undefined)m="7,0,0,0";return STD.isIE?'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version='+m+'" width="'+c+'" height="'+b+'" '+d+' align="middle"><param name="movie" value="'+
a+'" />'+y+n+p+u+w+r+"</object>":"<embed "+d+' type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" src="'+a+'" width="'+c+'" height="'+b+'"'+z+o+q+v+x+t+"/>"}catch(A){return false}}function writeCode(a,c){a=a.replace('src="','src="http://'+document.domain+(document.location.port?":"+document.location.port:""));if(c==undefined)document.write(a);else document.getElementById(c).innerHTML=a}
function writeCode2(a,c){if(c==undefined)document.write(a);else document.getElementById(c).innerHTML=a}var StringBuffer=function(){this.buffer=[]};StringBuffer.prototype.append=function(a){this.buffer[this.buffer.length]=a};StringBuffer.prototype.toString=function(){return this.buffer.join("")};if(!Array.prototype.push)Array.prototype.push=function(){for(var a=this.length,c=0;c<arguments.length;c++)this[a+c]=arguments[c];return this.length};
if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(new RegExp("(^\\s*)|(\\s*$)","g"),"")};if(!String.prototype.replaceAll)String.prototype.replaceAll=function(a,c){a=a.replace(new RegExp("(\\W)","g"),"\\$1");c=c.replace(new RegExp("\\$","g"),"$$$$");return this.replace(new RegExp(a,"gm"),c)};
if(!String.prototype.count)String.prototype.count=function(a){return(a=typeof a=="string"?this.match(new RegExp(a.replace(new RegExp("(\\W)","g"),"\\$1"),"g")):this.match(a))?a.length:0};if(!String.prototype.indexOfCaseInsensitive)String.prototype.indexOfCaseInsensitive=function(a,c){var b=typeof c=="undefined"?this:this.substring(c,this.length);return(b=typeof a=="string"?(new RegExp(a.replace(new RegExp("(\\W)","g"),"\\$1"),"i")).exec(b):a.exec(b))?b.index+(typeof c=="number"?c:0):-1};
function getTagChunks(a,c,b){for(var d=[],e=pos2=0;(e=a.indexOfCaseInsensitive(new RegExp("<"+c+"\\s","i"),pos2))>-1;){var f="";do{if((pos2=a.indexOfCaseInsensitive(new RegExp("</"+c,"i"),Math.max(e,pos2)))==-1)return d;pos2+=c.length+3;f=a.substring(e,pos2)}while(f!=""&&f.count(new RegExp("<"+c+"\\s","gi"))!=f.count(new RegExp("</"+c,"gi")));if(typeof b=="function")f=b(f);d[d.length]=f}return d}
function toggleMoreLess(a,c,b,d){oMore=document.getElementById("more"+c);oContent=document.getElementById("content"+c);if(b.Length==0)b="more...";if(d.Length==0)d="less...";if(oContent.style.display=="none"){oContent.style.display="block";oMore.className="moreless_top";a.innerHTML=d;oLess=document.createElement("P");oLess.id="less"+c;oLess.className="moreless_bottom";a=b.replace(/&/g,"&amp;");b=d.replace(/&/g,"&amp;");oLess.innerHTML='<span style="cursor: pointer;" onclick="toggleMoreLess(this, \''+
c+"', '"+a+"', '"+b+"'); return false;\">"+d+"</span>";after=oContent.nextSibling;oContent.parentNode.insertBefore(oLess,after)}else{oContent.style.display="none";oMore.className="moreless_fold";oMore.childNodes[0].innerHTML=b;oLess=document.getElementById("less"+c);oContent.parentNode.removeChild(oLess)}}function getParentByTagName(a,c){for(;c.tagName!=a.toUpperCase();)c=c.parentNode;return c}
function removeItselfById(a){document.getElementById(a).parentNode.removeChild(document.getElementById(a))}
function makeQueryStringByForm(a){queryString="";tempForm=document.getElementById(a);for(i=0;i<tempForm.elements.length;i++){linker=queryString!=""?"&":"";if(tempForm.elements[i].disabled!=true)if(tempForm.elements[i].tagName.toLowerCase()=="input")switch(tempForm.elements[i].type){case "checkbox":case "radio":if(tempForm.elements[i].checked==true)queryString+=linker+tempForm.elements[i].name+"="+tempForm.elements[i].value;break;case "text":case "password":queryString+=linker+tempForm.elements[i].name+
"="+tempForm.elements[i].value;break;case "file":if(tempForm.elements[i].value!="")queryString+=linker+tempForm.elements[i].name+"="+tempForm.elements[i].value}else if(tempForm.elements[i].tagName.toLowerCase()=="select"){num=tempForm.elements[i].selectedIndex;queryString+=linker+tempForm.elements[i].name+"="+tempForm.elements[i].options[num].value}else if(tempForm.elements[i].tagName.toLowerCase()=="textarea")queryString+=linker+tempForm.elements[i].name+"="+tempForm.elements[i].value}return queryString}
function showMessage(a){PM.showMessage(""+a,"right","bottom")}function preventEnter(a){if(!a)a=window.event;if(a.keyCode==13){a.returnValue=false;a.cancelBubble=true;try{a.preventDefault()}catch(c){}return false}return true}function looseURIEncode(a){a=a.replace(new RegExp("%","g"),"%25");a=a.replace(new RegExp("\\?","g"),"%3F");return a=a.replace(new RegExp("#","g"),"%23")}
function searchBlog(){var a=document.getElementById("TTSearchForm");if(a&&a.search&&a.search.value.trim()!="")window.location=blogURL+"/search/"+looseURIEncode(a.search.value);return false}
function processShortcut(a){a=STD.event(a);if(!(a.altKey||a.ctrlKey||a.metaKey)){switch(a.target.nodeName){case "INPUT":case "SELECT":case "TEXTAREA":return}switch(a.keyCode){case 81:window.location=blogURL+"/owner";break;case 82:if(isReaderEnabled)window.location=blogURL+"/owner/network/reader";break;case 84:if(isReaderEnabled)window.location=blogURL+"/owner/network/reader/?forceRefresh";break;case 65:case 72:case 80:if(prevURL)window.location=prevURL;break;case 83:case 76:case 78:if(nextURL)window.location=
nextURL;break;case 74:window.scrollBy(0,100);break;case 75:window.scrollBy(0,-100);break;case 90:window.location="#recentEntries";break;case 88:window.location="#recentComments";break;case 67:window.location="#recentTrackbacks";break}}}var commentSavingNow=false;
function addComment(a,c){if(commentSavingNow==true){alert(messages.onSaving);return false}var b=findFormObject(a);if(!b)return false;if(b.comment_type!=undefined&&b.comment_type[0].checked&&b.comment_type[0].value=="openid")return addCommentWithOpenIDAuth(b,c);var d=new HTTPRequest("POST",b.action);d.onSuccess=function(){commentSavingNow=false;document.getElementById("entry"+c+"Comment").innerHTML=this.getText("/response/commentBlock");if(getObject("recentComments")!=null)document.getElementById("recentComments").innerHTML=
this.getText("/response/recentCommentBlock");if(getObject("commentCount"+c)!=null)document.getElementById("commentCount"+c).innerHTML=this.getText("/response/commentView");if(getObject("commentCountOnRecentEntries"+c)!=null)document.getElementById("commentCountOnRecentEntries"+c).innerHTML="("+this.getText("/response/commentCount")+")";if(typeof addCommentCallback==="object"||typeof addCommentCallback==="array")for(var f=0;f<addCommentCallback.length;f++)typeof addCommentCallback[f]==="function"&&
addCommentCallback[f].call(this,a,c)};d.onError=function(){commentSavingNow=false;alert(this.getText("/response/description"))};var e="key="+commentKey;tempComment="comment_"+c;tempHomepage="homepage_"+c;tempName="name_"+c;tempPassword="password_"+c;tempSecret="secret_"+c;for(i=0;i<b.elements.length;i++){linker=e!=""?"&":"";if(b.elements[i].disabled!=true)if(b.elements[i].tagName.toLowerCase()=="input")switch(b.elements[i].type){case "checkbox":case "radio":if(b.elements[i].checked==true)if(b.elements[i].name==
tempSecret)e+=linker+b.elements[i].name+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].id==tempSecret)e+=linker+b.elements[i].id+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].name!="")e+=linker+b.elements[i].name+"_"+c+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].id!="")e+=linker+b.elements[i].id+"="+encodeURIComponent(b.elements[i].value);break;case "text":case "password":case "hidden":case "button":case "submit":if(b.elements[i].name==
tempName)e+=linker+b.elements[i].name+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].id==tempName)e+=linker+b.elements[i].id+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].name==tempPassword)e+=linker+b.elements[i].name+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].id==tempPassword)e+=linker+b.elements[i].id+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].name==tempHomepage)e+=linker+b.elements[i].name+"="+encodeURIComponent(b.elements[i].value);
else if(b.elements[i].id==tempHomepage)e+=linker+b.elements[i].id+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].name!="")e+=linker+b.elements[i].name+"_"+c+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].id!="")e+=linker+b.elements[i].id+"="+encodeURIComponent(b.elements[i].value);break}else if(b.elements[i].tagName.toLowerCase()=="select"){num=b.elements[i].selectedIndex;if(b.elements[i].name!="")e+=linker+b.elements[i].name+"_"+c+"="+encodeURIComponent(b.elements[i].options[num].value);
else if(b.elements[i].id!="")e+=linker+b.elements[i].id+"="+encodeURIComponent(b.elements[i].options[num].value)}else if(b.elements[i].tagName.toLowerCase()=="textarea")if(b.elements[i].name==tempComment)e+=linker+b.elements[i].name+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].name!="")e+=linker+b.elements[i].name+"_"+c+"="+encodeURIComponent(b.elements[i].value);else if(b.elements[i].id!="")e+=linker+b.elements[i].id+"="+encodeURIComponent(b.elements[i].value)}commentSavingNow=
true;d.send(e)}
function addCommentWithOpenIDAuth(a,c){if(!a)return false;form=document.createElement("form");var b=a.action.split("/");b.pop();b.pop();form.action=b.join("/");form.action+="/addopenid/"+c+"?__T__="+(new Date).getTime();form.method="post";b=document.createElement("input");b.type="hidden";b.name="key";b.value=commentKey;form.appendChild(b);b=document.createElement("input");b.type="hidden";b.name="requestURI";b.value=document.location.href;form.appendChild(b);tempComment="comment_"+c;tempHomepage="homepage_"+
c;tempSecret="secret_"+c;for(i=0;i<a.elements.length;i++)if(a.elements[i].disabled!=true){var d="",e="";if(a.elements[i].tagName.toLowerCase()=="input"){switch(a.elements[i].type){case "checkbox":case "radio":if(a.elements[i].checked==true)if(a.elements[i].name==tempSecret)d=a.elements[i].name;else if(a.elements[i].id==tempSecret)d=a.elements[i].id;else if(a.elements[i].name!="")d=a.elements[i].name+"_"+c;else if(a.elements[i].id!="")d=a.elements[i].id;break;case "text":case "password":case "hidden":case "button":case "submit":if(a.elements[i].name==
tempHomepage)d=a.elements[i].name;else if(a.elements[i].id==tempHomepage)d=a.elements[i].id;else if(a.elements[i].name!="")d=a.elements[i].name+"_"+c;else if(a.elements[i].id!="")d=a.elements[i].id;break}if(d)e=a.elements[i].value}else if(a.elements[i].tagName.toLowerCase()=="select"){num=a.elements[i].selectedIndex;if(a.elements[i].name!=""){d=a.elements[i].name+"_"+c;e=a.elements[i].options[num].value}else if(a.elements[i].id!=""){d=a.elements[i].id;e=a.elements[i].options[num].value}}else if(a.elements[i].tagName.toLowerCase()==
"textarea")if(a.elements[i].name==tempComment){d=a.elements[i].name;e=a.elements[i].value}else if(a.elements[i].name!=""){d=a.elements[i].name+"_"+c;e=a.elements[i].value}else if(a.elements[i].id!=""){d=a.elements[i].id;e=a.elements[i].value}if(d){b=document.createElement("input");b.type="hidden";b.name=d;b.value=e;form.appendChild(b)}}document.body.appendChild(form);form.submit()}
function recallLastComment(a){alert("Not yet supported.");a=findFormObject(a);if(!a)return false;a=a.action.split("/");a.pop();a.pop();a=a.join("/");a+="/recall?__T__="+(new Date).getTime();a=new HTTPRequest("POST",a);a.onSuccess=function(){};a.onError=function(){alert(this.getText("/response/description"))}}
function loadComment(a,c,b){var d=new HTTPRequest("POST",blogURL+"/comment/load/"+a),e=document.getElementById("entry"+a+"Comment");if(!b&&e.style.display=="none"||b){d.onSuccess=function(){PM.removeRequest(this);e.innerHTML=this.getText("/response/commentBlock");if(typeof loadCommentCallback==="object"||typeof loadCommentCallback==="array")for(var f=0;f<loadCommentCallback.length;f++)typeof loadCommentCallback[f]==="function"&&loadCommentCallback[f].call(this,a,c,b)};d.onError=function(){PM.removeRequest(this);
PM.showErrorMessage("Loading Failed.","center","bottom")};PM.addRequest(d,"Loading Comments...");d.send("&page="+c)}if(!b)e.style.display=e.style.display=="none"?"block":"none"}var openWindow="";
function openCenteredWindow(a,c,b,d,e){e=e?1:0;try{openWindow!=""&&openWindow.close()}catch(f){}openWindow=window.open(a,c,"width="+b+",height="+d+",top="+(screen.height/2-d/2)+",left="+(screen.width/2-b/2)+",location=0,menubar=0,resizable=1,scrollbars="+e+",status=0,toolbar=0");openWindow.focus();return openWindow}function deleteComment(a){openCenteredWindow(blogURL+"/comment/delete/"+a,"tatter",460,400)}
function modifyComment(a){openCenteredWindow(blogURL+"/comment/modify/"+a,"tatter",460,400)}function commentComment(a){openCenteredWindow(blogURL+"/comment/comment/"+a,"tatter",460,600)}
function getMoreLineStream(a,c,b){var d=new HTTPRequest("POST",blogURL+"/stream/");d.onSuccess=function(){contentView=this.getText("/response/contentView");buttonView=this.getText("/response/buttonView");if(a==1&&c==1)buttonView="";updateStream(contentView,buttonView,b)};d.onError=function(){};d.send("page="+a+"&lines="+c)}
function updateStream(a,c,b){Ocontent=document.getElementById("line-content");Pcontent=document.getElementById("line-more-page");if(b=="top")Ocontent.innerHTML=a+Ocontent.innerHTML;else Ocontent.innerHTML+=a;Pcontent.innerHTML=c;return true}function editEntry(a,c){openCenteredWindow(blogURL+"/owner/entry/edit/"+a+"?popupEditor&returnURL="+c,"tatter",1020,550,true)}function guestbookComment(a){openCenteredWindow(blogURL+"/comment/comment/"+a,"tatter",460,360)}
function sendTrackback(a){openCenteredWindow(blogURL+"/trackback/send/"+a,"tatter",580,400)}
function deleteTrackback(a,c){if(doesHaveOwnership){if(confirm(messages.confirmTrackbackDelete)){var b=new HTTPRequest("GET",blogURL+"/trackback/delete/"+a);b.onSuccess=function(){document.getElementById("entry"+c+"Trackback").innerHTML=this.getText("/response/trackbackList");document.getElementById("entry"+c+"Trackback").style.display="block";try{obj=document.getElementById("trackbackCount"+c);if(obj!=null)obj.innerHTML=this.getText("/response/trackbackCount")}catch(d){}try{obj=document.getElementById("recentTrackbacks");
if(obj!=null)obj.innerHTML=this.getText("/response/recentTrackbacks")}catch(e){}};b.onError=function(){alert(messages.operationFailed)};b.send()}}else alert(messages.operationFailed)}function changeVisibility(a,c){if(doesHaveOwnership){var b=new HTTPRequest("GET",blogURL+"/owner/entry/visibility/"+a+"?visibility="+c);b.onSuccess=function(){window.location.reload()};b.send()}}
function deleteEntry(a){if(doesHaveOwnership)if(confirm(messages.confirmEntryDelete)){a=new HTTPRequest("GET",blogURL+"/owner/entry/delete/"+a);var c=blogURL;if(blogURL==null||blogURL.length<=0)c="/";a.onSuccess=function(){window.location.href=c};a.send()}}
function reloadEntry(a){var c=document.getElementById("entry"+a+"password");if(!c){passwords=document.getElementsByName("entry"+a+"password");if(passwords!=null&&passwords.Count>0)c=passwords}if(c){document.cookie="GUEST_PASSWORD="+escape(c.value)+";path="+servicePath;window.location.href=window.location.href}}function thisMovie(a){return navigator.appName.indexOf("Microsoft")!=-1?window[a]:document[a]}
function copyUrl(a,c){try{window.clipboardData.setData("Text",a);window.alert(messages.trackbackUrlCopied)}catch(b){s=window.getSelection();var d=document.createRange();d.setStartBefore(c);d.setEndAfter(c);s.addRange(d)}}function onClipBoard(a){alert(a?messages.trackbackUrlCopied:messages.operationFailed)};
