function ctlUserSuggestFunction_WatchInputBox(a){try{var d=document.getElementById(a).instance;if(d.input.value!=d.typingText){d.typingText=d.input.value;d.requestSuggestion()}}catch(b){}}
function ctlUserSuggestFunction_showSuggestion(){try{var a=document.getElementById(arguments[0]).instance}catch(d){return}debug('<span style="color: red">Received '+a.cursor+"</span>");if(!(a.cursor!=arguments[1]||!a.isTyping)){a.suggestion.style.left=getOffsetLeft(a.input)+"px";a.suggestion.style.top=getOffsetTop(a.input)+a.input.offsetHeight+"px";var b=new StringBuffer;if(arguments[2]==0)for(var c=3;c<arguments.length;c++){arguments[c]=arguments[c].replaceAll("&quot;",'"');if(STD.isSafari)arguments[c]=
decodeURIComponent(arguments[c]);b.append('<li onmouseover="this.className=\'hover\'" onmouseout="this.className=\'\'" onmousedown="this.parentNode.instance.suggestionMouseClick(this)">');b.append(arguments[c].replace(new RegExp("("+a.input.value+")","gi"),"<em>$1</em>"));b.append("</li>")}else{a.hideSuggestion();return false}a.suggestion.innerHTML=b.toString();a.suggestion.style.display="block";a.isSuggestionShown=true;try{document.body.removeChild(a.suggestion)}catch(e){}document.body.appendChild(a.suggestion)}}
function ctlUserSuggest(a,d){this.name="Textcube Control Panel User Suggestion Object";this.copyright="Tatter Network Foundation";this.allowSuggestion=typeof d=="undefined"?false:!d;this.isSettingValue=this.isFocused=false;this.instance=this;this.cursor=0;this.inputClassName="";this.isSuggestionShown=this.isTyping=false;this.typingText="";this.container=a;this.container.instance=this;this.suggestion=document.createElement("ul");this.suggestion.instance=this;this.suggestion.selectedIndex=0;this.suggestion.className=
"ctlUserSuggest";this.suggestion.style.margin="0px";this.suggestion.style.padding="0px";this.suggestion.style.listStyleType="none";this.suggestion.style.position="absolute";this.suggestion.style.display="none";this.suggestion.style.zIndex="999";this.input=document.createElement("input");this.input.instance=this;this.input.setAttribute("autocomplete","off");this.input.onblur=function(){this.instance.isTyping=false;this.instance.typingText="";this.instance.setValue(this.value);this.instance.isFocused=
false};this.input.onfocus=function(){if(!this.instance.isFocused){this.instance.isFocused=true;this.instance.isTyping=true;this.instance.typingText=this.value;this.instance.requestSuggestion()}};this.input.onkeydown=function(b){var c=this.instance;c.isTyping=true;b=c.adjustEventCompatibility(b);switch(b.keyCode){case 13:c.setValue(this.value,false);break;case 9:c.setValue(this.value,false);return b.keyCode;case 27:c.hideSuggestion();break;case 38:c.moveUp();break;case 40:c.moveDown();break;default:return b.keyCode}b.returnValue=
false;b.cancelBubble=true;try{b.preventDefault()}catch(e){}return false};this.input.onkeypress=function(b){return preventEnter(b)};this.input.onkeyup=function(b){var c=this.instance;c.isTyping=true;b=c.adjustEventCompatibility(b);switch(b.keyCode){default:return b.keyCode}};setInterval("ctlUserSuggestFunction_WatchInputBox('"+this.container.id+"')",10);this.container.appendChild(this.input)}
ctlUserSuggest.prototype.setValue=function(a){if(!this.isSettingValue){this.isSettingValue=true;this.hideSuggestion();this.typingText=this.input.value=a;this.isSettingValue=false}};ctlUserSuggest.prototype.focusOnInput=function(){this.input.focus();this.input.select();try{setTimeout("document.getElementById('"+this.container.id+"').instance.input.focus()",1)}catch(a){}};ctlUserSuggest.prototype.getValue=function(){return this.input.value};
ctlUserSuggest.prototype.suggestionMouseClick=function(a){this.setValue(a.innerHTML.replace(new RegExp("</?em>","gi"),"").replaceAll("&amp;","&").match("^[^ ]*"),true);this.hideSuggestion()};ctlUserSuggest.prototype.hideSuggestion=function(){this.isSuggestionShown=false;this.suggestion.style.display="none";this.suggestion.selectedIndex=0};
ctlUserSuggest.prototype.moveUp=function(){if(this.isSuggestionShown){this.cursor++;this.suggestion.selectedIndex--;if(this.suggestion.selectedIndex<1)this.suggestion.selectedIndex=this.suggestion.childNodes.length;this.highlightRow()}};ctlUserSuggest.prototype.moveDown=function(){if(this.isSuggestionShown){this.cursor++;this.suggestion.selectedIndex++;if(this.suggestion.selectedIndex>this.suggestion.childNodes.length)this.suggestion.selectedIndex=1;this.highlightRow()}};
ctlUserSuggest.prototype.highlightRow=function(){if(this.isSuggestionShown&&this.suggestion.childNodes[0].className!="disabled"){for(var a=0;a<this.suggestion.childNodes.length;a++)this.suggestion.childNodes[a].className=a==this.suggestion.selectedIndex-1?"hover":"";this.input.value=this.typingText=this.suggestion.childNodes[this.suggestion.selectedIndex-1].innerHTML.replace(new RegExp("</?em>","gi"),"").unhtmlspecialchars().match("^[^ ]*")}};
ctlUserSuggest.prototype.requestSuggestion=function(){var a=this.instance;if(a.allowSuggestion){a.isTyping=true;a.cursor++;debug("Request "+a.cursor);var d=document.createElement("script");d.setAttribute("src",blogURL+"/control/action/user/suggest/?id="+a.container.getAttribute("id")+"&cursor="+a.cursor+"&input="+encodeURIComponent(a.input.value)+(STD.isSafari?"&encode=1":""));document.body.appendChild(d)}};
ctlUserSuggest.prototype.adjustEventCompatibility=function(a){if(navigator.appName=="Microsoft Internet Explorer"){a=window.event;a.target=a.srcElement}return a};function getOffsetTop(a){return a?a.offsetTop+getOffsetTop(a.offsetParent):0}function getOffsetLeft(a){return a?a.offsetLeft+getOffsetLeft(a.offsetParent):0}var StringBuffer=function(){this.buffer=[]};StringBuffer.prototype.append=function(a){this.buffer[this.buffer.length]=a};StringBuffer.prototype.toString=function(){return this.buffer.join("")};
if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(new RegExp("(^\\s*)|(\\s*$)","g"),"")};if(!String.prototype.htmlspecialchars)String.prototype.htmlspecialchars=function(){return this.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll("<","&gt;")};if(!String.prototype.unhtmlspecialchars)String.prototype.unhtmlspecialchars=function(){return this.replaceAll("&amp;","&").replaceAll("&lt;","<").replaceAll("&gt;",">")};var x=0;
function debug(a){try{document.getElementById("debug").innerHTML=++x+")"+a+"<br />"+document.getElementById("debug").innerHTML}catch(d){}}
function sendUserAddInfo(a,d){var b=new HTTPRequest(blogURL+"/control/action/user/add/?name="+a+"&email="+d);b.onSuccess=function(){PM.showMessage(_t("\uc0c8\ub85c\uc6b4 \uc0ac\uc6a9\uc790\uac00 \ucd94\uac00\ub418\uc5c8\uc2b5\ub2c8\ub2e4."),"right","top");ctlRefresh()};b.onError=function(){msg=this.getText("/response/result");alert(_t("\uc0ac\uc6a9\uc790\ub97c \ucd94\uac00\ud558\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4.")+"\r\nError : "+msg)};b.send()}
function sendBlogAddInfo(a,d){var b=new HTTPRequest(blogURL+"/control/action/blog/add/?owner="+a+"&identify="+d);b.onSuccess=function(){PM.showMessage(_t("\uc0c8\ub85c\uc6b4 \ube14\ub85c\uadf8\uac00 \ucd94\uac00\ub418\uc5c8\uc2b5\ub2c8\ub2e4."),"right","top");ctlRefresh()};b.onError=function(){msg=this.getText("/response/result");alert(_t("\ube14\ub85c\uadf8\ub97c \ucd94\uac00\ud558\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4.")+"\r\nError : "+msg)};b.send()}
function cleanUser(a){if(!confirm(_t("\ubaa8\ub4e0 \uae00\uacfc \ube14\ub85c\uadf8\uac00 \uad00\ub9ac\uc790\uc758 \uc18c\uc720\ub85c \uc62e\uaca8\uc9d1\ub2c8\ub2e4.")+"\t\n\n"+_t("\ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.")+"\t\n\n"+_t("\uacc4\uc18d \uc9c4\ud589\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")))return false;a=new HTTPRequest(blogURL+"/control/action/user/delete/?userid="+a);a.onSuccess=function(){PM.removeRequest(this);window.location.href="../"};a.onError=function(){PM.removeRequest(this);
msg=this.getText("/response/result");alert(_t("\uc0ac\uc6a9\uc790 \uc0ad\uc81c\uc5d0 \uc2e4\ud328\ud558\uc600\uc2b5\ub2c8\ub2e4.")+"\r\nError : "+msg)};PM.addRequest(a,_t("\uc0ac\uc6a9\uc790 \uc0ad\uc81c\uc911"));a.send()}function ctlRefresh(){window.location.reload()};
