djConfig.parseWidgets=false;dojo.require("dojo.dnd.HtmlDragAndDrop");dojo.require("dojo.widget.Parse");dojo.require("dojo.widget.Dialog");DragPanel=function(a,e){dojo.dnd.HtmlDragSource.call(this,a,e);this.dragClass="ajax-floating-panel";this.opacity=0.9;this.domNode.coverpageNumber!=null&&decorateDragPanel(this.domNode)};dojo.inherits(DragPanel,dojo.dnd.HtmlDragSource);DragPanelAdd=function(a,e){dojo.dnd.HtmlDragSource.call(this,a,e);this.dragClass="ajax-floating-panel";this.opacity=0.9};
dojo.inherits(DragPanelAdd,dojo.dnd.HtmlDragSource);DropPanel=function(a,e){dojo.dnd.HtmlDropTarget.call(this,a,e)};dojo.inherits(DropPanel,dojo.dnd.HtmlDropTarget);DropDeletePanel=function(a,e){dojo.dnd.HtmlDropTarget.call(this,a,e)};dojo.inherits(DropDeletePanel,dojo.dnd.HtmlDropTarget);var globalChker=true,globalNewNodeCounter=0;
dojo.lang.extend(DropPanel,{onDrop:function(a){if(a.dragObject.domNode.ajaxtype=="register"&&a.dragObject.domNode.moduleCategory=="plugin"){var e=document.createElement(a.dragObject.domNode.tagName);e.id="newDragPanel_"+globalNewNodeCounter++;e.className="coverpage-module coverpage-plugin-module";e.ajaxtype="register";e.moduleCategory=a.dragObject.domNode.moduleCategory;e.identifier=a.dragObject.domNode.identifier;e.innerHTML=a.dragObject.domNode.innerHTML;e.hasPropertyEdit=a.dragObject.domNode.hasPropertyEdit;
a.dragObject.domNode=e;new DragPanel(e,["coverpage"])}this.parentMethod=DropPanel.superclass.onDrop;e=this.parentMethod(a);delete this.parentMethod;if(e==true&&globalChker==true){for(var b=this.domNode.coverpage,c=0,d=a.dragObject.domNode.previousSibling;d!=null;){if(d.nodeType!=3&&d.className.indexOf("coverpage-module")!=-1)break;d=d.previousSibling}if(d!=null)c=d.modulePos+1;if(a.dragObject.domNode.ajaxtype=="reorder"){d=a.dragObject.domNode.coverpageNumber;var f=a.dragObject.domNode.modulePos;
a.dragObject.domNode.coverpageNumber=b;d=new HTTPRequest("POST",blogURL+"/owner/skin/coverpage/order?coverpageNumber="+d+"&targetCoverpageNumber="+b+"&modulePos="+f+"&targetPos="+c+viewMode);d.onSuccess=function(){clearWaitServerResponse()};d.onError=function(){globalChker=false;errorWaitServerResponse()};d.onVerify=function(){return true};d.send();waitServerResponse()}else if(a.dragObject.domNode.ajaxtype=="register"){a.dragObject.domNode.coverpageNumber=b;a.dragObject.domNode.ajaxtype="reorder";
d=blogURL+"/owner/skin/coverpage/register?coverpageNumber="+b+"&modulePos="+c+"&moduleId="+a.dragObject.domNode.identifier+viewMode;d=new HTTPRequest("POST",d);d.coverpage=b;d.modulepos=c;d.moduleCategory=a.dragObject.domNode.moduleCategory;d.onSuccess=function(){clearWaitServerResponse();this.moduleCategory=="plugin"&&previewPlugin(this.coverpage,this.modulepos);decorateDragPanel(a.dragObject.domNode)};d.onError=function(){globalChker=false;errorWaitServerResponse()};d.onVerify=function(){return true};
d.send();waitServerResponse()}else alert(a.dragObject.domNode.ajaxtype);reordering()}return e},createDropIndicator:function(){this.parentMethod=DropPanel.superclass.createDropIndicator;var a=this.parentMethod();delete this.parentMethod;with(this.dropIndicator.style){borderTopWidth="5px";borderTopColor="silver";borderTopStyle="solid"}return a}});
dojo.lang.extend(DropDeletePanel,{onDrop:function(a){if(a.dragObject.domNode.ajaxtype=="register"){if(this.dropIndicator){dojo.html.removeNode(this.dropIndicator);delete this.dropIndicator}return false}var e=a.dragObject.domNode.coverpageNumber,b=a.dragObject.domNode.modulePos;this.parentMethod=DropPanel.superclass.onDrop;a=this.parentMethod(a);delete this.parentMethod;window.location.href=blogURL+"/owner/skin/coverpage/delete?coverpageNumber="+e+"&modulePos="+b+viewMode;return a},createDropIndicator:function(){this.parentMethod=
DropPanel.superclass.createDropIndicator;var a=this.parentMethod();delete this.parentMethod;with(this.dropIndicator.style){borderTopWidth="5px";borderTopColor="silver";borderTopStyle="solid"}return a}});var dlg;
dojo.widget.defineWidget("dojo.widget.popupWindow",dojo.widget.Dialog,{templatePath:"",loadContents:function(){this.containerNode=this.domNode},setContent:function(a){this.domNode.innerHTML=a},placeModalDialog:function(){var a=dojo.html.getScroll().offset,e=dojo.html.getViewport(),b=dojo.html.getMarginBox(this.containerNode);if(b.width<200)b.width=200;if(b.height<200)b.height=200;var c=a.x+(e.width-b.width)/2;a=a.y+(e.height-b.height)/2;with(this.domNode.style){left=c+"px";top=a+"px"}}});
function submitCoverpagePlugin(a,e){for(var b=dlg.domNode.firstChild;b!=null;){if(b.tagName!=null&&b.tagName.toLowerCase()=="form")break;b=b.nextSibling}if(b!=null){var c=blogURL+"/owner/skin/coverpage/setPlugin?coverpageNumber="+a+"&modulePos="+e+"&ajaxcall=true"+viewMode,d="";for(b=b.firstChild;b!=null;){if(b.className!=null&&b.className.toLowerCase()=="field-box"){b=b.firstChild;break}b=b.nextSibling}for(;b!=null;){if(b.tagName!=null&&b.tagName.toLowerCase()=="div")for(var f=b.firstChild;f!=null;){if(f.tagName!=
null&&f.tagName.toLowerCase()=="input"&&f.type.toLowerCase()=="text")c+="&"+encodeURIComponent(f.name)+"="+encodeURIComponent(f.value);else if(f.tagName!=null&&f.tagName.toLowerCase()=="textarea"){if(d.length>0)d+="&";d+=f.name+"="+encodeURIComponent(f.value)}f=f.nextSibling}b=b.nextSibling}b=new HTTPRequest("POST",c);b.coverpage=a;b.modulepos=e;b.onSuccess=function(){previewPlugin(this.coverpage,this.modulepos);return true};b.onError=function(){errorWaitServerResponse();globalChker=false};b.onVerify=
function(){return true};b.send(d)}dlg.hide()}
function previewPlugin(a,e){var b=new HTTPRequest("GET",blogURL+"/owner/skin/coverpage/preview?coverpageNumber="+a+"&modulePos="+e+previewMode);b.coverpage=a;b.modulepos=e;b.onSuccess=function(){var c=document.getElementById("coverpage-ul-"+this.coverpage);if(c!=null)c=c.firstChild;for(;c!=null;){if(c.tagName!=null&&c.tagName.toLowerCase()=="li"){if(this.modulepos<=0)break;this.modulepos--}c=c.nextSibling}if(c!=null)c=c.lastChild;for(;c!=null;){if(c.tagName!=null&&c.tagName.toLowerCase()=="div")break;
c=c.previousSibling}if(c!=null)c.innerHTML=this._request.responseText};b.onError=function(){globalChker=false};b.onVerify=function(){return true};b.send()}
function decorateDragPanel(a){for(var e=a.coverpageNumber,b=a.modulePos,c=a.firstChild;c!=null;){if(c.tagName!=null&&c.tagName.toLowerCase()=="h4")break;c=c.nextSibling}if(c!=null){var d=document.createElement("a");d.className="module-close";d.href=blogURL+"/owner/skin/coverpage/delete/?coverpageNumber="+e+"&modulePos="+b+viewMode;d.title=decorateDragPanelString_deleteTitle;d.innerHTML='<img src="'+servicePath+adminSkin+'/image/img_delete_module.gif" border="0" alt="'+commonString_delete+'" />';c.nextSibling!=
null?a.insertBefore(d,c.nextSibling):a.appendChild(d)}for(c=a.firstChild;c!=null;){if(c.tagName!=null&&c.tagName.toLowerCase()=="div")c.style.clear="both";c=c.nextSibling}}
function editCoverpagePlugin(a,e){var b=new HTTPRequest("GET",blogURL+"/owner/skin/coverpage/edit?coverpageNumber="+a+"&modulePos="+e+"&ajaxcall=submitCoverpagePlugin("+a+","+e+")"+viewMode);b.onSuccess=function(){if(dlg!=null){dlg.setContent(this._request.responseText);var c=document.createElement("input");c.type="button";c.value=commonString_cancel;c.className="input-button";for(var d=dlg.domNode.firstChild;d!=null;){if(d.tagName!=null&&d.tagName.toLowerCase()=="form"){d=d.firstChild;break}d=d.nextSibling}for(;d!=
null;){if(d.className!=null&&d.className.toLowerCase()=="button-box"){d.appendChild(c);break}d=d.nextSibling}dlg.setCloseControl(c);dlg.show()}};b.onError=function(){globalChker=false};b.onVerify=function(){return true};b.send()}function waitServerResponse(){if(dlg!=null){dlg.setContent('<p class="waiting-string">'+commonString_saving+"</p>");dlg.show()}}function clearWaitServerResponse(){dlg.hide()}
function errorWaitServerResponse(){dlg.setContent('<p class="error-string">'+commonString_error+"</p>");var a=document.createElement("input");a.type="button";a.value=commonString_close;a.className="input-button";a.onclick=function(){window.location.reload();return false};var e=document.createElement("div");e.className="button-box";e.appendChild(a);dlg.domNode.appendChild(e);dlg.setCloseControl(a);dlg.show()};
