function TTGallery(a){this.containerId=a;this.container=document.getElementById(this.containerId);this.container.style.filter="progid:DXImageTransform.Microsoft.Fade(duration=0.3, overlap=1.0)";this.container.style.textAlign="center";this.container.style.width="100%";this.container.instance=this;this.offset=this.imageLoaded=this.numImages=0;this.src=[];this.caption=[];this.width=[];this.height=[];this.imageCache=[];this.nextText="NEXT";this.prevText="PREVIOUS";this.enlargeText="ZOOM";this.altText=
"gellery image";this.container=null}TTGallery.prototype.appendImage=function(a,b,d,e){this.numImages++;var c=new Image;c.src=a;c.onload=function(){};this.imageCache[this.imageCache.length]=a;this.src[this.src.length]=a;this.width[this.width.length]=d;this.height[this.height.length]=e;this.caption[this.caption.length]=b};
TTGallery.prototype.getControl=function(){var a=document.createElement("div");a.style.marginBottom="10px";a.className="galleryControl";a.style.color="#777";a.style.font="bold 0.9em Verdana, Sans-serif";a.innerHTML="("+(this.offset+1)+"/"+this.numImages+') <a href="#void" onclick="document.getElementById(\''+this.containerId+'\').instance.prev(); return false;"><img src="'+serviceURL+'/resources/image/gallery/gallery_prev.gif" style="vertical-align: middle;" alt="'+this.prevText+'" /></a> <a href="#void" onclick="document.getElementById(\''+
this.containerId+'\').instance.showImagePopup1(); return false;"><img src="'+serviceURL+'/resources/image/gallery/gallery_enlarge.gif" style="vertical-align: middle;" alt="'+this.enlargeText+'" /></a> <a href="#void" onclick="document.getElementById(\''+this.containerId+'\').instance.next(); return false;"><img src="'+serviceURL+'/resources/image/gallery/gallery_next.gif" style="vertical-align: middle;" alt="'+this.nextText+'" /></a>';return a};
TTGallery.prototype.getImage=function(){var a=document.createElement("img");a.instance=this;a.src=this.src[this.offset];a.width=this.width[this.offset];a.height=this.height[this.offset];a.onclick=this.showImagePopup2;a.alt=this.altText;a.style.cursor="pointer";return a};
TTGallery.prototype.getCaption=function(){var a=this.caption[this.offset];a=a.replace(new RegExp("&lt;?","gi"),"<");a=a.replace(new RegExp("&gt;?","gi"),">");a=a.replace(new RegExp("&quot;?","gi"),'"');a=a.replace(new RegExp("&#39;?","gi"),"'");a=a.replace(new RegExp("&amp;?","gi"),"&");a=a.replace(new RegExp("&lt;?","gi"),"<");a=a.replace(new RegExp("&gt;?","gi"),">");a=a.replace(new RegExp("&quot;?","gi"),'"');a=a.replace(new RegExp("&#39;?","gi"),"'");a=a.replace(new RegExp("&amp;?","gi"),"&");
var b=document.createElement("div");b.style.textAlign="center";b.style.marginTop="8px";b.className="galleryCaption";b.appendChild(document.createTextNode(a));return b};
TTGallery.prototype.show=function(a){this.container=document.getElementById(this.containerId);if(this.numImages==0){a=document.createElement("div");a.style.textAlign="center";a.style.color="#888";a.style.margin="10px auto";a.style.font="bold 2em/1 Verdana, Sans-serif";a.innerHTML="NO IMAGES";this.container.appendChild(a)}else{this.offset=typeof a=="undefined"?0:a<0?this.numImages-1:a>=this.numImages?0:a;this.container.filters&&this.container.filters[0].Apply();this.container.innerHTML="";this.container.appendChild(this.getControl());
this.container.appendChild(this.getImage());this.container.appendChild(this.getCaption());this.container.filters&&this.container.filters[0].Play()}this.container=null};TTGallery.prototype.prev=function(){this.show(this.offset-1)};TTGallery.prototype.next=function(){this.show(this.offset+1)};TTGallery.prototype.showImagePopup1=function(){this.showImagePopup()};TTGallery.prototype.showImagePopup2=function(){this.instance.showImagePopup()};TTGallery.prototype.showImagePopup=function(){try{open_img(this.src[this.offset])}catch(a){window.open(this.src[this.offset])}};
