function eolinTagFunction_WatchInputBox(a){try{var b=document.getElementById(a).instance,c=b.getInput();if(c.value.charAt(c.value.length-1)==",")if(c.value.length==1)c.value="";else b.setValue(c.value.substring(0,c.value.length-1));else if(c.value!=b.typingText){b.typingText=c.value;b.requestSuggestion()}}catch(e){}}
function eolinTagFunction_showLocalSuggestion(a,b,c){try{var e=document.getElementById(a).instance}catch(g){return}if(!(e.cursor!=b||!e.isTyping)){var l=e.getInput(),j=createHttp();if(j){j.open("GET",blogURL+"/suggest/?id="+a+"&cursor="+b+"&filter="+(STD.isSafari?c:encodeURIComponent(c)),true);j.onreadystatechange=function(){if(j.readyState==4)try{var f=j.responseXML.getElementsByTagName("response")[0],h=f.getAttribute("id"),m=f.getAttribute("cursor"),d=document.getElementById(h).instance;if(d.cursor==
m){h=[];var i=f.getElementsByTagName("tag");if(!d.allowEolinSuggestion&&i.length==0)d.hideSuggestion();else{for(f=0;f<i.length;f++)h[h.length]=i[f].lastChild.nodeValue;for(f=0;f<h.length;f++)for(i=0;i<d.suggestion.childNodes.length;i++)if(h[f]==d.suggestion.childNodes[i].innerHTML.replace(new RegExp("</?strong>","gi"),"")){d.suggestion.removeChild(d.suggestion.childNodes[i]);break}var k=new StringBuffer;for(f=0;f<h.length;f++){k.append('<li onmouseover="this.className=\'hover\'" onmouseout="this.className=\'\'" onmousedown="this.parentNode.instance.suggestionMouseClick(this)" style="background-color: #ccb"><strong>');
k.append(h[f].substring(0,l.value.length).htmlspecialchars().replaceAll("&amp;","&"));k.append("</strong>");k.append(h[f].substring(l.value.length).htmlspecialchars().replaceAll("&amp;","&"));k.append("</li>")}d.allowEolinSuggestion&&k.append(d.suggestion.innerHTML);d.suggestion.innerHTML=k.toString();if(!d.allowEolinSuggestion||d.getInput().value.trim()==""){d.suggestion.style.left=getOffsetLeft(l)+"px";d.suggestion.style.top=getOffsetTop(l)+l.offsetHeight+"px";d.suggestion.style.display="block";
d.isSuggestionShown=true;try{document.getElementById("previewSelected").style.visibility="hidden";document.getElementById("TCfilelist").style.visibility="hidden"}catch(n){}try{document.body.removeChild(d.suggestion)}catch(o){}document.body.appendChild(d.suggestion)}for(;d.suggestion.childNodes.length>10;)d.suggestion.removeChild(d.suggestion.childNodes[d.suggestion.childNodes.length-1])}}}catch(p){}};j.send(null);delete j}}}
function eolinTagFunction_showLocalSuggestionWithoutQuery(a,b,c){return eolinTagFunction_showLocalSuggestion(a,b,'name like "'+c.replace('"','\\"')+'%"')}
function eolinTagFunction_showSuggestion(){try{var a=document.getElementById(arguments[0]).instance}catch(b){return}if(!(a.cursor!=arguments[1]||!a.isTyping)){var c=a.getInput();if(c.value.trim()=="")a.hideSuggestion();else{a.suggestion.style.left=getOffsetLeft(c)+"px";a.suggestion.style.top=getOffsetTop(c)+c.offsetHeight+"px";var e=new StringBuffer;if(arguments[2]==0)for(var g=3;g<arguments.length;g++){arguments[g]=arguments[g].replaceAll("&quot;",'"');if(STD.isSafari)arguments[g]=decodeURIComponent(arguments[g]);
e.append('<li onmouseover="this.className=\'hover\'" onmouseout="this.className=\'\'" onmousedown="this.parentNode.instance.suggestionMouseClick(this)"><strong>');e.append(arguments[g].substring(0,c.value.length).htmlspecialchars().replace("&amp;","&"));e.append("</strong>");e.append(arguments[g].substring(c.value.length).htmlspecialchars().replace("&amp;","&"));e.append("</li>")}else{if(STD.isSafari)arguments[3]=decodeURIComponent(arguments[3]);e.append('<li class="disabled">');e.append("<strong>");
e.append(c.value.htmlspecialchars());e.append("</strong> - "+arguments[3]+"</li>")}a.suggestion.innerHTML=e.toString();a.suggestion.style.display="block";a.isSuggestionShown=true;try{document.body.removeChild(a.suggestion)}catch(l){}document.body.appendChild(a.suggestion)}}}
function Tag(a,b,c){this.name="Eolin Tag Object";this.copyright="Tatter & Company";this.allowEolinSuggestion=typeof c=="undefined"?false:!c;this.isSettingValue=false;this.instance=this;this.cursor=0;this.isSuggestionShown=this.isTyping=false;this.inputClassName=this.typingText="";this.language="ko";if(typeof b!="undefined")this.language=b;this.container=a;this.container.instance=this;this.suggestion=document.createElement("ul");this.suggestion.instance=this;this.suggestion.selectedIndex=0;this.suggestion.className=
"eolinSuggest";this.suggestion.style.margin="0px";this.suggestion.style.padding="0px";this.suggestion.style.listStyleType="none";this.suggestion.style.position="absolute";this.suggestion.style.display="none";this.suggestion.style.zIndex="999";setInterval("eolinTagFunction_WatchInputBox('"+this.container.id+"')",10);this.inputOnLast=this.createSuggestInput();this.inputTemporary=null;this.tagList=document.createElement("ul");this.tagList.instance=this;a=document.createElement("li");a.className="lastChild";
a.appendChild(this.inputOnLast);this.tagList.appendChild(a);this.container.appendChild(this.tagList)}Tag.prototype.isTemporaryEditing=function(){return this.inputTemporary!=null};Tag.prototype.setInputClassName=function(a){this.inputClassName=a;this.inputOnLast.className=a;if(this.inputTemporary)this.inputTemporary.className=a};Tag.prototype.getInput=function(){return this.inputTemporary==null?this.inputOnLast:this.inputTemporary};
Tag.prototype.adjustEventCompatibility=function(a){if(navigator.appName=="Microsoft Internet Explorer"){a=window.event;a.target=a.srcElement}return a};
Tag.prototype.createSuggestInput=function(){var a=document.createElement("input");a.instance=this;a.className=this.inputClassName;a.setAttribute("autocomplete","off");a.onblur=function(){var b=this.instance;b.isTyping=false;b.hideSuggestion();b.setValue(this.value)};a.onclick=this.requestSuggestion;a.onkeydown=function(b){var c=this.instance;c.isTyping=true;b=c.adjustEventCompatibility(b);switch(b.keyCode){case 8:if(this.value=="")c.moveBack();else return b.keyCode;break;case 13:c.setValue(this.value);
break;case 188:if(b.shiftKey)return b.keyCode;else c.setValue(this.value);break;case 9:if(this.value.trim()=="")return b.keyCode;c.setValue(this.value);break;case 27:c.hideSuggestion();break;case 38:c.moveUp();break;case 40:c.moveDown();break;default:return b.keyCode}b.returnValue=false;b.cancelBubble=true;try{b.preventDefault()}catch(e){}return false};a.onkeypress=function(b){return preventEnter(b)};return a};
Tag.prototype.suggestionMouseClick=function(a){this.getInput();this.hideSuggestion();this.setValue(a.innerHTML.replace(new RegExp("</?strong>","gi"),"").replaceAll("&amp;","&"))};
Tag.prototype.requestSuggestion=function(){var a=this.instance;a.isTyping=true;a.cursor++;if(!a.allowEolinSuggestion||a.getInput().value.trim()=="")eolinTagFunction_showLocalSuggestionWithoutQuery(a.container.getAttribute("id"),a.cursor,a.getInput().value);else{var b=document.createElement("script");b.setAttribute("src","http://suggest.eolin.com/tag/tatter/?id="+a.container.getAttribute("id")+"&cursor="+a.cursor+"&language="+a.language+"&word="+encodeURIComponent(a.getInput().value)+(STD.isSafari?
"&encode=1":""));document.body.appendChild(b)}};Tag.prototype.moveBack=function(){var a=this.getInput().parentNode.previousSibling;if(this.tagList.childNodes.length>1&&a){this.hideSuggestion();var b=a.innerHTML.unhtmlspecialchars();a.parentNode.removeChild(a);this.tagList.lastChild.className="lastChild";this.getInput().value=b}};
Tag.prototype.moveUp=function(){if(this.isSuggestionShown){this.cursor++;this.suggestion.selectedIndex--;if(this.suggestion.selectedIndex<1)this.suggestion.selectedIndex=this.suggestion.childNodes.length;this.highlightRow()}};Tag.prototype.moveDown=function(){if(this.isSuggestionShown){this.cursor++;this.suggestion.selectedIndex++;if(this.suggestion.selectedIndex>this.suggestion.childNodes.length)this.suggestion.selectedIndex=1;this.highlightRow()}};
Tag.prototype.highlightRow=function(){if(this.isSuggestionShown&&this.suggestion.childNodes[0].className!="disabled"){for(var a=0;a<this.suggestion.childNodes.length;a++)this.suggestion.childNodes[a].className=a==this.suggestion.selectedIndex-1?"hover":"";this.getInput().value=this.typingText=this.suggestion.childNodes[this.suggestion.selectedIndex-1].innerHTML.replace(new RegExp("</?strong>","gi"),"").unhtmlspecialchars()}};
Tag.prototype.getValues=function(){for(var a=[],b=0;b<this.tagList.childNodes.length-1;b++)a[b]=this.tagList.childNodes[b].innerHTML.trim().unhtmlspecialchars();return a};
Tag.prototype.setValue=function(a){if(!this.isSettingValue){this.isSettingValue=true;this.hideSuggestion();if(this.isTemporaryEditing()){this.inputTemporary.parentNode.onclick=this.tagListMouseClick;if(a.trim()=="")this.inputTemporary.parentNode.parentNode.removeChild(this.inputTemporary.parentNode);else this.inputTemporary.parentNode.innerHTML=a;this.typingText="";this.inputTemporary=null}else if(a.trim()!=""){var b=this.tagList.lastChild;b.className="";var c=document.createElement("li");c.onclick=
this.tagListMouseClick;c.appendChild(document.createTextNode(a));this.tagList.removeChild(b);this.tagList.appendChild(c);this.tagList.appendChild(b);this.typingText="";this.inputOnLast.value="";this.focusOnInput()}this.tagList.lastChild.className="lastChild";this.isSettingValue=false}};
Tag.prototype.tagListMouseClick=function(){var a=this.parentNode.instance;a.inputTemporary=a.createSuggestInput();a.inputTemporary.value=this.innerHTML.unhtmlspecialchars();a.typingText=this.innerHTML;this.innerHTML="";this.onclick=null;this.appendChild(a.inputTemporary);a.focusOnInput();a.requestSuggestion()};Tag.prototype.hideSuggestion=function(){this.isSuggestionShown=false;this.suggestion.style.display="none";this.suggestion.selectedIndex=0};
Tag.prototype.focusOnInput=function(){this.getInput().focus();this.getInput().select()};function getOffsetTop(a){return a?a.offsetTop+getOffsetTop(a.offsetParent):0}function getOffsetLeft(a){return a?a.offsetLeft+getOffsetLeft(a.offsetParent):0}var StringBuffer=function(){this.buffer=[]};StringBuffer.prototype.append=function(a){this.buffer[this.buffer.length]=a};StringBuffer.prototype.toString=function(){return this.buffer.join("")};
if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(new RegExp("(^\\s*)|(\\s*$)","g"),"")};if(!String.prototype.htmlspecialchars)String.prototype.htmlspecialchars=function(){return this.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll("<","&gt;")};if(!String.prototype.unhtmlspecialchars)String.prototype.unhtmlspecialchars=function(){return this.replaceAll("&amp;","&").replaceAll("&lt;","<").replaceAll("&gt;",">")};var x=0;
function debug(a){try{document.getElementById("debug").innerHTML=++x+")"+a+"<br />"+document.getElementById("debug").innerHTML}catch(b){}};
