function eolinLocationTagFunction_WatchInputBox(a){try{var c=document.getElementById(a).instance;if(c.input.value.charAt(c.input.value.length-1)=="/")if(input.value.length==1)input.value="";else c.setValue(c.input.value,true);else if(c.input.value!=c.typingText){c.typingText=c.input.value;c.requestSuggestion()}}catch(e){}}
function eolinLocationFunction_showLocalSuggestion(a,c,e){try{var b=document.getElementById(a).instance}catch(d){return}if(!(b.cursor!=c||!b.isTyping)){var h=b.input,k=createHttp();if(k){k.open("GET",blogURL+"/locationSuggest/?id="+a+"&cursor="+c+"&filter="+(STD.isSafari?e:encodeURIComponent(e)),true);k.onreadystatechange=function(){if(k.readyState==4)try{var g=k.responseXML.getElementsByTagName("response")[0],i=g.getAttribute("id"),n=g.getAttribute("cursor"),f=document.getElementById(i).instance;
if(f.cursor==n){i=[];var m=g.getElementsByTagName("location");if(!f.allowEolinSuggestion&&m.length==0)f.hideSuggestion();else{for(g=0;g<m.length;g++){value=m[g].lastChild.nodeValue.split("/");for(var j=0;j!=-1;j=e.indexOf("/",j+1))j!=0&&value.shift();i[i.length]=value.join("/")}for(g=0;g<i.length;g++)for(j=0;j<f.suggestion.childNodes.length;j++)if(i[g]==f.suggestion.childNodes[j].innerHTML.replace(new RegExp("</?em>","gi"),"")){f.suggestion.removeChild(f.suggestion.childNodes[j]);break}var l=new StringBuffer;
for(g=0;g<i.length;g++){l.append('<li onmouseover="this.className=\'hover\'" onmouseout="this.className=\'\'" onmousedown="this.parentNode.instance.suggestionMouseClick(this)" style="background-color: #ccb"><em>');l.append(i[g].substring(0,h.value.length).htmlspecialchars().replaceAll("&amp;","&"));l.append("</em>");l.append(i[g].substring(h.value.length).htmlspecialchars().replaceAll("&amp;","&"));l.append("</li>")}f.allowEolinSuggestion&&l.append(f.suggestion.innerHTML);f.suggestion.innerHTML=l.toString();
if(!f.allowEolinSuggestion||f.input.value.trim()==""){f.suggestion.style.left=getOffsetLeft(h)+"px";f.suggestion.style.top=getOffsetTop(h)+h.offsetHeight+"px";f.suggestion.style.display="block";f.isSuggestionShown=true;try{document.getElementById("previewSelected").style.visibility="hidden";document.getElementById("TCfilelist").style.visibility="hidden"}catch(o){}try{document.body.removeChild(f.suggestion)}catch(p){}document.body.appendChild(f.suggestion)}for(;f.suggestion.childNodes.length>10;)f.suggestion.removeChild(f.suggestion.childNodes[f.suggestion.childNodes.length-
1])}}}catch(q){}};k.send(null);delete k}}}
function eolinLocationTagFunction_showSuggestion(){try{var a=document.getElementById(arguments[0]).instance}catch(c){return}debug('<span style="color: red">Received '+a.cursor+"</span>");if(!(a.cursor!=arguments[1]||!a.isTyping)){a.suggestion.style.left=getOffsetLeft(a.input)+"px";a.suggestion.style.top=getOffsetTop(a.input)+a.input.offsetHeight+"px";var e=new StringBuffer;if(arguments[2]==0)for(var b=3;b<arguments.length;b++){arguments[b]=arguments[b].replaceAll("&quot;",'"');if(STD.isSafari)arguments[b]=
decodeURIComponent(arguments[b]);e.append('<li onmouseover="this.className=\'hover\'" onmouseout="this.className=\'\'" onmousedown="this.parentNode.instance.suggestionMouseClick(this)">');e.append(arguments[b].replace(new RegExp("("+a.input.value+")","gi"),"<em>$1</em>"));e.append("</li>")}else{b=arguments[3];var d=arguments[4],h=arguments[5];if(STD.isSafari){b=decodeURIComponent(b);d=decodeURIComponent(d);h=decodeURIComponent(h)}if(a.locationList.childNodes.length==1)e.append('<li class="disabled"><em>'+
a.input.value+"</em> - "+b+"<br />"+d+"</li>");else a.input.value.trim()==""?e.append('<li class="disabled">'+h+"</li>"):e.append('<li class="disabled"><em>'+a.input.value+"</em> - "+b+"</li>")}a.suggestion.innerHTML=e.toString();a.suggestion.style.display="block";a.isSuggestionShown=true;try{document.body.removeChild(a.suggestion)}catch(k){}document.body.appendChild(a.suggestion)}}
function LocationTag(a,c,e){this.name="Eolin Location Tag Object";this.copyright="Tatter & Company";this.allowEolinSuggestion=typeof e=="undefined"?false:!e;this.isSettingValue=this.isFocused=false;this.instance=this;this.cursor=0;this.inputClassName="";this.language="ko";if(typeof c!="undefined")this.language=c;this.isSuggestionShown=this.isTyping=false;this.typingText="";this.container=a;this.container.instance=this;this.suggestion=document.createElement("ul");this.suggestion.instance=this;this.suggestion.selectedIndex=
0;this.suggestion.className="eolinSuggest";this.suggestion.style.margin="0px";this.suggestion.style.padding="0px";this.suggestion.style.listStyleType="none";this.suggestion.style.position="absolute";this.suggestion.style.display="none";this.suggestion.style.zIndex="999";this.input=document.createElement("input");this.input.instance=this;this.input.className=this.inputClassName;this.input.setAttribute("autocomplete","off");this.input.onblur=function(){this.instance.isTyping=false;this.instance.typingText=
"";this.instance.setValue(this.value);this.instance.isFocused=false};this.input.onfocus=function(){if(!this.instance.isFocused){this.instance.isFocused=true;this.instance.isTyping=true;this.instance.typingText=this.value;this.instance.requestSuggestion()}};this.input.onkeydown=function(b){var d=this.instance;d.isTyping=true;b=d.adjustEventCompatibility(b);switch(b.keyCode){case 8:if(this.value=="")d.moveBack();else return b.keyCode;break;case 13:d.setValue(this.value,true);break;case 191:if(b.shiftKey)return b.keyCode;
else d.setValue(this.value,true);break;case 9:if(this.value.trim()=="")return b.keyCode;d.setValue(this.value,true);break;case 27:d.hideSuggestion();break;case 38:d.moveUp();break;case 40:d.moveDown();break;default:return b.keyCode}b.returnValue=false;b.cancelBubble=true;try{b.preventDefault()}catch(h){}return false};this.input.onkeypress=function(b){return preventEnter(b)};this.input.onkeyup=function(b){var d=this.instance;d.isTyping=true;b=d.adjustEventCompatibility(b);switch(b.keyCode){case 191:d.setValue(this.value,
true);break;default:return b.keyCode}b.returnValue=false;b.cancelBubble=true;try{b.preventDefault()}catch(h){}return false};setInterval("eolinLocationTagFunction_WatchInputBox('"+this.container.id+"')",10);this.locationList=document.createElement("ul");this.locationList.instance=this;a=document.createElement("li");a.className="lastChild";a.appendChild(this.input);this.locationList.appendChild(a);this.container.appendChild(this.locationList)}
LocationTag.prototype.getValues=function(){for(var a=[],c=0;c<this.locationList.childNodes.length-1;c++)a[c]=this.locationList.childNodes[c].innerHTML.trim().unhtmlspecialchars();return"/"+a.join("/")};
LocationTag.prototype.setValue=function(a,c){if(!this.isSettingValue){this.isSettingValue=true;this.hideSuggestion();var e=this.stringToLocation(a);this.input.parentNode.parentNode.removeChild(this.input.parentNode);for(var b=0;b<e.length;b++){var d=document.createElement("li");d.onclick=this.locationListMouseClick;d.appendChild(document.createTextNode(e[b]));this.locationList.appendChild(d)}d=document.createElement("li");d.appendChild(this.input);this.locationList.appendChild(d);this.locationList.lastChild.className=
"lastChild";this.typingText=this.input.value="";if(c){this.focusOnInput();navigator.userAgent.indexOf("Gecko")!=-1&&this.requestSuggestion()}this.isSettingValue=false}};LocationTag.prototype.focusOnInput=function(){this.input.focus();this.input.select();try{setTimeout("document.getElementById('"+this.container.id+"').instance.input.focus()",1)}catch(a){}};LocationTag.prototype.setInputClassName=function(a){this.inputClassName=a;this.input.className=a};
LocationTag.prototype.suggestionMouseClick=function(a){this.setValue(a.innerHTML.replace(new RegExp("</?em>","gi"),"").replaceAll("&amp;","&"),true);this.hideSuggestion()};LocationTag.prototype.locationListMouseClick=function(){var a=this.parentNode.instance,c=a.input;for(c.value=this.innerHTML.unhtmlspecialchars();this.nextSibling;)this.parentNode.removeChild(this.nextSibling);this.innerHTML=this.typingText="";this.onclick=null;this.appendChild(c);a.focusOnInput()};
LocationTag.prototype.hideSuggestion=function(){this.isSuggestionShown=false;this.suggestion.style.display="none";this.suggestion.selectedIndex=0};LocationTag.prototype.moveUp=function(){if(this.isSuggestionShown){this.cursor++;this.suggestion.selectedIndex--;if(this.suggestion.selectedIndex<1)this.suggestion.selectedIndex=this.suggestion.childNodes.length;this.highlightRow()}};
LocationTag.prototype.moveBack=function(){var a=this.input.parentNode.previousSibling;if(this.locationList.childNodes.length>1&&a){this.hideSuggestion();var c=a.innerHTML.unhtmlspecialchars();a.parentNode.removeChild(a);this.locationList.lastChild.className="lastChild";this.input.value=c}};
LocationTag.prototype.moveDown=function(){if(this.isSuggestionShown){this.cursor++;this.suggestion.selectedIndex++;if(this.suggestion.selectedIndex>this.suggestion.childNodes.length)this.suggestion.selectedIndex=1;this.highlightRow()}};
LocationTag.prototype.highlightRow=function(){if(this.isSuggestionShown&&this.suggestion.childNodes[0].className!="disabled"){for(var a=0;a<this.suggestion.childNodes.length;a++)this.suggestion.childNodes[a].className=a==this.suggestion.selectedIndex-1?"hover":"";this.input.value=this.typingText=this.suggestion.childNodes[this.suggestion.selectedIndex-1].innerHTML.replace(new RegExp("</?em>","gi"),"").unhtmlspecialchars()}};
LocationTag.prototype.getPath=function(){var a=this.getValues();return a+(a=="/"?"":"/")+this.input.value};
LocationTag.prototype.requestSuggestion=function(){var a=this.instance;if(!a.allowEolinSuggestion||a.input.value.trim()=="")eolinLocationFunction_showLocalSuggestion(a.container.getAttribute("id"),a.cursor,this.getPath());else{a.isTyping=true;a.cursor++;debug("Request "+a.cursor);var c=document.createElement("script");c.setAttribute("src","http://suggest.eolin.com/location/script/?id="+a.container.getAttribute("id")+"&cursor="+a.cursor+"&language="+a.language+"&path="+encodeURIComponent(a.getPath())+
(STD.isSafari?"&encode=1":""));document.body.appendChild(c)}};LocationTag.prototype.stringToLocation=function(a){try{var c=[],e=a.split("/");for(a=0;a<e.length;a++)if(e[a].trim()!="")c[c.length]=e[a].trim();return c}catch(b){return[]}};LocationTag.prototype.adjustEventCompatibility=function(a){if(navigator.appName=="Microsoft Internet Explorer"){a=window.event;a.target=a.srcElement}return a};function getOffsetTop(a){return a?a.offsetTop+getOffsetTop(a.offsetParent):0}
function getOffsetLeft(a){return a?a.offsetLeft+getOffsetLeft(a.offsetParent):0}var StringBuffer=function(){this.buffer=[]};StringBuffer.prototype.append=function(a){this.buffer[this.buffer.length]=a};StringBuffer.prototype.toString=function(){return this.buffer.join("")};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(new RegExp("(^\\s*)|(\\s*$)","g"),"")};
if(!String.prototype.htmlspecialchars)String.prototype.htmlspecialchars=function(){return this.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll("<","&gt;")};if(!String.prototype.unhtmlspecialchars)String.prototype.unhtmlspecialchars=function(){return this.replaceAll("&amp;","&").replaceAll("&lt;","<").replaceAll("&gt;",">")};var x=0;function debug(a){try{document.getElementById("debug").innerHTML=++x+")"+a+"<br />"+document.getElementById("debug").innerHTML}catch(c){}};
