function TTReader(){this.blogURL=blogURL;this.servicePath=servicePath;this.optionForceNewWindow=this.optionForceLoadImage=false;this.selectedEntry=this.selectedFeed=this.selectedGroup=this.editingFeedId=this.editingGroupId=0;this.selectedEntryObject=this.selectedFeedObject=this.selectedGroupObject=null;this.starredOnly=this.unreadOnly=false;this.searchKeyword="";this.isPannelCollapsed=false;this.entriesTotal=this.entriesShown=this.resizeHeight=this.resizeScroll=this.resizeStart=0;this.areEntriesLoading=
false;this.floatingListOffset=0;this.feedUpdating="\ud53c\ub4dc \uc5c5\ub370\uc774\ud2b8 \uc911";this.feedFailure="\uc798\ubabb\ub41c \ud53c\ub4dc";this.feedUpdate="\ud53c\ub4dc \uc5c5\ub370\uc774\ud2b8"}TTReader.prototype.setShownEntries=function(a){this.entriesShown=a;getObject("entriesShown").innerHTML=a};TTReader.prototype.setTotalEntries=function(a){this.entriesTotal=a;getObject("entriesTotal").innerHTML=a};TTReader.prototype.setBlogTitle=function(a){getObject("blogTitle").innerHTML=a};
TTReader.prototype.togglePannel=function(a){try{a=STD.event(a);a.returnValue=false;a.cancelBubble=true}catch(b){}if(this.isPannelCollapsed){getObject("pannel").style.display="block";getObject("toggleButton").className="pannel-show";getObject("toggleButton").innerHTML='<span class="text">'+hide_str+"</span>";setUserSetting("readerPannelVisibility",1)}else{getObject("pannel").style.display="none";getObject("toggleButton").className="pannel-hide";getObject("toggleButton").innerHTML='<span class="text">'+
show_str+"</span>";setUserSetting("readerPannelVisibility",0)}getObject("floatingList").style.top="0px";this.floatingListOffset=getObject("floatingList").offsetTop;this.isPannelCollapsed=!this.isPannelCollapsed};
TTReader.prototype.toggleConfigure=function(){if(getObject("groupsAndFeeds").style.display=="none"){getObject("groupsAndFeeds").style.display="block";getObject("configure").style.display="none";getObject("settingLabel").innerHTML='<span class="text">'+configureLabel+"</span>";getObject("settingLabel").parentNode.className="configureText"}else{this.isPannelCollapsed&&this.togglePannel();getObject("groupsAndFeeds").style.display="none";getObject("configure").style.display="block";getObject("settingLabel").innerHTML=
'<span class="text">'+pannelLabel+"</span>";getObject("settingLabel").parentNode.className="feedListText"}getObject("floatingList").style.top="0px";this.floatingListOffset=getObject("floatingList").offsetTop};
TTReader.prototype.startResizing=function(a){a=STD.event(a);if(a.target.tagName=="DIV"&&!Reader.isPannelCollapsed){STD.addEventListener(document);document.addEventListener("selectstart",Reader.returnFalse,false);document.addEventListener("mousemove",Reader.doResizing,false);Reader.resizeStart=a.clientY;Reader.resizeScroll=STD.getScrollTop();Reader.resizeHeight=parseInt(getObject("groupBox").style.height)}};TTReader.prototype.returnFalse=function(){return false};
TTReader.prototype.finishResizing=function(){if(Reader.resizeStart!=0){STD.removeEventListener(document);document.removeEventListener("mousemove",Reader.doResizing,false);document.removeEventListener("selectstart",Reader.returnFalse,false);setUserSetting("readerPannelHeight",parseInt(getObject("groupBox").style.height));Reader.resizeStart=0;getObject("floatingList").style.top="0px";this.floatingListOffset=getObject("floatingList").offsetTop}};
TTReader.prototype.doResizing=function(a){a=STD.event(a);a=Reader.resizeHeight+(a.clientY-Reader.resizeStart)+(STD.getScrollTop()-Reader.resizeScroll);if(a>=100){getObject("groupBox").style.height=a+"px";getObject("feedBox").style.height=a+"px"}};
TTReader.prototype.selectGroup=function(a,b){this.refreshFeedList(b);this.refreshEntryList(b,0);this.refreshEntry(b,0,0);this.selectedGroup=b;getObject("groupList0").className=getObject("groupList0").className.replace(" active-class"," inactive-class");if(this.selectedGroupObject!=null)this.selectedGroupObject.className=this.selectedGroupObject.className.replace(" active-class"," inactive-class");this.selectedGroupObject=a.parentNode.parentNode;this.selectedGroupObject.className=this.selectedGroupObject.className.replace(" rollover-class",
" active-class");extraClass=this.selectedGroupObject.className};
TTReader.prototype.selectFeed=function(a,b){this.refreshEntryList(this.selectedGroup,b);this.refreshEntry(this.selectedGroup,b,0);this.selectedFeed=b;if(this.selectedFeedObject!=null)this.selectedFeedObject.className=this.selectedFeedObject.className.replace(" active-class"," inactive-class");this.selectedFeedObject=a;this.selectedFeedObject.className=this.selectedFeedObject.className.replace(" rollover-class"," active-class");extraClass=this.selectedFeedObject.className};
TTReader.prototype.selectEntry=function(a){this.refreshEntry(this.selectedGroup,this.selectedFeed,a);tempClass=document.getElementById("entrytitleList"+this.selectedEntry).className;document.getElementById("entrytitleList"+this.selectedEntry).className=tempClass.replace(/active-class/,"inactive-class");this.selectedEntry=a;this.selectEntryObject(a)};
TTReader.prototype.selectEntryObject=function(a){var b=getObject("entrytitleList"+a);if(b){this.selectedEntryObject=b;this.selectedEntryObject.className="read active-class";a=getObject("listup");this.floatingListOffset==0&&this.setListPosition();this.startScroll("listup",getOffsetTop(b)-getOffsetTop(a)-a.offsetHeight/4)}else setTimeout("Reader.selectEntryObject("+a+")",100)};
TTReader.prototype.startScroll=function(a,b){var c=getObject(a);if(typeof b!="undefined")c.scrollTarget=Math.min(Math.max(parseInt(b),0),c.scrollHeight);if(c.scrollTop!=c.scrollTarget){c.scrollTop+=Math.ceil((c.scrollTarget-c.scrollTop)/5);c.scrollTop+=c.scrollTop>c.scrollTarget?-1:0;c.scrollTop<c.scrollHeight-c.offsetHeight&&setTimeout("Reader.startScroll('"+a+"')",10)}};
TTReader.prototype.refreshFeedGroup=function(){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/view/group/");a.onSuccess=function(){Reader.selectedGroup=0;Reader.selectedGroupObject=null;getObject("groupBox").innerHTML=this.getText("/response/view")};a.onError=function(){switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+" (refreshFeedGroup)","center","bottom")}};a.send("group=0&starred="+(this.starredOnly?1:0)+"&keyword="+this.searchKeyword)};
TTReader.prototype.refreshFeedList=function(a){var b=new HTTPRequest("POST",this.blogURL+"/owner/reader/view/feed/");b.onSuccess=function(){Reader.selectedFeed=0;Reader.selectedFeedObject=null;getObject("feedBox").innerHTML=this.getText("/response/view")};b.onError=function(){switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+" (refreshFeedList)","center","bottom")}};b.send("group="+a+"&starred="+(this.starredOnly?1:0)+"&keyword="+this.searchKeyword)};
TTReader.prototype.refreshEntryList=function(a,b){var c=new HTTPRequest("POST",this.blogURL+"/owner/reader/view/entries/");c.onSuccess=function(){getObject("listup").innerHTML=this.getText("/response/view");Reader.selectedEntry=this.getText("/response/firstEntryId");try{Reader.selectedEntryObject=getObject("entrytitleList"+Reader.selectedEntry).parentNode}catch(d){Reader.selectedEntryObject=null}Reader.setShownEntries(parseInt(this.getText("/response/entriesShown")));Reader.setTotalEntries(parseInt(this.getText("/response/entriesTotal")))};
c.onError=function(){switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+" (refreshEntryList)","center","bottom")}};c.send("group="+(a==undefined?0:a)+"&feed="+(b==undefined?0:b)+"&unread="+(this.unreadOnly?1:0)+"&starred="+(this.starredOnly?1:0)+"&keyword="+this.searchKeyword)};
TTReader.prototype.imageLoadingFailed=function(a){a=STD.event(a);var b=a.target;if(b.nodeType==9)b=a.currentTarget;STD.removeEventListener(b);b.removeEventListener("error",Reader.imageLoadingFailed,false);b.src=Reader.blogURL+"/owner/reader/imageLoader/?url="+encodeURIComponent(b.src)};
TTReader.prototype.doPostProcessingOnEntry=function(){if(Reader.optionForceLoadImage)for(var a=searchChildNodes(getObject("entryBody"),"img"),b=0;b<a.length;b++)if(a[b].getAttribute("trying")!="trying"){a[b].setAttribute("trying","trying");STD.addEventListener(a[b]);a[b].addEventListener("error",Reader.imageLoadingFailed,false)}if(Reader.optionForceNewWindow){a=searchChildNodes(getObject("entryBody"),"a");for(b=0;b<a.length;b++)a[b].target="_blank"}};
TTReader.prototype.refreshEntry=function(a,b,c){var d=new HTTPRequest("POST",this.blogURL+"/owner/reader/view/entry/");d.onSuccess=function(){Reader.selectedEntry=this.getText("/response/id");getObject("blogTitle").innerHTML=this.getText("/response/blog");getObject("entry").innerHTML=this.getText("/response/view");try{getObject("entrytitleList"+Reader.selectedEntry).className="read active-class"}catch(e){}Reader.setListPosition(true);Reader.doPostProcessingOnEntry();window.scrollTo(0,getOffsetTop(getObject("scrollPoint")))};
d.onError=function(){switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+" (refreshEntry)","center","bottom")}};d.send("group="+(a==undefined?0:a)+"&feed="+(b==undefined?0:b)+"&entry="+c+"&unread="+(this.unreadOnly?1:0)+"&starred="+(this.starredOnly?1:0)+"&keyword="+this.searchKeyword)};
TTReader.prototype.prevEntry=function(){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/view/entry/next/");a.onSuccess=function(){if(this.getText("/response/id")!=0){Reader.selectedEntry=this.getText("/response/id");Reader.selectEntry(Reader.selectedEntry)}else PM.showErrorMessage(s_notFoundPrevPost,"center","bottom")};a.onError=function(){switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+" (prevEntry)","center","bottom")}};a.send("group="+this.selectedGroup+
"&feed="+this.selectedFeed+"&entry="+this.selectedEntry+"&unread="+(this.unreadOnly?1:0)+"&starred="+(this.starredOnly?1:0)+"&keyword="+this.searchKeyword)};
TTReader.prototype.nextEntry=function(){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/view/entry/previous/");a.onSuccess=function(){if(this.getText("/response/id")!=0){getObject("entrytitleList"+this.getText("/response/id"))==null&&Reader.listScroll(true);Reader.selectedEntry=this.getText("/response/id");Reader.selectEntry(Reader.selectedEntry)}else PM.showErrorMessage(s_notFoundNextPost,"center","bottom")};a.onError=function(){switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+
" (nextEntry)","center","bottom")}};a.send("group="+this.selectedGroup+"&feed="+this.selectedFeed+"&entry="+this.selectedEntry+"&unread="+(this.unreadOnly?1:0)+"&starred="+(this.starredOnly?1:0)+"&keyword="+this.searchKeyword)};
TTReader.prototype.addGroup=function(a){var b=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/group/add/");b.onSuccess=function(){Reader.selectedGroup=0;Reader.selectedGroupObject=null;getObject("groupBox").innerHTML=this.getText("/response/view");PM.removeRequest(this);PM.showMessage(s_groupAdded,"center","bottom")};b.onError=function(){PM.removeRequest(this);switch(parseInt(this.getText("/response/error"))){case 1:alert(s_enterFeedName);break;case 2:alert(s_groupExists);break;default:PM.showErrorMessage(s_unknownError+
" (addGroup)","center","bottom")}};PM.addRequest(b,s_addingGroup);b.send("title="+encodeURIComponent(a)+"&current="+this.selectedGroup)};TTReader.prototype.editGroup=function(a,b){this.editingGroupId=a;getObject("groupList").style.display="none";getObject("groupAdder").style.display="none";getObject("groupEditor").style.display="block";getObject("changeGroupTitle").value=b;getObject("changeGroupTitle").select()};
TTReader.prototype.cancelEditGroup=function(){getObject("groupList").style.display="";getObject("groupAdder").style.display="";getObject("groupEditor").style.display="none"};
TTReader.prototype.editGroupExecute=function(){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/group/edit/");a.onSuccess=function(){Reader.selectedGroup=0;Reader.selectedGroupObject=null;getObject("groupBox").innerHTML=this.getText("/response/view");PM.removeRequest(this);PM.showMessage(s_groupModified,"center","bottom")};a.onError=function(){PM.removeRequest(this);switch(parseInt(this.getText("/response/error"))){case 1:alert(s_enterGroupName);break;case 2:break;default:PM.showErrorMessage(s_unknownError+
" (editGroupExecute)","center","bottom")}};PM.addRequest(a,s_editingGroup);a.send("id="+this.editingGroupId+"&title="+encodeURIComponent(getObject("changeGroupTitle").value)+"&current="+this.selectedGroup)};
TTReader.prototype.deleteGroup=function(){if(confirm(s_confirmDelete)){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/group/delete/");a.onSuccess=function(){Reader.selectedGroup=0;Reader.selectedGroupObject=null;getObject("groupBox").innerHTML=this.getText("/response/view");PM.removeRequest(this);PM.showMessage(s_groupRemoved,"center","bottom")};a.onError=function(){PM.removeRequest(this);switch(parseInt(this.getText("/response/error"))){case 1:alert(s_groupNotFound);break;default:PM.showErrorMessage(s_unknownError+
" (deleteGroup)","center","bottom")}};PM.addRequest(a,s_removingGroup);a.send("id="+this.editingGroupId+"&current="+this.selectedGroup)}};
TTReader.prototype.addFeed=function(a){var b=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/feed/add/");b.onSuccess=function(){Reader.selectedFeed=0;Reader.selectedFeedObject=null;getObject("feedBox").innerHTML=this.getText("/response/view");PM.showMessage(s_feedAdded,"center","bottom");PM.removeRequest(this);Reader.refreshEntryList(this.selectedGroup,this.selectedFeed);Reader.refreshEntry(this.selectedGroup,this.selectedFeed,0)};b.onError=function(){PM.removeRequest(this);switch(parseInt(this.getText("/response/error"))){case 1:alert(s_feedExists);
break;case 2:alert(s_conNotConnect);break;case 3:alert(s_feedBroken);break;default:PM.showErrorMessage(s_unknownError+" (addFeed)","center","bottom")}};PM.addRequest(b,s_requestFeed);b.send("group="+this.selectedGroup+"&url="+encodeURIComponent(a))};
TTReader.prototype.editFeed=function(a,b){this.editingFeedId=a;getObject("feedList").style.display="none";getObject("feedAdder").style.display="none";getObject("feedEditor").style.display="block";getObject("changeFeedGroup").value=this.selectedGroup;getObject("changeFeedURL").value=b;getObject("changeFeedURL").select()};TTReader.prototype.cancelEditFeed=function(){getObject("feedList").style.display="";getObject("feedAdder").style.display="";getObject("feedEditor").style.display="none"};
TTReader.prototype.editFeedExecute=function(){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/feed/edit/");a.onSuccess=function(){Reader.selectedFeed=0;Reader.selectedFeedObject=null;getObject("feedBox").innerHTML=this.getText("/response/view");PM.removeRequest(this);PM.showMessage(s_feedModified,"center","bottom")};a.onError=function(){PM.removeRequest(this);switch(parseInt(this.getText("/response/error"))){case 1:alert(s_enterFeedName);break;case 2:break;default:PM.showErrorMessage(s_unknownError+
" (editFeedExecute)","center","bottom")}};PM.addRequest(a,s_editingFeed);a.send("id="+this.editingFeedId+"&old_group="+this.selectedGroup+"&new_group="+getObject("changeFeedGroup").value+"&url="+encodeURIComponent(getObject("changeFeedURL").value))};
TTReader.prototype.deleteFeed=function(){if(confirm(s_confirmDelete)){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/feed/delete/");a.onSuccess=function(){Reader.selectedFeed=0;Reader.selectedFeedObject=null;getObject("feedBox").innerHTML=this.getText("/response/view");PM.removeRequest(this);PM.showMessage(s_feedRemoved,"center","bottom");Reader.refreshEntryList(this.selectedGroup,this.selectedFeed);Reader.refreshEntry(this.selectedGroup,this.selectedFeed,0)};a.onError=function(){PM.removeRequest(this);
switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+" (deleteFeed)","center","bottom")}};PM.addRequest(a,s_removingFeed);a.send("id="+this.editingFeedId+"&group="+this.selectedGroup)}};
TTReader.prototype.saveSetting=function(){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/config/save/");a.onSuccess=function(){getObject("groupsAndFeeds").style.display="block";getObject("configure").style.display="none";getObject("settingLabel").innerHTML='<span class="text">'+configureLabel+"</span>";PM.showMessage(s_saved,"center","bottom")};a.onError=function(){PM.removeRequest(this);switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+" (saveSetting)",
"center","bottom")}};var b=document.getElementById("reader-section"),c=b.updateCycle?b.updateCycle.value:"",d=b.feedLife?b.feedLife.value:"",e=b.loadImage?document.getElementById("loadImage1").checked?1:2:"";a.send("updateCycle="+c+"&feedLife="+d+"&loadImage="+e+"&allowScript="+(b.allowScript?b.allowScript[0].checked?1:2:"")+"&newWindow="+(b.newWindow?b.newWindow[0].checked?1:2:""));Reader.optionForceLoadImage=document.getElementById("loadImage1")&&document.getElementById("loadImage1").checked?true:
false;Reader.optionForceNewWindow=b.newWindow[1]&&b.newWindow[1].checked?true:false};TTReader.prototype.markAsUnread=function(a){var b=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/mark/unread/");b.presetProperty(getObject("entrytitleList"+a),"className","unread active-class");b.onSuccess=function(){PM.showMessage(s_markedAsUnread,"center","bottom")};b.send("id="+a)};
TTReader.prototype.markAsReadAll=function(){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/mark/allread/");a.onSuccess=function(){Reader.showUnreadOnly();PM.showMessage(s_markedAsReadAll,"center","bottom")};a.send()};
TTReader.prototype.toggleStarred=function(a){if(typeof a=="undefined")a=this.selectedEntry;if(getObject("star"+a)){if(getObject("star"+a).className.match("-on-")){var b=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/mark/unstar/");b._ttreader=this;b.onSuccess=function(){getObject("star"+a).className=getObject("star"+a).className.replace("-on-","-off-");getObject("star"+a).innerHTML='<span class="text">'+disscrapedPostText+"</span>"}}else{b=new HTTPRequest("POST",this.blogURL+"/owner/reader/action/mark/star/");
b._ttreader=this;b.onSuccess=function(){getObject("star"+a).className=getObject("star"+a).className.replace("-off-","-on-");getObject("star"+a).innerHTML='<span class="text">'+scrapedPostText+"</span>"}}b.send("id="+a)}};
TTReader.prototype.showUnreadOnly=function(){this.unreadOnly=true;this.starredOnly=false;this.searchKeyword="";this.refreshFeedGroup();this.refreshFeedList(this.selectedGroup);this.refreshEntryList(this.selectedGroup,this.selectedFeed);this.refreshEntry(this.selectedGroup,this.selectedFeed,0)};
TTReader.prototype.showStarredOnly=function(){this.unreadOnly=false;this.searchKeyword="";if(this.starredOnly){this.starredOnly=false;getObject("starredOnlyIndicator").className="scrap-off-icon"}else{this.starredOnly=true;getObject("starredOnlyIndicator").className="scrap-on-icon"}this.refreshFeedGroup();this.refreshFeedList(0);this.refreshEntryList(0,0);this.refreshEntry(0,0,0)};
TTReader.prototype.showSearch=function(){this.starredOnly=false;this.searchKeyword=getObject("keyword").value;this.refreshFeedGroup();this.refreshFeedList(0);this.refreshEntryList(0,0);this.refreshEntry(0,0,0)};
TTReader.prototype.listScroll=function(a){var b=getObject("listup");if((b.offsetHeight+b.scrollTop>b.scrollHeight-100||a==1)&&this.entriesShown<this.entriesTotal&&!this.areEntriesLoading){this.areEntriesLoading=true;getObject("feedLoadingIndicator").style.display="block";a=new HTTPRequest("POST",this.blogURL+"/owner/reader/view/entries/more/");a.onSuccess=function(){PM.removeRequest(this);Reader.areEntriesLoading=false;Reader.setShownEntries(Reader.entriesShown+parseInt(this.getText("/response/count")));
getObject("feedLoadingIndicator").style.display="none";var c=document.createElement("div");c.innerHTML=this.getText("/response/view");getObject("additionalFeedContainer").appendChild(c);if(Reader.entriesShown==Reader.entriesTotal)getObject("iconMoreEntries").style.display="none"};a.onError=function(){PM.removeRequest(this);Reader.areEntriesLoading=false;getObject("feedLoadingIndicator").style.display="none";switch(parseInt(this.getText("/response/error"))){default:PM.showErrorMessage(s_unknownError+
" (listScroll)","center","bottom")}};PM.addRequest(a,s_loadingList);a.send("group="+this.selectedGroup+"&feed="+this.selectedFeed+"&unread="+(this.unreadOnly?1:0)+"&starred="+(this.starredOnly?1:0)+"&keyword="+this.searchKeyword+"&loaded="+this.entriesShown)}};
TTReader.prototype.setListPosition=function(a){var b=getObject("floatingList");if(a==true){b.style.top="0px";this.setListPosition()}else{if(this.floatingListOffset==0)this.floatingListOffset=b.offsetTop;b.style.top=STD.getScrollTop()>this.floatingListOffset-6?STD.getScrollTop()-this.floatingListOffset+6+"px":"0px"}};TTReader.prototype.openEntryInNewWindow=function(){window.open(getObject("entryPermalink").href)};
TTReader.prototype.updateFeed=function(a,b){getObject("iconFeedStatus"+a).className="updating-button button";getObject("iconFeedStatus"+a).innerHTML="<span>"+this.feedUpdating+"</span>";var c=new HTTPRequest("GET",this.blogURL+"/owner/reader/update/"+a);c.onSuccess=function(){getObject("iconFeedStatus"+a).className="update-button button";getObject("iconFeedStatus"+a).innerHTML="<span>"+this.feedUpdate+"</span>";Reader.refreshFeedList(Reader.selectedGroup);Reader.refreshEntryList(Reader.selectedGroup,
Reader.selectedFeed);PM.showMessage(b,"center","bottom")};c.onError=function(){getObject("iconFeedStatus"+a).className="failure-button button";getObject("iconFeedStatus"+a).innerHTML="<span>"+this.feedFailure+"</span>";switch(parseInt(this.getText("/response/error"))){case 1:alert(s_xmlBroken);break;case 2:alert(s_conNotConnect);break;case 3:alert(s_feedBroken);break;default:PM.showErrorMessage(s_unknownError+" (updateFeed)","center","bottom")}};c.send()};
TTReader.prototype.updateAllFeeds=function(){getObject("hiddenFrame").src=this.blogURL+"/owner/reader/update/?__T__="+(new Date).getTime()};TTReader.prototype.importOPMLUpload=function(){document.getElementById("opml-section").submit()};
TTReader.prototype.importOPMLURL=function(){var a=new HTTPRequest("POST",this.blogURL+"/owner/reader/opml/import/url/");a.onSuccess=function(){PM.removeRequest(this);Reader.refreshFeedGroup();Reader.refreshFeedList(0);Reader.refreshEntryList(0,0);Reader.refreshEntry(0,0,0);this.getText("/response/total")==1?alert(this.getText("/response/total")+s_opmlUploadCompleteSingle):alert(this.getText("/response/total")+s_opmlUploadCompleteMulti)};a.onError=function(){PM.removeRequest(this);switch(parseInt(this.getText("/response/error"))){case 1:alert(s_conNotConnect);
break;case 2:alert(s_xmlBroken);break;case 3:alert(s_opmlBroken);break;default:PM.showErrorMessage(s_unknownError+" (importOPMLURL)","center","bottom")}};PM.addRequest(a,s_loadingOPML);a.send("url="+encodeURIComponent(getObject("opmlRequestValue").value))};TTReader.prototype.exportOPML=function(){window.location=this.blogURL+"/owner/reader/opml/export/"};
