var _ERROR_MESSAGE="Oops.. there was a problem with your request.<br /><br />Please try again.<br /><br /><em>Click anywhere to close.</em>",_RESIZE_DURATION=400,_INITIAL_WIDTH=250,_INITIAL_HEIGHT=250,_CONTENTS_WIDTH=500,_CONTENTS_HEIGHT=400,_DEF_CONTENTS_WIDTH=500,_DEF_CONTENTS_HEIGHT=400,_ANIMATE_CAPTION=true,_EVAL_SCRIPTS=false,_EVAL_RESPONSE=false,MOOdalBox={init:function(a){this.options=Object.extend({resizeDuration:_RESIZE_DURATION,initialWidth:_INITIAL_WIDTH,initialHeight:_INITIAL_HEIGHT,contentsWidth:_CONTENTS_WIDTH,
contentsHeight:_CONTENTS_HEIGHT,defContentsWidth:_DEF_CONTENTS_WIDTH,defContentsHeight:_DEF_CONTENTS_HEIGHT,animateCaption:_ANIMATE_CAPTION,evalScripts:_EVAL_SCRIPTS,evalResponse:_EVAL_RESPONSE},a||{});this.anchors=[];$A($$("a")).each(function(b){if(b.rel&&b.href&&b.rel.test("^moodalbox","i")){b.onclick=this.click.pass(b,this);this.anchors.push(b)}},this);this.eventKeyDown=this.keyboardListener.bindWithEvent(this);this.eventPosition=this.position.bind(this);this.overlay=(new Element("div")).setProperty("id",
"mb_overlay").injectInside(document.body);this.center=(new Element("div")).setProperty("id","mb_center").setStyles({width:this.options.initialWidth+"px",height:this.options.initialHeight+"px",marginLeft:"-"+this.options.initialWidth/2+"px",display:"none"}).injectInside(document.body);this.contents=(new Element("div")).setProperty("id","mb_contents").injectInside(this.center);this.bottom=(new Element("div")).setProperty("id","mb_bottom").setStyle("display","none").injectInside(document.body);this.closelink=
(new Element("a")).setProperties({id:"mb_close_link",href:"#"}).injectInside(this.bottom);this.caption=(new Element("div")).setProperty("id","mb_caption").injectInside(this.bottom);(new Element("div")).setStyle("clear","both").injectInside(this.bottom);this.error=(new Element("div")).setProperty("id","mb_error").setHTML(_ERROR_MESSAGE);this.closelink.onclick=this.overlay.onclick=this.close.bind(this);a=this.nextEffect.bind(this);this.fx={overlay:this.overlay.effect("opacity",{duration:500}).hide(),
resize:this.center.effects({duration:this.options.resizeDuration,onComplete:a}),contents:this.contents.effect("opacity",{duration:500,onComplete:a}),bottom:this.bottom.effects({duration:400,onComplete:a})};this.ajaxRequest=Class.empty},click:function(a){return this.open(a.href,a.title,a.rel)},open:function(a,b,c){this.href=a;this.title=b;this.rel=c;this.position();this.setup(true);this.top=Window.getScrollTop()+Window.getHeight()/15;this.center.setStyles({top:this.top+"px",display:""});this.fx.overlay.custom(0.8);
return this.loadContents(a)},position:function(){this.overlay.setStyles({top:Window.getScrollTop()+"px",height:Window.getHeight()+"px"})},setup:function(a){var b=$A($$("object"));b.extend($$(window.ActiveXObject?"select":"embed"));b.each(function(c){c.style.visibility=a?"hidden":""});b=a?"addEvent":"removeEvent";window[b]("scroll",this.eventPosition)[b]("resize",this.eventPosition);document[b]("keydown",this.eventKeyDown);this.step=0},loadContents:function(){if(this.step)return false;this.step=1;
var a=this.rel.match(/[0-9]+/g);this.options.contentsWidth=a&&a[0]>0?a[0]:this.options.defContentsWidth;this.options.contentsHeight=a&&a[1]>0?a[1]:this.options.defContentsHeight;this.bottom.setStyles({opacity:"0",height:"0px",display:"none"});this.center.className="mb_loading";this.fx.contents.hide();a=this.nextEffect.bind(this);var b=this.ajaxFailure.bind(this);this.ajaxRequest=(new Ajax(this.href,{method:"get",update:this.contents,evalScripts:this.options.evalScripts,evalResponse:this.options.evalResponse,
onComplete:a,onFailure:b})).request();return false},ajaxFailure:function(){this.contents.setHTML("");this.error.clone().injectInside(this.contents);this.nextEffect();this.center.setStyle("cursor","pointer");this.bottom.setStyle("cursor","pointer");this.center.onclick=this.bottom.onclick=this.close.bind(this)},nextEffect:function(){switch(this.step++){case 1:this.center.className="";this.center.setStyle("cursor","default");this.bottom.setStyle("cursor","default");this.center.onclick=this.bottom.onclick=
"";this.caption.setHTML(this.title);this.contents.setStyles({width:this.options.contentsWidth+"px",height:this.options.contentsHeight+"px"});if(this.center.clientHeight!=this.contents.offsetHeight){this.fx.resize.custom({height:[this.center.clientHeight,this.contents.offsetHeight]});break}this.step++;case 2:if(this.center.clientWidth!=this.contents.offsetWidth){this.fx.resize.custom({width:[this.center.clientWidth,this.contents.offsetWidth],marginLeft:[-this.center.clientWidth/2,-this.contents.offsetWidth/
2]});break}this.step++;case 3:this.bottom.setStyles({top:this.top+this.center.clientHeight+"px",width:this.contents.style.width,marginLeft:this.center.style.marginLeft,display:""});this.fx.contents.custom(0,1);break;case 4:if(this.options.animateCaption){this.fx.bottom.custom({opacity:[0,1],height:[0,this.bottom.scrollHeight]});break}this.bottom.setStyles({opacity:"1",height:this.bottom.scrollHeight+"px"});case 5:this.step=0}},keyboardListener:function(a){if(a.control&&a.key=="w"||a.control&&a.key==
"x"||a.key=="esc"){this.close();a.stop()}},close:function(){if(!(this.step<0)){this.step=-1;for(var a in this.fx)this.fx[a].clearTimer();this.center.style.display=this.bottom.style.display="none";this.center.className="mb_loading";this.fx.overlay.chain(this.setup.pass(false,this)).custom(0);return false}}};window.addEventListener("load",MOOdalBox.init.bind(MOOdalBox),true);
