dojo.require("dojo.html.common");dojo.provide("dojo.html.selection");dojo.require("dojo.dom");dojo.require("dojo.lang.common");dojo.html.selectionType={NONE:0,TEXT:1,CONTROL:2};dojo.html.clearSelection=function(){var a=dojo.global(),b=dojo.doc();try{if(a.getSelection)dojo.render.html.safari?a.getSelection().collapse():a.getSelection().removeAllRanges();else if(b.selection)if(b.selection.empty)b.selection.empty();else b.selection.clear&&b.selection.clear();return true}catch(c){dojo.debug(c);return false}};
dojo.html.disableSelection=function(a){a=dojo.byId(a)||dojo.body();var b=dojo.render.html;if(b.mozilla)a.style.MozUserSelect="none";else if(b.safari)a.style.KhtmlUserSelect="none";else if(b.ie)a.unselectable="on";else return false;return true};dojo.html.enableSelection=function(a){a=dojo.byId(a)||dojo.body();var b=dojo.render.html;if(b.mozilla)a.style.MozUserSelect="";else if(b.safari)a.style.KhtmlUserSelect="";else if(b.ie)a.unselectable="off";else return false;return true};
dojo.html.selectElement=function(){dojo.deprecated("dojo.html.selectElement","replaced by dojo.html.selection.selectElementChildren",0.5)};dojo.html.selectInputText=function(a){var b=dojo.global(),c=dojo.doc();a=dojo.byId(a);if(c.selection&&dojo.body().createTextRange){b=a.createTextRange();b.moveStart("character",0);b.moveEnd("character",a.value.length);b.select()}else if(b.getSelection){b.getSelection();a.setSelectionRange(0,a.value.length)}a.focus()};
dojo.html.isSelectionCollapsed=function(){dojo.deprecated("dojo.html.isSelectionCollapsed","replaced by dojo.html.selection.isCollapsed",0.5);return dojo.html.selection.isCollapsed()};
dojo.lang.mixin(dojo.html.selection,{getType:function(){if(dojo.doc().selection)return dojo.html.selectionType[dojo.doc().selection.type.toUpperCase()];else{var a=dojo.html.selectionType.TEXT,b;try{b=dojo.global().getSelection()}catch(c){}if(b&&b.rangeCount==1){b=b.getRangeAt(0);if(b.startContainer==b.endContainer&&b.endOffset-b.startOffset==1&&b.startContainer.nodeType!=dojo.dom.TEXT_NODE)a=dojo.html.selectionType.CONTROL}return a}},isCollapsed:function(){var a=dojo.global(),b=dojo.doc();if(b.selection)return b.selection.createRange().text==
"";else if(a.getSelection){a=a.getSelection();return dojo.lang.isString(a)?a=="":a.isCollapsed||a.toString()==""}},getSelectedElement:function(){if(dojo.html.selection.getType()==dojo.html.selectionType.CONTROL)if(dojo.doc().selection){var a=dojo.doc().selection.createRange();if(a&&a.item)return dojo.doc().selection.createRange().item(0)}else{a=dojo.global().getSelection();return a.anchorNode.childNodes[a.anchorOffset]}},getParentElement:function(){if(dojo.html.selection.getType()==dojo.html.selectionType.CONTROL){var a=
dojo.html.selection.getSelectedElement();if(a)return a.parentNode}else if(dojo.doc().selection)return dojo.doc().selection.createRange().parentElement();else if(a=dojo.global().getSelection()){for(a=a.anchorNode;a&&a.nodeType!=dojo.dom.ELEMENT_NODE;)a=a.parentNode;return a}},getSelectedText:function(){if(dojo.doc().selection){if(dojo.html.selection.getType()==dojo.html.selectionType.CONTROL)return null;return dojo.doc().selection.createRange().text}else{var a=dojo.global().getSelection();if(a)return a.toString()}},
getSelectedHtml:function(){if(dojo.doc().selection){if(dojo.html.selection.getType()==dojo.html.selectionType.CONTROL)return null;return dojo.doc().selection.createRange().htmlText}else{var a=dojo.global().getSelection();if(a&&a.rangeCount){a=a.getRangeAt(0).cloneContents();var b=document.createElement("div");b.appendChild(a);return b.innerHTML}return null}},hasAncestorElement:function(){return dojo.html.selection.getAncestorElement.apply(this,arguments)!=null},getAncestorElement:function(){for(var a=
dojo.html.selection.getSelectedElement()||dojo.html.selection.getParentElement();a;){if(dojo.html.selection.isTag(a,arguments).length>0)return a;a=a.parentNode}return null},isTag:function(a,b){if(a&&a.tagName)for(var c=0;c<b.length;c++)if(a.tagName.toLowerCase()==String(b[c]).toLowerCase())return String(b[c]).toLowerCase();return""},selectElement:function(a){var b=dojo.global(),c=dojo.doc();a=dojo.byId(a);if(c.selection&&dojo.body().createTextRange)try{var d=dojo.body().createControlRange();d.addElement(a);
d.select()}catch(e){dojo.html.selection.selectElementChildren(a)}else if(b.getSelection){b=b.getSelection();if(b.removeAllRanges){d=c.createRange();d.selectNode(a);b.removeAllRanges();b.addRange(d)}}},selectElementChildren:function(a){var b=dojo.global(),c=dojo.doc();a=dojo.byId(a);if(c.selection&&dojo.body().createTextRange){b=dojo.body().createTextRange();b.moveToElementText(a);b.select()}else if(b.getSelection){b=b.getSelection();if(b.setBaseAndExtent)b.setBaseAndExtent(a,0,a,a.innerText.length-
1);else b.selectAllChildren&&b.selectAllChildren(a)}},getBookmark:function(){var a,b=dojo.doc();if(b.selection){a=b.selection.createRange();a=a.getBookmark()}else{var c;try{c=dojo.global().getSelection()}catch(d){}if(c){a=c.getRangeAt(0);a=a.cloneRange()}else dojo.debug("No idea how to store the current selection for this browser!")}return a},moveToBookmark:function(a){var b=dojo.doc();if(b.selection){b=b.selection.createRange();b.moveToBookmark(a);b.select()}else{var c;try{c=dojo.global().getSelection()}catch(d){}if(c&&
c.removeAllRanges){c.removeAllRanges();c.addRange(a)}else dojo.debug("No idea how to restore selection for this browser!")}},collapse:function(a){if(dojo.global().getSelection){var b=dojo.global().getSelection();if(b.removeAllRanges)a?b.collapseToStart():b.collapseToEnd();else dojo.global().getSelection().collapse(a)}else if(dojo.doc().selection){b=dojo.doc().selection.createRange();b.collapse(a);b.select()}},remove:function(){if(dojo.doc().selection){var a=dojo.doc().selection;a.type.toUpperCase()!=
"NONE"&&a.clear()}else{a=dojo.global().getSelection();for(var b=0;b<a.rangeCount;b++)a.getRangeAt(b).deleteContents()}return a}});
