dojo.provide("dojo.html.util");dojo.require("dojo.html.layout");dojo.html.getElementWindow=function(a){return dojo.html.getDocumentWindow(a.ownerDocument)};
dojo.html.getDocumentWindow=function(a){if(dojo.render.html.safari&&!a._parentWindow){var c=function(b){b.document._parentWindow=b;for(var f=0;f<b.frames.length;f++)c(b.frames[f])};c(window.top)}if(dojo.render.html.ie&&window!==document.parentWindow&&!a._parentWindow){a.parentWindow.execScript("document._parentWindow = window;","Javascript");var d=a._parentWindow;a._parentWindow=null;return d}return a._parentWindow||a.parentWindow||a.defaultView};
dojo.html.gravity=function(a,c){a=dojo.byId(a);var d=dojo.html.getCursorPosition(c);with(dojo.html){var b=getAbsolutePosition(a,true),f=getBorderBox(a),e=b.x+f.width/2;b=b.y+f.height/2}with(dojo.html.gravity)return(d.x<e?WEST:EAST)|(d.y<b?NORTH:SOUTH)};dojo.html.gravity.NORTH=1;dojo.html.gravity.SOUTH=2;dojo.html.gravity.EAST=4;dojo.html.gravity.WEST=8;
dojo.html.overElement=function(a,c){a=dojo.byId(a);var d=dojo.html.getCursorPosition(c),b=dojo.html.getBorderBox(a),f=dojo.html.getAbsolutePosition(a,true,dojo.html.boxSizing.BORDER_BOX),e=f.y,g=e+b.height;f=f.x;b=f+b.width;return d.x>=f&&d.x<=b&&d.y>=e&&d.y<=g};
dojo.html.renderedTextContent=function(a){a=dojo.byId(a);var c="";if(a==null)return c;for(var d=0;d<a.childNodes.length;d++)switch(a.childNodes[d].nodeType){case 1:case 5:var b="unknown";try{b=dojo.html.getStyle(a.childNodes[d],"display")}catch(f){}switch(b){case "block":case "list-item":case "run-in":case "table":case "table-row-group":case "table-header-group":case "table-footer-group":case "table-row":case "table-column-group":case "table-column":case "table-cell":case "table-caption":c+="\n";
c+=dojo.html.renderedTextContent(a.childNodes[d]);c+="\n";break;case "none":break;default:c+=a.childNodes[d].tagName&&a.childNodes[d].tagName.toLowerCase()=="br"?"\n":dojo.html.renderedTextContent(a.childNodes[d]);break}break;case 3:case 2:case 4:var e=a.childNodes[d].nodeValue;b="unknown";try{b=dojo.html.getStyle(a,"text-transform")}catch(g){}switch(b){case "capitalize":e=e.split(" ");for(d=0;d<e.length;d++)e[d]=e[d].charAt(0).toUpperCase()+e[d].substring(1);e=e.join(" ");break;case "uppercase":e=
e.toUpperCase();break;case "lowercase":e=e.toLowerCase();break;default:break}switch(b){case "nowrap":break;case "pre-wrap":break;case "pre-line":break;case "pre":break;default:e=e.replace(/\s+/," ");/\s$/.test(c)&&e.replace(/^\s/,"");break}c+=e;break;default:break}return c};
dojo.html.createNodesFromText=function(a,c){if(c)a=a.replace(/^\s+|\s+$/g,"");var d=dojo.doc().createElement("div");d.style.visibility="hidden";dojo.body().appendChild(d);var b="none";if(/^<t[dh][\s\r\n>]/i.test(a.replace(/^\s+/))){a="<table><tbody><tr>"+a+"</tr></tbody></table>";b="cell"}else if(/^<tr[\s\r\n>]/i.test(a.replace(/^\s+/))){a="<table><tbody>"+a+"</tbody></table>";b="row"}else if(/^<(thead|tbody|tfoot)[\s\r\n>]/i.test(a.replace(/^\s+/))){a="<table>"+a+"</table>";b="section"}d.innerHTML=
a;d.normalize&&d.normalize();var f=null;switch(b){case "cell":f=d.getElementsByTagName("tr")[0];break;case "row":f=d.getElementsByTagName("tbody")[0];break;case "section":f=d.getElementsByTagName("table")[0];break;default:f=d;break}b=[];for(var e=0;e<f.childNodes.length;e++)b.push(f.childNodes[e].cloneNode(true));d.style.display="none";dojo.html.destroyNode(d);return b};
dojo.html.placeOnScreen=function(a,c,d,b,f,e,g){if(c instanceof Array||typeof c=="array"){g=e;e=f;f=b;b=d;d=c[1];c=c[0]}if(e instanceof String||typeof e=="string")e=e.split(",");if(isNaN(b))b instanceof Array||typeof b=="array"||(b=[0,0]);else b=[Number(b),Number(b)];var i=dojo.html.getScroll().offset,j=dojo.html.getViewport();a=dojo.byId(a);var h=a.style.display;a.style.display="";var k=dojo.html.getBorderBox(a),m=k.width;k=k.height;a.style.display=h;e instanceof Array||typeof e=="array"||(e=["TL"]);
var n,t;h=Infinity;for(var u,v=0;v<e.length;++v){var q=e[v],l=true,r=c-(q.charAt(1)=="L"?0:m)+b[0]*(q.charAt(1)=="L"?1:-1),s=d-(q.charAt(0)=="T"?0:k)+b[1]*(q.charAt(0)=="T"?1:-1);if(f){r-=i.x;s-=i.y}if(r<0){r=0;l=false}if(s<0){s=0;l=false}var o;if(r+m>j.width){o=j.width-m;l=false}else o=r;o=Math.max(b[0],o)+i.x;var p;if(s+k>j.height){p=j.height-k;l=false}else p=s;p=Math.max(b[1],p)+i.y;if(l){n=o;t=p;h=0;u=q;break}else{l=Math.pow(o-r-i.x,2)+Math.pow(p-s-i.y,2);if(h>l){h=l;n=o;t=p;u=q}}}if(!g){a.style.left=
n+"px";a.style.top=t+"px"}return{left:n,top:t,x:n,y:t,dist:h,corner:u}};dojo.html.placeOnScreenPoint=function(a,c,d,b,f){dojo.deprecated("dojo.html.placeOnScreenPoint","use dojo.html.placeOnScreen() instead","0.5");return dojo.html.placeOnScreen(a,c,d,b,f,["TL","TR","BL","BR"])};
dojo.html.placeOnScreenAroundElement=function(a,c,d,b,f,e){var g,i=Infinity;c=dojo.byId(c);var j=c.style.display;c.style.display="";var h=dojo.html.getElementBox(c,b),k=h.width;h=h.height;b=dojo.html.getAbsolutePosition(c,true,b);c.style.display=j;for(var m in f){var n=f[m];c=b.x+(m.charAt(1)=="L"?0:k);j=b.y+(m.charAt(0)=="T"?0:h);c=dojo.html.placeOnScreen(a,c,j,d,true,n,true);if(c.dist==0){g=c;break}else if(i>c.dist){i=c.dist;g=c}}if(!e){a.style.left=g.left+"px";a.style.top=g.top+"px"}return g};
dojo.html.scrollIntoView=function(a){if(a)if(dojo.render.html.ie)dojo.html.getBorderBox(a.parentNode).height<=a.parentNode.scrollHeight&&a.scrollIntoView(false);else if(dojo.render.html.mozilla)a.scrollIntoView(false);else{var c=a.parentNode,d=c.scrollTop+dojo.html.getBorderBox(c).height,b=a.offsetTop+dojo.html.getMarginBox(a).height;if(d<b)c.scrollTop+=b-d;else if(c.scrollTop>a.offsetTop)c.scrollTop-=c.scrollTop-a.offsetTop}};
