dojo.provide("dojo.widget.Dialog");dojo.require("dojo.widget.*");dojo.require("dojo.widget.ContentPane");dojo.require("dojo.event.*");dojo.require("dojo.gfx.color");dojo.require("dojo.html.layout");dojo.require("dojo.html.display");dojo.require("dojo.html.iframe");
dojo.declare("dojo.widget.ModalDialogBase",null,{isContainer:true,focusElement:"",bgColor:"black",bgOpacity:0.4,followScroll:true,closeOnBackgroundClick:false,trapTabs:function(a){if(a.target==this.tabStartOuter)if(this._fromTrap){this.tabStart.focus();this._fromTrap=false}else{this._fromTrap=true;this.tabEnd.focus()}else if(a.target==this.tabStart)if(this._fromTrap)this._fromTrap=false;else{this._fromTrap=true;this.tabEnd.focus()}else if(a.target==this.tabEndOuter)if(this._fromTrap){this.tabEnd.focus();
this._fromTrap=false}else{this._fromTrap=true;this.tabStart.focus()}else if(a.target==this.tabEnd)if(this._fromTrap)this._fromTrap=false;else{this._fromTrap=true;this.tabStart.focus()}},clearTrap:function(){var a=this;setTimeout(function(){a._fromTrap=false},100)},postCreate:function(){with(this.domNode.style){position="absolute";zIndex=999;display="none";overflow="visible"}var a=dojo.body();a.appendChild(this.domNode);this.bg=document.createElement("div");this.bg.className="dialogUnderlay";with(this.bg.style){position=
"absolute";left=top="0px";zIndex=998;display="none"}a.appendChild(this.bg);this.setBackgroundColor(this.bgColor);this.bgIframe=new dojo.html.BackgroundIframe;if(this.bgIframe.iframe)with(this.bgIframe.iframe.style){position="absolute";left=top="0px";zIndex=90;display="none"}this.closeOnBackgroundClick&&dojo.event.kwConnect({srcObj:this.bg,srcFunc:"onclick",adviceObj:this,adviceFunc:"onBackgroundClick",once:true})},uninitialize:function(){this.bgIframe.remove();dojo.html.removeNode(this.bg,true)},
setBackgroundColor:function(a){a=arguments.length>=3?new dojo.gfx.color.Color(arguments[0],arguments[1],arguments[2]):new dojo.gfx.color.Color(a);this.bg.style.backgroundColor=a.toString();return this.bgColor=a},setBackgroundOpacity:function(a){if(arguments.length==0)a=this.bgOpacity;dojo.html.setOpacity(this.bg,a);try{this.bgOpacity=dojo.html.getOpacity(this.bg)}catch(b){this.bgOpacity=a}return this.bgOpacity},_sizeBackground:function(){if(this.bgOpacity>0){var a=dojo.html.getViewport(),b=a.height,
c=a.width;with(this.bg.style){width=c+"px";height=b+"px"}a=dojo.html.getScroll().offset;this.bg.style.top=a.y+"px";this.bg.style.left=a.x+"px";a=dojo.html.getViewport();if(a.width!=c)this.bg.style.width=a.width+"px";if(a.height!=b)this.bg.style.height=a.height+"px"}this.bgIframe.size(this.bg)},_showBackground:function(){if(this.bgOpacity>0)this.bg.style.display="block";if(this.bgIframe.iframe)this.bgIframe.iframe.style.display="block"},placeModalDialog:function(){var a=dojo.html.getScroll().offset,
b=dojo.html.getViewport(),c;if(this.isShowing())c=dojo.html.getMarginBox(this.domNode);else{dojo.html.setVisibility(this.domNode,false);dojo.html.show(this.domNode);c=dojo.html.getMarginBox(this.domNode);dojo.html.hide(this.domNode);dojo.html.setVisibility(this.domNode,true)}var d=a.x+(b.width-c.width)/2;a=a.y+(b.height-c.height)/2;with(this.domNode.style){left=d+"px";top=a+"px"}},_onKey:function(a){if(a.key){for(var b=a.target;b!=null;){if(b==this.domNode)return;b=b.parentNode}if(a.key!=a.KEY_TAB)dojo.event.browser.stopEvent(a);
else if(!dojo.render.html.opera)try{this.tabStart.focus()}catch(c){}}},showModalDialog:function(){if(this.followScroll&&!this._scrollConnected){this._scrollConnected=true;dojo.event.connect(window,"onscroll",this,"_onScroll")}dojo.event.connect(document.documentElement,"onkey",this,"_onKey");this.placeModalDialog();this.setBackgroundOpacity();this._sizeBackground();this._showBackground();this._fromTrap=true;setTimeout(dojo.lang.hitch(this,function(){try{this.tabStart.focus()}catch(a){}}),50)},hideModalDialog:function(){if(this.focusElement){dojo.byId(this.focusElement).focus();
dojo.byId(this.focusElement).blur()}this.bg.style.display="none";this.bg.style.width=this.bg.style.height="1px";if(this.bgIframe.iframe)this.bgIframe.iframe.style.display="none";dojo.event.disconnect(document.documentElement,"onkey",this,"_onKey");if(this._scrollConnected){this._scrollConnected=false;dojo.event.disconnect(window,"onscroll",this,"_onScroll")}},_onScroll:function(){var a=dojo.html.getScroll().offset;this.bg.style.top=a.y+"px";this.bg.style.left=a.x+"px";this.placeModalDialog()},checkSize:function(){if(this.isShowing()){this._sizeBackground();
this.placeModalDialog();this.onResized()}},onBackgroundClick:function(){this.lifetime-this.timeRemaining>=this.blockDuration||this.hide()}});
dojo.widget.defineWidget("dojo.widget.Dialog",[dojo.widget.ContentPane,dojo.widget.ModalDialogBase],{templateString:'<div id="${this.widgetId}" class="dojoDialog" dojoattachpoint="wrapper">\n\t<span dojoattachpoint="tabStartOuter" dojoonfocus="trapTabs" dojoonblur="clearTrap"\ttabindex="0"></span>\n\t<span dojoattachpoint="tabStart" dojoonfocus="trapTabs" dojoonblur="clearTrap" tabindex="0"></span>\n\t<div dojoattachpoint="containerNode" style="position: relative; z-index: 2;"></div>\n\t<span dojoattachpoint="tabEnd" dojoonfocus="trapTabs" dojoonblur="clearTrap" tabindex="0"></span>\n\t<span dojoattachpoint="tabEndOuter" dojoonfocus="trapTabs" dojoonblur="clearTrap" tabindex="0"></span>\n</div>\n',blockDuration:0,
lifetime:0,closeNode:"",postMixInProperties:function(){dojo.widget.Dialog.superclass.postMixInProperties.apply(this,arguments);this.closeNode&&this.setCloseControl(this.closeNode)},postCreate:function(){dojo.widget.Dialog.superclass.postCreate.apply(this,arguments);dojo.widget.ModalDialogBase.prototype.postCreate.apply(this,arguments)},show:function(){if(this.lifetime){this.timeRemaining=this.lifetime;if(this.timerNode)this.timerNode.innerHTML=Math.ceil(this.timeRemaining/1E3);if(this.blockDuration&&
this.closeNode)if(this.lifetime>this.blockDuration)this.closeNode.style.visibility="hidden";else this.closeNode.style.display="none";this.timer&&clearInterval(this.timer);this.timer=setInterval(dojo.lang.hitch(this,"_onTick"),100)}this.showModalDialog();dojo.widget.Dialog.superclass.show.call(this)},onLoad:function(){this.placeModalDialog();dojo.widget.Dialog.superclass.onLoad.call(this)},fillInTemplate:function(){},hide:function(){this.hideModalDialog();dojo.widget.Dialog.superclass.hide.call(this);
this.timer&&clearInterval(this.timer)},setTimerNode:function(a){this.timerNode=a},setCloseControl:function(a){this.closeNode=dojo.byId(a);dojo.event.connect(this.closeNode,"onclick",this,"hide")},setShowControl:function(a){a=dojo.byId(a);dojo.event.connect(a,"onclick",this,"show")},_onTick:function(){if(this.timer){this.timeRemaining-=100;if(this.lifetime-this.timeRemaining>=this.blockDuration)if(this.closeNode)this.closeNode.style.visibility="visible";if(this.timeRemaining){if(this.timerNode)this.timerNode.innerHTML=
Math.ceil(this.timeRemaining/1E3)}else{clearInterval(this.timer);this.hide()}}}});
