dojo.provide("dojo.widget.DomWidget");dojo.require("dojo.event.*");dojo.require("dojo.widget.Widget");dojo.require("dojo.dom");dojo.require("dojo.html.style");dojo.require("dojo.xml.Parse");dojo.require("dojo.uri.*");dojo.require("dojo.lang.func");dojo.require("dojo.lang.extras");dojo.widget._cssFiles={};dojo.widget._cssStrings={};dojo.widget._templateCache={};dojo.widget.defaultStrings={dojoRoot:dojo.hostenv.getBaseScriptUri(),dojoWidgetModuleUri:dojo.uri.moduleUri("dojo.widget"),baseScriptUri:dojo.hostenv.getBaseScriptUri()};
dojo.widget.fillFromTemplateCache=function(a,b,d,c){var e=b||a.templatePath;b=dojo.widget._templateCache;if(!e&&!a.widgetType){do var g="__dummyTemplate__"+dojo.widget._templateCache.dummyCount++;while(b[g]);a.widgetType=g}g=e?e.toString():a.widgetType;var h=b[g];if(!h){b[g]={string:null,node:null};h=c?{}:b[g]}if(!a.templateString&&!c)a.templateString=d||h.string;if(a.templateString)a.templateString=this._sanitizeTemplateString(a.templateString);if(!a.templateNode&&!c)a.templateNode=h.node;if(!a.templateNode&&
!a.templateString&&e){d=this._sanitizeTemplateString(dojo.hostenv.getText(e));a.templateString=d;c||(b[g].string=d)}if(!h.string&&!c)h.string=a.templateString};dojo.widget._sanitizeTemplateString=function(a){if(a){a=a.replace(/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,"");var b=a.match(/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im);if(b)a=b[1]}else a="";return a};dojo.widget._templateCache.dummyCount=0;dojo.widget.attachProperties=["dojoAttachPoint","id"];
dojo.widget.eventAttachProperty="dojoAttachEvent";dojo.widget.onBuildProperty="dojoOnBuild";dojo.widget.waiNames=["waiRole","waiState"];
dojo.widget.wai={waiRole:{name:"waiRole",namespace:"http://www.w3.org/TR/xhtml2",alias:"x2",prefix:"wairole:"},waiState:{name:"waiState",namespace:"http://www.w3.org/2005/07/aaa",alias:"aaa",prefix:""},setAttr:function(a,b,d,c){dojo.render.html.ie?a.setAttribute(this[b].alias+":"+d,this[b].prefix+c):a.setAttributeNS(this[b].namespace,d,this[b].prefix+c)},getAttr:function(a,b,d){return dojo.render.html.ie?a.getAttribute(this[b].alias+":"+d):a.getAttributeNS(this[b].namespace,d)},removeAttr:function(a,
b,d){var c=true;if(dojo.render.html.ie)c=a.removeAttribute(this[b].alias+":"+d);else a.removeAttributeNS(this[b].namespace,d);return c}};
dojo.widget.attachTemplateNodes=function(a,b,d){function c(i){return i.replace(/^\s+|\s+$/g,"")}var e=dojo.dom.ELEMENT_NODE;if(!a)a=b.domNode;if(a.nodeType==e){e=a.all||a.getElementsByTagName("*");for(var g=-1;g<e.length;g++){var h=g==-1?a:e[g],f=[];if(!b.widgetsInTemplate||!h.getAttribute("dojoType")){for(f=0;f<this.attachProperties.length;f++){var k=h.getAttribute(this.attachProperties[f]);if(k){f=k.split(";");for(var l=0;l<f.length;l++)if(dojo.lang.isArray(b[f[l]]))b[f[l]].push(h);else b[f[l]]=
h;break}}if(f=h.getAttribute(this.eventAttachProperty)){k=f.split(";");for(f=0;f<k.length;f++)if(k[f]&&k[f].length){var m=null,n=c(k[f]);if(k[f].indexOf(":")>=0){var o=n.split(":");n=c(o[0]);m=c(o[1])}m||(m=n);o=function(){var i=new String(m);return function(j){b[i]&&b[i](dojo.event.browser.fixEvent(j,this))}}();dojo.event.browser.addListener(h,n,o,false,true)}}for(f=0;f<d.length;f++)if((n=h.getAttribute(d[f]))&&n.length){m=null;k=d[f].substr(4);m=c(n);var p=[m];if(m.indexOf(";")>=0)p=dojo.lang.map(m.split(";"),
c);for(l=0;l<p.length;l++)if(p[l].length){o=function(){var i=new String(p[l]);return function(j){b[i]&&b[i](dojo.event.browser.fixEvent(j,this))}}();dojo.event.browser.addListener(h,k,o,false,true)}}}if(f=h.getAttribute(this.templateProperty))b[f]=h;dojo.lang.forEach(dojo.widget.waiNames,function(i){i=dojo.widget.wai[i];var j=h.getAttribute(i.name);if(j)if(j.indexOf("-")==-1)dojo.widget.wai.setAttr(h,i.name,"role",j);else{j=j.split("-");dojo.widget.wai.setAttr(h,i.name,j[0],j[1])}},this);(f=h.getAttribute(this.onBuildProperty))&&
eval("var node = baseNode; var widget = targetObj; "+f)}}};dojo.widget.getDojoEventsFromStr=function(a){var b=/(dojoOn([a-z]+)(\s?))=/gi;a=a?a.match(b)||[]:[];b=[];for(var d={},c=0;c<a.length;c++)if(!(a[c].length<1)){var e=a[c].replace(/\s/,"");e=e.slice(0,e.length-1);if(!d[e]){d[e]=true;b.push(e)}}return b};
dojo.declare("dojo.widget.DomWidget",dojo.widget.Widget,function(){arguments.length>0&&typeof arguments[0]=="object"&&this.create(arguments[0])},{templateNode:null,templateString:null,templateCssString:null,preventClobber:false,domNode:null,containerNode:null,widgetsInTemplate:false,addChild:function(a,b,d,c,e){if(this.isContainer){if(e==undefined)e=this.children.length;this.addWidgetAsDirectChild(a,b,d,c,e);this.registerChild(a,e)}else{dojo.debug("dojo.widget.DomWidget.addChild() attempted on non-container widget");
return null}return a},addWidgetAsDirectChild:function(a,b,d,c,e){if(!this.containerNode&&!b)this.containerNode=this.domNode;b=b?b:this.containerNode;d||(d="after");if(!c){b||(b=dojo.body());c=b.lastChild}e||(e=0);a.domNode.setAttribute("dojoinsertionindex",e);if(c)if(d=="insertAtIndex")dojo.dom.insertAtIndex(a.domNode,c.parentNode,e);else d=="after"&&c===b.lastChild?b.appendChild(a.domNode):dojo.dom.insertAtPosition(a.domNode,b,d);else b.appendChild(a.domNode)},registerChild:function(a,b){a.dojoInsertionIndex=
b;for(var d=-1,c=0;c<this.children.length;c++)if(this.children[c].dojoInsertionIndex<=b)d=c;this.children.splice(d+1,0,a);a.parent=this;a.addedTo(this,d+1);delete dojo.widget.manager.topWidgets[a.widgetId]},removeChild:function(a){dojo.dom.removeNode(a.domNode);return dojo.widget.DomWidget.superclass.removeChild.call(this,a)},getFragNodeRef:function(a){if(!a)return null;a[this.getNamespacedType()]||dojo.raise("Error: no frag for widget type "+this.getNamespacedType()+", id "+this.widgetId+" (maybe a widget has set it's type incorrectly)");
return a[this.getNamespacedType()].nodeRef},postInitialize:function(a,b,d){var c=this.getFragNodeRef(b);if(d&&(d.snarfChildDomOutput||!c))d.addWidgetAsDirectChild(this,"","insertAtIndex","",a.dojoinsertionindex,c);else if(c)if(this.domNode&&this.domNode!==c)this._sourceNodeRef=dojo.dom.replaceNode(c,this.domNode);if(d)d.registerChild(this,a.dojoinsertionindex);else dojo.widget.manager.topWidgets[this.widgetId]=this;if(this.widgetsInTemplate){d=new dojo.xml.Parse;var e;c=this.domNode.getElementsByTagName("*");
for(a=0;a<c.length;a++){if(c[a].getAttribute("dojoAttachPoint")=="subContainerWidget")e=c[a];c[a].getAttribute("dojoType")&&c[a].setAttribute("isSubWidget",true)}if(this.isContainer&&!this.containerNode)if(e){if(a=this.getFragNodeRef(b)){dojo.dom.moveChildren(a,e);b.dojoDontFollow=true}}else dojo.debug("No subContainerWidget node can be found in template file for widget "+this);a=d.parseElement(this.domNode,null,true);dojo.widget.getParser().createSubComponents(a,this);e=[];for(d=[this];c=d.pop();)for(a=
0;a<c.children.length;a++){var g=c.children[a];if(!(g._processedSubWidgets||!g.extraArgs.issubwidget)){e.push(g);g.isContainer&&d.push(g)}}for(a=0;a<e.length;a++){d=e[a];if(d._processedSubWidgets){dojo.debug("This should not happen: widget._processedSubWidgets is already true!");return}d._processedSubWidgets=true;if(d.extraArgs.dojoattachevent){c=d.extraArgs.dojoattachevent.split(";");for(g=0;g<c.length;g++){var h=null,f=dojo.string.trim(c[g]);if(f.indexOf(":")>=0){h=f.split(":");f=dojo.string.trim(h[0]);
h=dojo.string.trim(h[1])}h||(h=f);dojo.lang.isFunction(d[f])?dojo.event.kwConnect({srcObj:d,srcFunc:f,targetObj:this,targetFunc:h}):alert(f+" is not a function in widget "+d)}}if(d.extraArgs.dojoattachpoint)this[d.extraArgs.dojoattachpoint]=d}}this.isContainer&&!b.dojoDontFollow&&dojo.widget.getParser().createSubComponents(b,this)},buildRendering:function(a,b){var d=dojo.widget._templateCache[this.widgetType];if(a.templatecsspath)a.templateCssPath=a.templatecsspath;var c=a.templateCssPath||this.templateCssPath;
if(c&&!dojo.widget._cssFiles[c.toString()]){if(!this.templateCssString&&c){this.templateCssString=dojo.hostenv.getText(c);this.templateCssPath=null}dojo.widget._cssFiles[c.toString()]=true}if(this.templateCssString&&!dojo.widget._cssStrings[this.templateCssString]){dojo.html.insertCssText(this.templateCssString,null,c);dojo.widget._cssStrings[this.templateCssString]=true}if(!this.preventClobber&&(this.templatePath||this.templateNode||this.templateString&&this.templateString.length||typeof d!="undefined"&&
(d.string||d.node)))this.buildFromTemplate(a,b);else this.domNode=this.getFragNodeRef(b);this.fillInTemplate(a,b)},buildFromTemplate:function(a,b){if(a.templatepath)a.templatePath=a.templatepath;dojo.widget.fillFromTemplateCache(this,a.templatePath,null,false);var d=dojo.widget._templateCache[this.templatePath?this.templatePath.toString():this.widgetType];if(d){if(!this.templateString.length)this.templateString=d.string;if(!this.templateNode)this.templateNode=d.node}var c=false,e=null;e=this.templateString;
if(!this.templateNode&&this.templateString)if(c=this.templateString.match(/\$\{([^\}]+)\}/g)){d=this.strings||{};for(var g in dojo.widget.defaultStrings)if(dojo.lang.isUndefined(d[g]))d[g]=dojo.widget.defaultStrings[g];for(var h=0;h<c.length;h++){g=c[h];g=g.substring(2,g.length-1);var f=g.substring(0,5)=="this."?dojo.lang.getObjPathValue(g.substring(5),this):d[g];if(f||dojo.lang.isString(f)){for(g=new String(dojo.lang.isFunction(f)?f.call(this,g,this.templateString):f);g.indexOf('"')>-1;)g=g.replace('"',
"&quot;");e=e.replace(c[h],g)}}}else{this.templateNode=this.createNodesFromText(this.templateString,true)[0];d.node=this.templateNode}if(!this.templateNode&&!c){dojo.debug("DomWidget.buildFromTemplate: could not create template");return false}else if(c)e=this.createNodesFromText(e,true)[0];else{e=this.templateNode.cloneNode(true);if(!e)return false}this.domNode=e;this.attachTemplateNodes();if(this.isContainer&&this.containerNode)(c=this.getFragNodeRef(b))&&dojo.dom.moveChildren(c,this.containerNode)},
attachTemplateNodes:function(a,b){if(!a)a=this.domNode;b||(b=this);return dojo.widget.attachTemplateNodes(a,b,dojo.widget.getDojoEventsFromStr(this.templateString))},fillInTemplate:function(){},destroyRendering:function(){try{dojo.dom.destroyNode(this.domNode);delete this.domNode}catch(a){}if(this._sourceNodeRef)try{dojo.dom.destroyNode(this._sourceNodeRef)}catch(b){}},createNodesFromText:function(){dojo.unimplemented("dojo.widget.DomWidget.createNodesFromText")}});
