dojo.provide("dojo.widget.Parse");dojo.require("dojo.widget.Manager");dojo.require("dojo.dom");
dojo.widget.Parse=function(e){this.propertySetsList=[];this.fragment=e;this.createComponents=function(a,d){var c=[],b=false;try{if(a&&a.tagName&&a!=a.nodeRef)for(var f=dojo.widget.tags,g=String(a.tagName).split(";"),i=0;i<g.length;i++){var h=g[i].replace(/^\s+|\s+$/g,"").toLowerCase();a.tagName=h;var j;if(f[h]){b=true;j=f[h](a,this,d,a.index);c.push(j)}else{if(h.indexOf(":")==-1)h="dojo:"+h;if(j=dojo.widget.buildWidgetFromParseTree(h,a,this,d,a.index)){b=true;c.push(j)}}}}catch(k){dojo.debug("dojo.widget.Parse: error:",
k)}b||(c=c.concat(this.createSubComponents(a,d)));return c};this.createSubComponents=function(a,d){var c,b=[];for(var f in a)if((c=a[f])&&typeof c=="object"&&c!=a.nodeRef&&c!=a.tagName&&!dojo.dom.isNode(c))b=b.concat(this.createComponents(c,d));return b};this.parsePropertySets=function(){return[]};this.parseProperties=function(a){var d={};for(var c in a)if(!(a[c]==a.tagName||a[c]==a.nodeRef)){var b=a[c];if(!(b.tagName&&dojo.widget.tags[b.tagName.toLowerCase()]))if(b[0]&&b[0].value!=""&&b[0].value!=
null)try{if(c.toLowerCase()=="dataprovider"){this.getDataProvider(this,b[0].value);d.dataProvider=this.dataProvider}d[c]=b[0].value;var f=this.parseProperties(b);for(var g in f)d[g]=f[g]}catch(i){dojo.debug(i)}switch(c.toLowerCase()){case "checked":case "disabled":if(typeof d[c]!="boolean")d[c]=true;break}}return d};this.getDataProvider=function(a,d){dojo.io.bind({url:d,load:function(c,b){if(c=="load")a.dataProvider=b},mimetype:"text/javascript",sync:true})};this.getPropertySetById=function(a){for(var d=
0;d<this.propertySetsList.length;d++)if(a==this.propertySetsList[d].id[0].value)return this.propertySetsList[d];return""};this.getPropertySetsByType=function(){for(var a=[],d=0;d<this.propertySetsList.length;d++){var c=this.propertySetsList[d],b=c.componentClass||c.componentType||null,f=this.propertySetsList[d].id[0].value;b&&f==b[0].value&&a.push(c)}return a};this.getPropertySets=function(a){var d=[],c=a.tagName;if(a["dojo:propertyproviderlist"]){a=a["dojo:propertyproviderlist"].value.split(" ");
for(var b in a)if(b.indexOf("..")==-1&&b.indexOf("://")==-1){var f=this.getPropertySetById(b);f!=""&&d.push(f)}}return this.getPropertySetsByType(c).concat(d)};this.createComponentFromScript=function(a,d,c,b){c.fastMixIn=true;a=(b||"dojo")+":"+d.toLowerCase();if(dojo.widget.tags[a])return[dojo.widget.tags[a](c,this,null,null,c)];return[dojo.widget.buildWidgetFromParseTree(a,c,this,null,null,c)]}};dojo.widget._parser_collection={dojo:new dojo.widget.Parse};
dojo.widget.getParser=function(e){e||(e="dojo");this._parser_collection[e]||(this._parser_collection[e]=new dojo.widget.Parse);return this._parser_collection[e]};
dojo.widget.createWidget=function(e,a,d,c){var b=false,f=typeof e=="string";if(f){b=e.indexOf(":");var g=b>-1?e.substring(0,b):"dojo";if(b>-1)e=e.substring(b+1);var i=e.toLowerCase(),h=g+":"+i;b=dojo.byId(e)&&!dojo.widget.tags[h]}if(arguments.length==1&&(b||!f)){g=new dojo.xml.Parse;b=b?dojo.byId(e):e;return dojo.widget.getParser().createComponents(g.parseElement(b,null,true))[0]}a=a||{};f=false;b=null;var j=dojo.render.html.capable;if(j)b=document.createElement("span");if(d)if(c)dojo.dom.insertAtPosition(b,
d,c);else b=d;else{f=true;j&&dojo.body().appendChild(b)}g=function(m,o,l,n){l[h]={dojotype:[{value:i}],nodeRef:m,fastMixIn:true};l.ns=n;return dojo.widget.getParser().createComponentFromScript(m,o,l,n)}(b,e.toLowerCase(),a,g);if(!g||!g[0]||typeof g[0].widgetType=="undefined")throw new Error('createWidget: Creation of "'+e+'" widget failed.');try{f&&g[0].domNode.parentNode&&g[0].domNode.parentNode.removeChild(g[0].domNode)}catch(k){dojo.debug(k)}return g[0]};
