dojo.provide("dojo.widget.Widget");dojo.require("dojo.lang.func");dojo.require("dojo.lang.array");dojo.require("dojo.lang.extras");dojo.require("dojo.lang.declare");dojo.require("dojo.ns");dojo.require("dojo.widget.Manager");dojo.require("dojo.event.*");dojo.require("dojo.a11y");
dojo.declare("dojo.widget.Widget",null,function(){this.children=[];this.extraArgs={}},{parent:null,isTopLevel:false,disabled:false,isContainer:false,widgetId:"",widgetType:"Widget",ns:"dojo",getNamespacedType:function(){return(this.ns?this.ns+":"+this.widgetType:this.widgetType).toLowerCase()},toString:function(){return"[Widget "+this.getNamespacedType()+", "+(this.widgetId||"NO ID")+"]"},repr:function(){return this.toString()},enable:function(){this.disabled=false},disable:function(){this.disabled=
true},onResized:function(){this.notifyChildrenOfResize()},notifyChildrenOfResize:function(){for(var a=0;a<this.children.length;a++){var c=this.children[a];c.onResized&&c.onResized()}},create:function(a,c,b,e){if(e)this.ns=e;this.satisfyPropertySets(a,c,b);this.mixInProperties(a,c,b);this.postMixInProperties(a,c,b);dojo.widget.manager.add(this);this.buildRendering(a,c,b);this.initialize(a,c,b);this.postInitialize(a,c,b);this.postCreate(a,c,b);return this},destroy:function(a){this.parent&&this.parent.removeChild(this);
this.destroyChildren();this.uninitialize();this.destroyRendering(a);dojo.widget.manager.removeById(this.widgetId)},destroyChildren:function(){for(var a,c=0;this.children.length>c;){a=this.children[c];if(a instanceof dojo.widget.Widget){this.removeChild(a);a.destroy()}else c++}},getChildrenOfType:function(a,c){var b=[],e=dojo.lang.isFunction(a);e||(a=a.toLowerCase());for(var d=0;d<this.children.length;d++){if(e)this.children[d]instanceof a&&b.push(this.children[d]);else this.children[d].widgetType.toLowerCase()==
a&&b.push(this.children[d]);if(c)b=b.concat(this.children[d].getChildrenOfType(a,c))}return b},getDescendants:function(){for(var a=[],c=[this],b;b=c.pop();){a.push(b);b.children&&dojo.lang.forEach(b.children,function(e){c.push(e)})}return a},isFirstChild:function(){return this===this.parent.children[0]},isLastChild:function(){return this===this.parent.children[this.parent.children.length-1]},satisfyPropertySets:function(a){return a},mixInProperties:function(a,c){if(a.fastMixIn||c.fastMixIn)for(var b in a)this[b]=
a[b];else{var e=dojo.widget.lcArgsCache[this.widgetType];if(e==null){e={};for(var d in this)e[(new String(d)).toLowerCase()]=d;dojo.widget.lcArgsCache[this.widgetType]=e}var g={};for(b in a){if(!this[b])if(d=e[(new String(b)).toLowerCase()]){a[d]=a[b];b=d}if(!g[b]){g[b]=true;if(typeof this[b]!=typeof void 0)if(typeof a[b]!="string")this[b]=a[b];else if(dojo.lang.isString(this[b]))this[b]=a[b];else if(dojo.lang.isNumber(this[b]))this[b]=new Number(a[b]);else if(dojo.lang.isBoolean(this[b]))this[b]=
a[b].toLowerCase()=="false"?false:true;else if(dojo.lang.isFunction(this[b]))if(a[b].search(/[^\w\.]+/i)==-1)this[b]=dojo.evalObjPath(a[b],false);else{d=dojo.lang.nameAnonFunc(new Function(a[b]),this);dojo.event.kwConnect({srcObj:this,srcFunc:b,adviceObj:this,adviceFunc:d})}else if(dojo.lang.isArray(this[b]))this[b]=a[b].split(";");else if(this[b]instanceof Date)this[b]=new Date(Number(a[b]));else if(typeof this[b]=="object")if(this[b]instanceof dojo.uri.Uri)this[b]=dojo.uri.dojoUri(a[b]);else{var f=
a[b].split(";");for(d=0;d<f.length;d++){var h=f[d].indexOf(":");if(h!=-1&&f[d].length>h)this[b][f[d].substr(0,h).replace(/^\s+|\s+$/g,"")]=f[d].substr(h+1)}}else this[b]=a[b];else this.extraArgs[b.toLowerCase()]=a[b]}}}},postMixInProperties:function(){},initialize:function(){return false},postInitialize:function(){return false},postCreate:function(){return false},uninitialize:function(){return false},buildRendering:function(){dojo.unimplemented("dojo.widget.Widget.buildRendering, on "+this.toString()+
", ");return false},destroyRendering:function(){dojo.unimplemented("dojo.widget.Widget.destroyRendering");return false},addedTo:function(){},addChild:function(){dojo.unimplemented("dojo.widget.Widget.addChild");return false},removeChild:function(a){for(var c=0;c<this.children.length;c++)if(this.children[c]===a){this.children.splice(c,1);a.parent=null;break}return a},getPreviousSibling:function(){var a=this.getParentIndex();if(a<=0)return null;return this.parent.children[a-1]},getSiblings:function(){return this.parent.children},
getParentIndex:function(){return dojo.lang.indexOf(this.parent.children,this,true)},getNextSibling:function(){var a=this.getParentIndex();if(a==this.parent.children.length-1)return null;if(a<0)return null;return this.parent.children[a+1]}});dojo.widget.lcArgsCache={};dojo.widget.tags={};
dojo.widget.tags.addParseTreeHandler=function(){dojo.deprecated("addParseTreeHandler",". ParseTreeHandlers are now reserved for components. Any unfiltered DojoML tag without a ParseTreeHandler is assumed to be a widget","0.5")};dojo.widget.tags["dojo:propertyset"]=function(a,c){c.parseProperties(a["dojo:propertyset"])};dojo.widget.tags["dojo:connect"]=function(a,c){c.parseProperties(a["dojo:connect"])};
dojo.widget.buildWidgetFromParseTree=function(a,c,b,e,d,g){dojo.a11y.setAccessibleMode();var f=a.split(":");f=f.length==2?f[1]:a;b=g||b.parseProperties(c[c.ns+":"+f]);if(f=dojo.widget.manager.getImplementation(f,null,null,c.ns)){if(!f.create)throw new Error('"'+a+'" widget object has no "create" method and does not appear to implement *Widget');}else throw new Error('cannot find "'+a+'" widget');b.dojoinsertionindex=d;return f.create(b,c,e,c.ns)};
dojo.widget.defineWidget=function(){if(dojo.lang.isString(arguments[3]))dojo.widget._defineWidget(arguments[0],arguments[3],arguments[1],arguments[4],arguments[2]);else{var a=[arguments[0]],c=3;if(dojo.lang.isString(arguments[1]))a.push(arguments[1],arguments[2]);else{a.push("",arguments[1]);c=2}dojo.lang.isFunction(arguments[c])?a.push(arguments[c],arguments[c+1]):a.push(null,arguments[c]);dojo.widget._defineWidget.apply(this,a)}};dojo.widget.defineWidget.renderers="html|svg|vml";
dojo.widget._defineWidget=function(a,c,b,e,d){var g=a.split("."),f=g.pop();c=a.search(new RegExp("\\.("+(c?c+"|":"")+dojo.widget.defineWidget.renderers+")\\."));g=c<0?g.join("."):a.substr(0,c);dojo.widget.manager.registerWidgetPackage(g);c=g.indexOf(".");c>-1&&g.substring(0,c);d=d||{};d.widgetType=f;if(!e&&d.classConstructor){e=d.classConstructor;delete d.classConstructor}dojo.declare(a,b,e,d)};
